### ISSUE TITLE
The program's player displays files incorrectly

### ISSUE THREAD

**Issue by unjust-water** [mltframework/shotcut#1017]
I'm on Manjaro KDE, shotcut's version is 20.11.28-1, previous version of the program didn't have that issue. Tried mp4 and webm files.

https://user-images.githubusercontent.com/77757053/105250304-30f26480-5b82-11eb-8927-238d62d84acc.mp4

**Comment by ddennedy** [comment]
This happens when QT_SCALE_FACTOR is set to a non-integer value (e.g. 1.5) or possibly some combination of system Qt settings along with system display scale not a multiple of 100% (e.g. 125%). It is already fixed in 6865ddfbf45d7bd8d2070a56992f5cb413e78080 for the next version due by end of month, and you can get a beta here: https://github.com/mltframework/shotcut/actions/runs/498060048
