### ISSUE TITLE
Frame exporting, exports only one rich Text not all

### ISSUE THREAD

**Issue by uxadax** [mltframework/shotcut#1020]
Frame exporting, only exports one rich Text element not all.

- Win 10

**Comment by ddennedy** [comment]
This is a known problem when the Text: Rich is currently selected. In that case, the editor - a UI component - is showing and the video filter is hidden. Otherwise, things look weird when there is not perfect pixel match or video processing latency. There is a simple workaround for now: first deselect the current filter using the <kbd>X</kbd> button below the list of filters.
A fix is prepared for version 21.02 and not the next 21.01 due in a few days.
