### ISSUE TITLE
Shotcut crashes on Startup on Windows 

### ISSUE THREAD

**Issue by 4dbcc7e6c2** [mltframework/shotcut#1028]
Hi 
I am running Windows, Below are the OS Build details and basic computer specs.  Shotcut has started crashing on startup since I installed version 21.01.29, I uninstalled the program and selected remove shotcut settings from registry when I installed 21.0.29 again.  I then uninstalled v21.01.29 and removed all files that referenced shotcut from my disk.  I then installed v20.11.28 (the last version I had before updating to 21.01.29)  However this didn't fix the crashing problem.  I have attached the crash log generated by shotcut.  (v.21.01.29 didn't generate a report) The other thing that I noticed is that in Task manager shot cut is getting suspended before if can finish loading.  I don't know it this has anything to do with it.  

I hope I have provided enough details.  

Edition - Windows 10 Pro
OS build - 19042.789
CPU - i5-8265U
RAM - 16Gb
GPU - Intel UHD 620. 
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/5947746/shotcut-log.txt)

**Comment by ddennedy** [comment]
I have not experienced this myself and not many others have reported it, but for every new version some people always report some sort of failure or huge performance increase while hundreds of thousands of others get along just fine. One thing I have found is that people have an invalid upgrade. This typically occurs when trying to install to the same folder, and some files were not upgraded because they were locked possibly by a hidden, hung shotcut.exe or melt.exe process, but I see you effectively checked that. Looking at your log it, and I see it fails just before something like this that appears in a normal and healthy startup:
```
[Debug  ] <Mlt::GLWidget::initializeGL> begin 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL vendor "Google Inc." 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL renderer "ANGLE (Radeon RX 560 Series Direct3D11 vs_5_0 ps_5_0)" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL threaded? false 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL ES? true 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL maximum texture size = 16384 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL maximum viewport size = 32767 x 32767 
[Debug  ] <Mlt::GLWidget::initializeGL> end 
```
This suggests you have a problem in your DirectX, OpenGL, or Display Method in Shotcut settings. Of course, you cannot change the Shotcut settings menu if it is not starting. See this https://forum.shotcut.org/t/display-method/12705/2 for help.
You should try rebooting if you have not and after trying all these, maybe reinstall graphics driver. Also, try disconnecting an external monitor if you have that connected.

**Comment by 4dbcc7e6c2** [comment]
Thank you for your help, It is greatly appreciated

After, updating windows, updating the graphics driver, installing the OpenGL.reg file and rebooting Shotcut finally started.
