### ISSUE TITLE
Memory management issue

### ISSUE THREAD

**Issue by hagemann-one** [mltframework/shotcut#1055]
To whom it may concern,

I get frequently the following memory warning:
"You are running low on available memory!"
This is very annoying and did not happen on previous versions of your software. My computer has the following data:
Shotcut version 21.02.27
Windows 7 Ultimate
Processor: Intel Core i5-4200 CPU @1.60 GHz 2.30 GHz
RAM: 8.00 GB
64-bit Operating System

Kind regards
Walter
![Screenshot_18](https://user-images.githubusercontent.com/80745399/111276927-d867b100-8672-11eb-8532-306a72d3d708.jpg)

**Comment by ddennedy** [comment]
This is a recently added *feature* in version 20.11, not a bug. Previously, Shotcut would simply crash when it runs out of memory. It still can crash due to that, but this goes a long way to prevent that as well as prevent performance complaints because your system is constantly paging virtual memory to hard disk. You cannot make something heavy like multitrack video editing run in the tiniest amount of available memory. Your options are:

1. follow the directions provided
2. make simpler, low resolution projects
3. get more RAM
4. run an older version
