### ISSUE TITLE
Why's Shotcut isn't working on my Chromebook's Linux Beta?

### ISSUE THREAD

**Issue by Calvin242** [mltframework/shotcut#1072]
So, I have a problem with my Chromebook, trying to run Shotcut. I was about to make a video with it, but after I imported it to Shotcut, the video just froze, as well the software. I don't know why the f@ck it just happened. The last time I used Shotcut on my Chromebook, it works just fine, and I hadn't got any problems with it. But right now, every time I tried to do something with it (i.e. Opening a file, dragging it, etc.), it just F@#$ING FROZE ALL THE DAMN TIME! Is there any way to fix the problem, so I can use go with my video? Thanks!

Here's what I got on my terminal:
![Screenshot 2021-04-12 6 56 43 PM](https://user-images.githubusercontent.com/63752085/114472772-e69ce480-9bc0-11eb-8f6f-741b7a85fcd2.png)

**Comment by ddennedy** [comment]
Sorry, but we do not support ChromeOS. See the [FAQ](https://shotcut.org/FAQ/). While some have reported using it, none of the developers have one or can help with this. Most of the Chrome machines are too weak as well. Anger does not help, and  we welcome any patches you can provide to make it work.

**Comment by Calvin242** [comment]
> Sorry, but we do not support ChromeOS. See the [FAQ](https://shotcut.org/FAQ/). While some have reported using it, none of the developers have one or can help with this. Most of the Chrome machines are too weak as well. Anger does not help, and we welcome any patches you can provide to make it work.

Sorry for my little outburst, but all I'm saying is, I just want the Shotcut to work on my Chromebook, since it can run Linux Apps.

**Comment by ddennedy** [comment]
I see you are using the arm64 build of Flatpak, which yeah is Linux and not ChromeOS. Sorry for that oversight. Unfortunately, still, none of the developers have such a machine. Personally, I only consider the Apple M1 the only viable ARM machine to run Shotcut, which is CPU-based for all of its video decoding and processing. I suggest you try to downgrade your Shotcut's flatpack because it sounds like you might be affected by recent technology updates. Try version 20.11.28 or 20.09.27. Here is an example to do that with a flatpak:
https://github.com/flatpak/flatpak/issues/3097
