### ISSUE TITLE
X removes the wrong clip when trying to remove gaps

### ISSUE THREAD

**Issue by Cagier** [mltframework/shotcut#1081]
Version 21.03.21
When an empty spot on a track is selected and you right-click and the press remove the blank portion is correctly removed.
However, if the same track is selected and you highlight the same empty area but instead press the X key, then the non-blank clip above the selected track is erroneously removed instead.

**Comment by ddennedy** [comment]
This is by design. The context menu is attached to the blank spot similar to a clip. That spot is actually an object you can select using ctrl+space depending on the current track. When no clip is selected, Shotcut goes into a special mode that is designed for certain workflows especially when using a jog/shuttle controller that does not treat blanks as objects so thing can be targeted by playhead position.

**Comment by ddennedy** [comment]
I removed the X keyboard shortcut that appears in this context menu when opened on a blank spot.

**Comment by Cagier** [comment]
Ok, thanks for the speedy responses. I do remove blank gaps a lot. Any
chance of providing a different shortcut for that kind of remove (Ctrl Shit
X or something?)
