### ISSUE TITLE
Can’t get login to forum.

### ISSUE THREAD

**Issue by APOS80** [mltframework/shotcut#1138]
I don’t get any confirmation mail and yes I checket junk mail and tried resend.

**Comment by ddennedy** [comment]
e-mail delivery is not reliable. I have done everything I can to legitimize the e-mail server's delivery, but some servers always reject it possibly because too many of its users have flagged it as spam. The forum sends new replies and popular topics e-mails that you can opt out of, but not everyone uses that and flags it. I manually activated your account.
