### ISSUE TITLE
The program crashed after I finished editing!!!

### ISSUE THREAD

**Issue by Mizuno-Mashiro** [mltframework/shotcut#1150]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Windows 10
Shotcut 21.03.21

I've got no idea how to recover my data... But I've taken a whole day editing it using Shotcut. Do we have auto backup in Shotcut? It was really depressing. 

I was trying to save my project, however, the program crashed. I don't have a clue how I can reproduce this bug, can someone help me out?

**Comment by bmatherly** [comment]
I would be best to head over to the forum to search for advice on project recovery. Here is a good thread to start with:
https://forum.shotcut.org/t/how-to-manually-recover-an-auto-saved-project-after-a-crash/20814

**Comment by ddennedy** [comment]
> Do we have auto backup in Shotcut?

Yes. If you have never saved the project when you next start Shotcut it will detect this and offer to recover. Otherwise, you need to try to open the project file, and if there was an autosave version it offers to recover. If neither of these happen you need to restore from a backup or your work is lost.
