### ISSUE TITLE
Levels Filter, Gamma Value doesn't keep input for certain values

### ISSUE THREAD

**Issue by andrewk8** [mltframework/shotcut#1151]
SC 21.08.29 Portable x64
Windows 10 21H1

1. In a Timeline clip.
2. Add Levels filter
2. In the Gamma, type 1.15.  Press enter.
3. Observe that Gamma value changes to 1.14.

You can use up arrow to change 1.14 to 1.15.  But if won't hold 1.15 as a typed input.

The issue is reproducible with a 1.15 Gamma. It existed in 21.06.29 (and earlier?).

Impact: Low. I don't have quality metrics for output and can't see 0.01 difference in Gamma. But the UI is behaving unexpectedly.

**Comment by bmatherly** [comment]
Thanks for your report. This issue is a result of a rounding error that occurs during unit conversion. The underlying library uses units that have an inconvenient scale. So Shotcut presents the values as a range from 0.01 - 4.00 and converts to the scale of the underlying library. This conversion process results in some values that do not map directly and have to get rounded to the nearest valid value.

Even though this is a valid issue, I am going to close it because the impact is low and we are unlikely to find an easy solution.
