### ISSUE TITLE
build-shotcut.sh and lame.

### ISSUE THREAD

**Issue by firew4lker** [mltframework/shotcut#116]
In order to build lame with the build-shotcut.sh I had to download and apply the following patch for lame

https://gist.githubusercontent.com/rdp/3581e2c51916f3d8056e/raw/052a1a57b876cc6f22f1c0780e71193641b11669/lame3.patch

Maybe the script should mention it or do it automatically?

cd src/lame
wget lame3.patch
patch -p0 < lame3.patch

Build system: 32-bit ArchLinux.

**Comment by metellius** [comment]
So this is a 32 bit issue then? remember that the website states '64-bit only'. it's up to @ddennedy whether build-shotcut.sh should support it or not.

**Comment by firew4lker** [comment]
I don;t know if this problem occurs on 64-bit systems.

The website doesn;t state that he 32-bit version is dropped.

**Comment by ddennedy** [comment]
It does appear to be a 32-bit issue, but our nightly 32-bit builds have been working without this patch. I think it may depend on the OS you use to run it. I do not want to change the build script to start patching things (adds more complexity to an already very complex script). The way I handle something like this is to fork it onto GitHub, patch it, and point the build script there. However, I only am willing to do this for things affecting *our* builds. Unlike the mlt and melted build scripts, which are designed for general use by all, the shotcut build script is really intended only for my build nodes due to the complexity of supporting multiple operating systems. Therefore, I will not be forking lame to maintain this patch. As a result, I am closing this as it is not a shotcut functional defect and not something I intend to act upon (or even merge a patch to build-shotcut.sh and therefore inherit).

**Comment by ddennedy** [comment]
Yes, the web site does say 64-bit only right on the release blog post on the home page and on the download page.

**Comment by firew4lker** [comment]
We should not report problems from 32-bit versions? Is 32-bit officially dropped?

**Comment by ddennedy** [comment]
We only accept problem reports from the builds that we provide. Since we no longer provide 32-bit builds, then, no, do not report problems made on your own 32-bit build - unless you are a developer and accompany that report with a patch for review or comment.

**Comment by firew4lker** [comment]
Ok.

**Comment by ddennedy** [comment]
I might consider switching to this git repo for lame since it appears to be an actively maintained alternative: https://github.com/rbrito/lame

It does not have your exact patch, but I see something else matching "xmmintrin" in configure that might accomplish the same thing.
@firew4lker please change the script to use git as the source type and to use the above git repo and test it. If you still have a problem, you could submit your patch to the github project, and then I am willing to change build-shotcut.sh to use it.

**Comment by firew4lker** [comment]
Ok.
