### ISSUE TITLE
Exported video has white frames instead of image

### ISSUE THREAD

**Issue by cableTh0rn** [mltframework/shotcut#1206]
Hello, exported video show white frames instead of images. Only source images are affected, video clips are exported perfect. 
ffmpeg version 3.4.8
shotcut version 21.12.24
Ubuntu 18.04

This happens when image is inserted into the video track , preview ok but exported video is completely white instead of the picture. No problem with the audio. Video files are in MTS and images are in JPG format. Below is the white frame screen shot of the exported video. Export selected as youtube profile.
![Screenshot from 2021-12-27 12-59-07](https://user-images.githubusercontent.com/75907398/147460473-c519f383-3c0a-44f1-be76-b6ff4719aaf3.png)
.

When running shotcut 20.11.28 from appimage, on the same computer, this problem goes away. I suppose this started after ffmpeg update, but newer shotcut versions should run OK with ffmpeg as old shotcut versions.

Below is the screenshot , exported video have white frames , instead of featured.jpg, this happens if image is replaced with another one.

![Screenshot from 2021-12-27 13-06-36](https://user-images.githubusercontent.com/75907398/147461084-992b2e7c-0f56-4e4a-b78d-e18fb9521a95.png)

Anyone having this bug?

**Comment by bmatherly** [comment]
It works for me using this very simple test project:
![image](https://user-images.githubusercontent.com/821968/147476629-a54fe93e-a19e-4701-bb3e-df724f51321a.png)

I tested using the official portable tar:
https://github.com/mltframework/shotcut/releases/download/v21.12.24/shotcut-linux-x86_64-211224.txz
Have you tried that package?

It could be related to your FFMpeg version since we only support Shotcut with FFMpeg 4.4. But for images, Shotcut uses Qt. And you did not mention your QT version. We support Shotcut with Qt 5.15.2.

**Comment by ddennedy** [comment]
Shotcut requires the latest version of MLT. Latest MLT requires FFmpeg v4 as reported here:
https://www.mltframework.org/blog/v6.26.0_released/
