### ISSUE TITLE
Adding Text (From Filters)

### ISSUE THREAD

**Issue by H-arks** [mltframework/shotcut#1212]
The settings chosen out of the toolbar when adding a text overlay are not saving themselves and I have to repeatedly change the font size, color, or formatting choice. Any thing I should mess with in settings or is this non-fixable? 

An annoying bug... That's all.

**Comment by ddennedy** [comment]
This bug report is invalid; repeating myself from the bug template:

>  If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Are you talking about the Text: Rich video filter? If so, I am unable to reproduce the problem and do not understand how to from the very short description. Maybe the problem is that you need to select the text you want to change before trying to format it. Unlike some word processors, this editor does not let you set the format *before* the next text to be typed. You need to type first, select, and then format. Sorry, but that is the way it is. We do not actually make the editor at this level. It comes from a library we do make or change.
