### ISSUE TITLE
Translating items with numreus

### ISSUE THREAD

**Issue by zorgoz** [mltframework/shotcut#1214]
Please provide a reasonable sample on how to translate such items:

```
<message numerus="yes">
        <location filename="../src/docks/playlistdock.cpp" line="259"/>
        <source>Replace %n playlist items</source>
        <translation type="unfinished">
            <numerusform></numerusform>
            <numerusform></numerusform>
        </translation>
    </message>
```

As the source and the translation part are modeled differently, it is nowhere any straightforward hint on this. Why are there multiple `numerusform` elements anyway? Thanks.

**Comment by bmatherly** [comment]
Numerusform strings allow you to handle pluralizations for your language. You can handle single values, multiples values, and zero values.

Example from [here](https://help.phrase.com/help/qt-translation-source):

```
    <message numerus="yes">
      <source>pluralized_key</source>
      <translation>
        <numerusform>Only one pluralization found.</numerusform>
        <numerusform>Hey, you have %s pluralizations!</numerusform>
        <numerusform>You have no pluralization.</numerusform>
      </translation>
    </message>
```

Translations commonly only provide single and multiple strings. Sometimes it is useful to look at other translations for examples (even if you do not speak that langauge).

For example, the French translation provides translations for single and multiple:

https://github.com/mltframework/shotcut/blob/master/translations/shotcut_fr.ts#L5847

```
            <numerusform>Remplacer %n élément de la liste de lecture</numerusform>
            <numerusform>Remplacer %n éléments de la liste de lecture</numerusform>
```

**Comment by zorgoz** [comment]
Just to clarify: 
```
        <numerusform>For non/zero</numerusform>
        <numerusform>For singular/one</numerusform>
        <numerusform>For plural/multiple</numerusform>
```
in this specific order?

**Comment by bmatherly** [comment]
> Just to clarify ... in this specific order?

It actually depends on the language. QT has defined different "rules" for the (up to) 3 entries depending on the language family.

https://doc.qt.io/qt-5/i18n-plural-rules.html

Which family is your language in? Well, that is harder to find, but you can deduce it from the source code:

https://github.com/qt/qttools/blob/5.15.2/src/linguist/shared/numerus.cpp

So, for example, Hungarian is in the Japanese family. So the rules are:

<html>
<body>


Language | Rule 1 | Rule 2 | Rule 3
-- | -- | -- | --
Japanese | otherwise | N/A | N/A


</body>
</html>

So there should only ever be one numerusform entry for Hungarian.
