### ISSUE TITLE
Build thinks it is cross-compile

### ISSUE THREAD

**Issue by bkauler** [mltframework/shotcut#1216]
I have 21.12.24, running on EasyOS 3.2.1, reckon I have all the required deps installed.

```
# export PKG_CONFIG=/usr/bin/pkg-config
# qmake PREFIX=/usr DEFINES+=SHOTCUT_NOUPGRADE DEFINES+=NDEBUG
# make
....
Project WARNING: Cross compiling without sysroot. Disabling pkg-config.
```

...then it fails, can't find stuff. But I am NOT cross-compiling. Does anyone have a thought how I can tackle this?

I did search online, and saw a fix to export PKG_CONFIG, but that doesn't work with shotcut.

**Comment by bkauler** [comment]
Got it to compile by defining PKG_CONFIG on the same line:

```
# mkdir build
# cd build
# qmake ../shotcut.pro PKG_CONFIG=/usr/bin/pkg-config PREFIX=/usr
# make
...have to fix CuteLogger/Makefile
# make
# make install
```

Requires manual fix for CuteLogger/Makefile, reported in #1217 

The puzzle still remains, why does it think it is cross-compiling?
I have compiled other qt5-based apps without this problem.

**Comment by ddennedy** [comment]
This is a problem in your Qt environment.

**Comment by ddennedy** [comment]
Why not try one of our builds on our [Download](https://shotcut.org/download/) page? I am not responding on the other bug #1057 as your problem is unrelated to its original report. Basically, if compile it yourself, you need to debug it yourself. We spend significant effort to make our own builds and cannot help everyone with their build. If it still fails to load the timeline, look at the console output or View > Application Log for interesting messages. It is also possible that it does not work because you do not have an adequate OpenGL environment, as the QML code Timeline uses depends on OpenGL as explained in our [FAQ](https://shotcut.org/FAQ/) and the [Display Method](https://forum.shotcut.org/t/display-method/12705) document.
