### ISSUE TITLE
Crashing while working

### ISSUE THREAD

**Issue by adbookerfhsu** [mltframework/shotcut#1238]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Just started using this a few days ago. Haven't had any problems until today. The program crashes and closes out on it's own. I am laying down video and separate audio files and splicing the excess out. The videos are less than 3 minutes long in total so it should not be a computer processing or graphics problem.

Lost an entire 2 hrs on a project (yeah, my fault for now saving - lesson learned). I LOVE this program.  But  as many times as this thing has crashed in the last hr its almost as bad as the slow processing in Windows Video Editor. 
I am working on a windows 10 desktop version 10.0.19043 - 64 bit

Shotcut version 22.01.30

Just like to know if there is something I am doing wrong or is this a bug. Anyone else having the same issue?

**Comment by ddennedy** [comment]
I don't know; it doesn't happen to me. Some things to try:
- reboot
- reinstall
- reinstall using the installer check box to remove shotcut's settings from the registry
- If the problem seems to be occurring with a certain file or all files from the same source (tool or device), use Properties > Convert on them, and use the converted files.

> Lost an entire 2 hrs on a project 

There is auto-save. If you never saved the project; it offers to restore upon startup. If you did save the project at some point, it only offers to restore when you try to reopen it. You need to use File > Open if the project is not listed in Recent Projects.

**Comment by stephenlevitt** [comment]
I installed the latest Shotcut version (22.01.30) running on Windows 10 (19043.1526 - 64 bit) and also had multiple crashes. They are hard to pin down. It crashes sometimes when opening an *.mlt file which was missing some assets, sometimes when pasting a png image into the timeline but seemingly only at the end of one of the tracks, and just at random. 

I have reverted to version 21.03.21 and, for now, the crashes seem to have disappeared.

**Comment by whcrg** [comment]
For me on mac shotcut version 22.01.30 crashes with segfault often but not always when applying effect Size, position & rotate and selecting a preset slide in/out.

https://pastebin.com/624stwJy

**Comment by luzpaz** [comment]
Is this issue still reproducible ?

**Comment by ddennedy** [comment]
Too vague and expiring it now.
