### ISSUE TITLE
Can't build shotcut under Kali linux

### ISSUE THREAD

**Issue by DJE98** [mltframework/shotcut#1249]
# What happened?
I tried to run the the build-shotcut.sh script from the current master branch under my kali linux like described on the [website](https://shotcut.org/notes/linuxdev/).

# Goal
I want to start contributing to the project.

# Problem description
I started to run and get the problem, that the git repository has local changes and I have to have to disable ACTION_GET. So ran the script again with ACTION_GET = 0.
[first_run_error_log.txt](https://github.com/mltframework/shotcut/files/8495710/first_run_error_log.txt)

At the second run the script didn't install the dependencies from the current branch. So I have to install for example the dependencies eigen3 libepoxy libsdl2-dev manually for movit or the dependencies  libmp3lame-dev libtheora. for ffmpeg.
[second_run_error_log.txt](https://github.com/mltframework/shotcut/files/8495709/second_run_error_log.txt)

In my next try I ran the command like described on the readme file, but I didn't know exactly which dependencies I have to install. So I fixed the missing with search request. Unter I got a compilation error. 
[next_error_log.txt](https://github.com/mltframework/shotcut/files/8495763/next_error_log.txt)

# System description
Kali linux 2022.1
cmake version 3.22.1
libmlt++7 (= 7.4.0-1)

**Comment by ddennedy** [comment]
Build help is not provided and not a bug. The script works for me mainly to make the nightly build, which you can see here under Actions works. It does not install any package dependencies and only builds some dependencies. Shotcut only depends on the latest release of MLT and Qt 5.15 to build. Basically you need to pass the test of figuring how to build it to be qualified to contribute to the project.

**Comment by DJE98** [comment]
Thank you for your answer.
In the [kali repositories](https://pkg.kali.org/pkg/mlt) is mlt in an older version than in the  [debian repositories](https://packages.debian.org/unstable/libmlt++-dev). 
I tried to install directly from the [git repository](https://github.com/mltframework/mlt). The installation path from  mlt is /usr/local/.., but the project requires is  the files on /usr/.. I tried to set symbols, but there are also missing files. 
[install_log.txt](https://github.com/mltframework/shotcut/files/8498378/install_log.txt)
A guide for compling on different linux distros would be really nice.

**Comment by bmatherly** [comment]
>  So I have to install for example the dependencies eigen3 libepoxy libsdl2-dev 

This is normal and common if you have not already installed the dependencies. When I use the script for the first time on a machine, I usually iterate a few times:
1) Run the script
2) Install missing dependencies
3) Delete folders that give the "local changes" error
4) Repeat

It would be great if someone wants to improve the script to have an option to discard local changes for this use case.

**Comment by ddennedy** [comment]
When using the build script that builds many close dependencies, there are still some packages needed. Our [automated builds](https://github.com/mltframework/shotcut/blob/master/.github/workflows/build-linux.yml) run in a docker container based on an ubuntu image whose [Dockerfile](https://github.com/mltframework/mlt-scripts/blob/master/docker/shotcut-build/Dockerfile) shows the additional dependencies needed.

You can use MLT installed to any location. I use `-D CMAKE_INSTALL_DIR=$HOME/opt` on my system. But for that to work you need to define/extend a `PKG_CONFIG_PATH` environment variable. It is not completely necessary to have all of the dependencies that Shotcut's official builds include in order to do basic coding work, but to access certain features or debug certain bug reports more will be needed. These are the factors to consider when choosing to build MLT against mainly distro packages or to use the build script. For example, you can build without movit to simplify things as that is not even a supported feature. I do not use the build script for my Linux development. I manually maintain the same dependencies that are in the build script. Sometimes, when MLT is not moving fast and some Linux distros are on its latest release, Shotcut development is rather easy. But not always, especially for the past year. Then, factor in rather extreme fragmentation that is in Linux ecosystem, and it becomes difficult to provide and maintain instructions.
