### ISSUE TITLE
Error when changing the language. Version 22.04.22

### ISSUE THREAD

**Issue by vdvolkov1963** [mltframework/shotcut#1252]
Error when changing the language. Version 22.04.22
https://disk.yandex.ru/i/f8zl4Y8fcmUEHA

**Comment by ddennedy** [comment]
Adding information that you missed: This is some version of Windows. I did not reproduce it. You did not state which languages. I tested from English (United States) to Russia and back to English (United States). It looks like the error (I cannot read it; do not understand that language) is not important because you can simply start the app in the new language.
