### ISSUE TITLE
How do I disable vertical scroll?

### ISSUE THREAD

**Issue by CHJ85** [mltframework/shotcut#1253]
Hi there. In most DE's on Linux, the keyboard shortcut for desktop zoom is ALT + scroll wheel. Because this conflicts with vertical zoom in Shotcut, I was wondering if there's a way to disable or better yet change the key from ALT to Shift?
Btw. The fact that you cannot customize the keyboard shortcut is kind of a pain. This is a perfect example right here.
Thanks.

**Comment by ddennedy** [comment]
There is no official way to disable such as a setting visible or hidden. In Qt alt+mouse-wheel is the builtin way to horizontally scroll views such as most panels in Shotcut when the content is wider than the space given. Timeline is different because it is horizontally dominant. Some of the Shotcut code is interpreted at run time because it is QML with JavaScript. So, you can modify `$prefix/share/shotcut/qml/views/timeline/Timeline.js`/`onMouseWheel()` but not if you are using AppImage or Flatpak because these are basically sealed.

Also, I had to smile amused at the combination of "Linux" and "most" in the same sentence since the ecosystem is heavily fragmented. ;-) The default Ubuntu desktop I am using (not so uncommon) does not use that combination to zoom. Maybe you turned on something specifically to enable that. Also, I am a little surprised to just now here about this after several years of it being like this.

**Comment by CHJ85** [comment]
Thank you. And well. Alt+mouse wheel used to be the default for Gnome back when I was using it. I'm pretty sure XFCE uses alt+mouse wheel too. And I know Cinnamon does. Not KDE Plasma though. So that's why I said "most".

**Comment by ddennedy** [comment]
You are going to have to live with it by not using alt+wheel in Shotcut on your desktop since Qt has builtin alt+wheel for all scrollviews that we are not going to attempt to override. Try to change the desktop's behavior or drag the scroll bar instead.

**Comment by CHJ85** [comment]
I meant horizontal. Not vertical. But I'm sure you realized that.
