### ISSUE TITLE
Clip duration in Playlist Add Selected To Slideshow does NOT act as maximum duration

### ISSUE THREAD

**Issue by abakum** [mltframework/shotcut#1285]
How to reproduce:
1) Drag the 4 second clip to the source
![image](https://user-images.githubusercontent.com/18271863/172152483-0ea23a5e-975b-454a-8f58-033cf2a0b536.png)
2) Select a 1 second subclip from 0:0:0 to 0:0:1.
3) Add it to playlist
4) Select a 2 second subclip from 0:0:1 to 0:0:3.
5) Add it to playlist
6) Select a 1 second subclip from 0:0:3 to 0:0:4.
7) Add it to the playlist
![image](https://user-images.githubusercontent.com/18271863/172154108-c6891479-b110-47e4-955a-dc6b85e5133b.png)
8) Select 3 clips in the playlist with a duration of 1, 2, 1 seconds and Add Selected To Slideshow
9) Set Clip Duration to 10 seconds.
![image](https://user-images.githubusercontent.com/18271863/172156765-867ec8fb-4ef4-4cb9-aa73-2ec8373cf882.png)
10) On the Timeline, I got 3 clips with durations 4, 3 ,1, although I expected that there would be 3 clips with a duration of 1, 2, 1 seconds.
![image](https://user-images.githubusercontent.com/18271863/172157128-b82504b5-b018-4d5f-9c1f-50a9a75ed2d5.png)

Project:
[Clip duration acts as the maximum duration.zip](https://github.com/mltframework/shotcut/files/8844352/Clip.duration.acts.as.the.maximum.duration.zip)

**Comment by bmatherly** [comment]
Thanks for your report. I had to recreate your project because the media was missing. But I think I reproduced something similar using the released version 22.04.25. I was not able to reproduce the problem using the latest nightly git build.

Can you try to recreate the problem with one of our nightly git action builds and report back?
https://github.com/mltframework/shotcut/actions

**Comment by ddennedy** [comment]
> I had to recreate your project because the media was missing.

You can use the Missing Files dialog to easily substitute your own media. I did for `Clip duration acts as the maximum duration.mlt` and reproduced the problem.

When I used git master to recreate the project, I am starting with a clip that is longer than 10 seconds. And what I get is 3 clips on the timeline track that are each 10 seconds long. That is because the slideshow generator is not honoring the out points of the playlist items. If the source clip is 4 seconds long (see the `length` properties in the provided .mlt file), then you get result 4, 3, 1 because of the duration of the source minus the in point. The question is: Should it honor the out point? If you agree that it should then
```
--- src/widgets/slideshowgeneratorwidget.cpp
+++ src/widgets/slideshowgeneratorwidget.cpp
@@ -178,7 +178,7 @@ Mlt::Playlist *SlideshowGeneratorWidget::getSlideshow()
         Mlt::ClipInfo *c = m_clips->clip_info(i, &info);
         if (c) {
             Mlt::Producer producer(MLT.profile(), "xml-string", MLT.XML(c->producer).toUtf8().constData());
-            slideshow->append(producer, c->frame_in, c->frame_in + framesPerClip - 1);
+            slideshow->append(producer, c->frame_in, qMin(c->frame_out, c->frame_in + framesPerClip - 1));
         }
     }
 
```

**Comment by bmatherly** [comment]
> The question is: Should it honor the out point?

For a video, I think it definitely should. The user might trim a video clip to just a specific part that they want to show. And that segment might be shorter than the configured duration.

For an image, I think a user might expect the slideshow generator to always make the image the full duration since trimming doesn't really have any effect on a still image. I think this is probably the use case I had in mind when I wrote the code originally.

But maybe it is inconsistent to treat videos an images differently. Or maybe it is not easy to detect a still image (look for qimage producer?).

**Comment by ddennedy** [comment]
I agree with the difference between image and video, especially considering the default duration of an image is only a few seconds. I do not think it is OK to make this inconsistent since someone might observe what happens with video and then try to vary the duration of each photo slide by adjusting their duration only to find it does not. And making an image also honor the out point to be consistent with video will lead to greater user confusion and frustration with a mismatching expectation. Combine that with the main purpose of this is for photos. Thus, I have decided that this is a feature and not a bug and will not be changed.

**Comment by abakum** [comment]
[Slideshow Generator](https://forum.shotcut.org/t/slideshow-generator/19162).
"Use music files and set Clip duration very high to make a music bed track" it is a trick.
Instead, you may add a checkboxes to form of Slideshow Generator:
"Use duration from playlist"
"Use duration from source clip"
If the checkboxes is not selected, then will be used Clip duration from a form Slideshow Generator
For my taste, it’s convenient to create a playlist with all the videos and photos, and show successful photos longer than usual and then connect them with transitions using a Slideshow Generator, but I trust the taste of the author

**Comment by abakum** [comment]
> Can you try to recreate the problem with one of our nightly git action builds and report back? 
![image](https://user-images.githubusercontent.com/18271863/172306039-bf5c6c1a-668e-44ff-9e70-3e66e6af6646.png)
[Clip duration acts as the maximum duration2.zip](https://github.com/mltframework/shotcut/files/8850464/Clip.duration.acts.as.the.maximum.duration2.zip)
