### ISSUE TITLE
cutting an "Image sequence" video doesn't work as expected

### ISSUE THREAD

**Issue by owai1980** [mltframework/shotcut#1302]
Hello.

I use a lot of image sequences to make timelapse. 

when i want to cut (Split) an image sequence in 2 parts, then I change the FPS of the second part (repeat image count), there is a bug: the sequence is recomputed from the start of the original (full) sequence. So the first frame of the second part is changed. This should not happen.
I hope you understand what i mean.

I use this "trick" to because the "speed change" options are (sadly - not yet ? ) not compatible with image sequences.

thank you

johan

**Comment by bmatherly** [comment]
Missing features is not a bug. And recalculating the "in" point from the start of the file is expected behavior (even if it is not your preferred behavior). Even if we added speed controls to image sequences, your experience would be poor due to lagging.

I recommend to open your image sequence and then immediately export it in an edit friendly format like ProRes or DNxHD.

**Comment by owai1980** [comment]
Thank you for your answer.

I agree that a missing feature is not a bug... But  I still think that
"recalculating the "in" point from the start of the file " is a very
strange behaviour.

It is surprising and misleading. When a sequence is cut, users expect that
the new sequence is now independent.

 I understand that i have no right to decide how it should work, but i
wonder what is the reason.

Yeah, maybe i will try to build a video sequence before using shortcut...
But... It is sad 😁 Shotcut is "almost perfect"!

Thank you for your answer

Johan


Le dim. 17 juil. 2022 à 15:22, Brian Matherly ***@***.***> a
écrit :

**Comment by bmatherly** [comment]
>  I understand that i have no right to decide how it should work, but i
wonder what is the reason.

It is not because nobody wants it to work the way you suggest. It is because nobody has taken the time to make it work differently for your use case.

We don't track suggestions on this bug tracker. You might find some good discussion with other users on [the forum](https://forum.shotcut.org/).
