### ISSUE TITLE
broken editing with nested projects of different aspect ratios

### ISSUE THREAD

**Issue by weckr** [mltframework/shotcut#1303]
I'm trying to use shotcut in mobile game video ads pipeline, and found some great benefits to it being based on commandline tool, I use this to batch export multiple version of the same project etc.

I usually have few versions of the same video with different aspect ratios for different storefronts, social media, etc. For this in theory the ability to use shotcut project in a timeline of another shotcut project is absolutely perfect. Kdenlive does this too, but preview performance of the nested projects is abysmal and it gets very unstable. Shotcut nested performance is usable, but unfortunately it doesn't seem to be able to handle nested projects of different aspect ratios correctly eg. I would have the original "source" clip in large 16x9 project with some edits, and I want to use it in the timeline of "export" 9x16 project. I do it this way because I would have several of these "export" projects of different ratios with differently placed titles etc. but I want some pieces of edited video to be shared by all of them to avoid work duplication. But it just gets broken when you import different aspect ratio .mlt, the imported clip has incorrect aspect ratio, and i think it even breaks the aspect ratio of the project you are editing it in.

Anyways I've been just exporting the "source" videos as a workaround, but doing it properly with nesting would be amazing, and since the feature is there I think this is definitely a bug.

editing 16x9 .mlt with 1x1 .mlt imported into the timeline - the whole project preview goes 1x1, the imported 1x1 is stretched to 9x16, etc...
![image](https://user-images.githubusercontent.com/34169362/180436083-208fc2c3-f623-4f72-9ab3-ba99a28b89e2.png)

Shotcut version 22.06.23, windows 11, radeon 6600, ryzen 3600

**Comment by bmatherly** [comment]
Shotcut has not been designed to handle MLT as clip that does not have a matching video mode (profile) as the project that contains it. If someone were to add that feature, I think many people would like it. But nobody has volunteered their time to do it.

> Anyways I've been just exporting the "source" videos as a workaround

That would be my suggested workflow for what you are trying to accomplish. I understand and appreciate that costs extra render time and storage space.

I have to register this as a "feature request" since Shotcut has not been implemented to support this. And we only track defects on this bug tracker.

You are welcome to post your suggestion on[ the forum ](https://forum.shotcut.org/)and look for other workflow ideas from other users.
