### ISSUE TITLE
Audio fades created on video-only clips + mismatch of audio/video fade

### ISSUE THREAD

**Issue by Lex-DRL** [mltframework/shotcut#1322]
When fade is created with a circular handle that appears on a clip corner, both video and audio fades are added. I assume it's a supposed behavior in general case, but it creates redundant audio fade even for video-only clips, like text or color bars.

This leads to confusion: if you then set fade duration in filters panel (a common thing to do if you need a precise duration), the actual fade might mismatch with the one shown in timeline.

Possible solutions:
- Don't create audio transition on such clips at all.
- An option to link audio/video fade filters together (probably, should be on by default).
- ... or use a single filter which fades **both** audio and video at once.
- _[in addition to any of the above]_ Display audio/video fades on clips separately. E.g.: audio fade darkens the clip corner with orange, video fade darkens with blue (portal-like colors are suggested for color blindness reasons). So when they match, their tint is combined to neutral darkening grey and when they don't - a chromatic-aberration-like edge is clearly visible.

Shotcut **v22.06.23** portable, Windows 10 21H2 19044.1889

**Comment by bmatherly** [comment]
_ProTip: It is good to have only one report per issue. While I can appreciate that these two reports are strongly related by the same part of the UI, it is still helpful to keep separate conversations in separate issues._

**RE: Audio fades created on video-only clips**

I think a prerequisite for this suggestion would be that we need some way to detect and indicate to the user which clips are silent. And then, we would need to detect the change of that silence. For example, if someone adds a mute filter to a clip, then the Fade Audio filter should not appear. Similarly, what if we add a filter someday that would add sound to an otherwise silent clip - we would need to add the fade audio filter back on.

**RE: mismatch of audio/video fade**

Someone else will call the current behavior a feature :)

"An option to link audio/video fade filters together (probably, should be on by default)."
The Shotcut architecture is purposefully designed so that each filter is independent of the others. This is to avoid complicated interactions between elements that are not on the screen at the same time. So I think this suggestion would be a last resort and we would prefer to look for an alternative idea.

"a single filter which fades both audio and video at once."
This is a feature request that I have considered in the past, but I have not made it a priority.

_P.S. I would classify these two topics as optimizations or minor feature requests since the program is working as designed and these are suggestions to change the design. Most of the Shotcut power users/influencers do not monitor this bug tracker. You might find some sympathizers on the forum._
