### ISSUE TITLE
Failed to compile source code

### ISSUE THREAD

**Issue by leijiuhu** [mltframework/shotcut#1363]
0. Download shotcut source code
https://github.com/mltframework/shotcut/archive/refs/tags/v22.10.22.zip

1. Install qt5.15.2
https://blog.csdn.net/Qi_1337/article/details/121249717

2. Install msys2 (to download dependent libraries)
https://www.msys2.org/
Set the msys2 environment variable Path: C: msys64 usr bin; C:\msys64\mingw64\bin;

3. Download Configuration Auto Dependent Library Manager
1)、go to http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/
2)、download the file pkg-config_ 0.26-1_ win32.zip
3)、extract the file bin/pkg-config. exe to C:\MinGW\bin
4)、download the file gettext-runtime_ 0.18.1.1-2_ win32.zip
5)、extract the file bin/intl. dll to C:\MinGW\bin
6)、go to http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28
7)、download the file glib_ 2.28.8-1_ win32.zip
Add C:\MinGW\bin to the system environment variable Path.

4. Download dependent libraries
Install fftw3
1)、Open MSYS2 MINGW64 in msys2 installed previously
2)、enter pacman - S mingw-w64-x86_ 64-fftw
![image](https://user-images.githubusercontent.com/97873285/197735148-caa73d9b-347e-419d-a9a6-e90f71fe22d8.png)
3)、enter y. Installation succeeded

Install mlt (similar to above)
1)、Open MSYS2 MINGW64 in msys2 installed previously
2)、enter pacman - S mingw-w64-x86_ 64-mlt
3)、enter y. Installation succeeded.

5. Set system environment variables

> Qt5_DIR  

                            D:\ljh\Qt5.15.2\5.15.2\msvc2019_ 64\lib\cmake\Qt5

> Qt5LinguistTools_DIR

                          D:\ljh\Qt5.15.2\5.15.2\msvc2019_64\lib\cmake\Qt5LinguistTools

> PKG_ CONFIG_ PATH 

          C:\msys64\mingw64\lib\pkgconfig

6. Cmake configuration
1)、Decompress the source code, enter the source code directory, and create a new folder called build to store the compiled files
2)、Enter the build directory and enter cmd in the upper path bar
3)、Enter the following command. The path only refers to
cmake -DCMAKE_ INSTALL_ PREFIX=D:\ljh\QtWindowProject\shotcut\src\shotcut-22.10.22\build D:\ljh\QtWindowProject\shotcut\src\shotcut-22.10.22
![image](https://user-images.githubusercontent.com/97873285/197735269-a6c19f46-b03c-4cbd-8396-73dba2564cce.png)

7. Compile
cmake --build .
![image](https://user-images.githubusercontent.com/97873285/197735887-bb15ab76-3ccd-4965-a527-fda263c15acf.png)
As shown in the figure above, I got a lot of errors. Please tell me where I have problems. Can you help me

**Comment by bmatherly** [comment]
All your errors are referencing "shotcut.vcxproj". Are you trying to use visual studio? No one here has tried to use visual studio, so I do not think we will be able to help.

Did you know that we have a build script for msys environment? Maybe there are some good clues for you to follow here:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut-msys2.sh

**Comment by leijiuhu** [comment]
I tried to run the script build-shotcut-msys2.sh directly, but it only helped me download the dependent files. As shown in the following picture, it does not tell me how to compile shotcut. What should I do? Can you help me.
![image](https://user-images.githubusercontent.com/97873285/198497162-49b10635-c877-4a4d-9534-e2d075c38041.png)

**Comment by leijiuhu** [comment]
Can you tell me how to do it? I don't really understand how to run this script through githb. Can you give me a reference link?

**Comment by bmatherly** [comment]
You do not need to run it from github. You can run it from your command prompt. Inspect the github workflow file and treat each line as a command that you should run on the command line since that is what GitHub does when it runs the script.

The script needs a configuration file named build-shotcut.conf to give it parameters to run. The workflow file shows you all the dependencies that are installed and how the configuration file is constructed.

**Comment by leijiuhu** [comment]
Can't it be true? You mean that I need to manually run every line of the script through the command line. Is there a simpler method? Just like running build-shotcut-msys2.sh.Or do I have to write a script myself?

**Comment by ddennedy** [comment]
You can use the SDK as you started in #1360 but you need to copy the FFTW files (libraries, C headers, .pc for pkg-config) into the Shotcut SDK folders since it is not included (FFTW is a new dependency that this SDK does not yet include because I am lazy). There might be a little bit more to it like editing the .pc file too, but I am not sure because I am traveling and do not have access to my Windows machines. WE DO NOT PROVIDE SUPPORT FOR BUILDING, AND THE SDK IS NOT A SUPPORTED PRODUCT. Your failure to build successfully is not a bug. Please do not open another issue about this, or I will block you in GitHub.

**Comment by bmatherly** [comment]
> Consider disabling ACTION_GET in your build config if you want to compile with these changes

Did you  try that?

**Comment by leijiuhu** [comment]
Thank you for your help. I was too careless. Thank you very much for your patient help
