### ISSUE TITLE
Zoom Timeline to Fit only scales half of 3hr video, Slider all the way left, Max 1.5hrs?

### ISSUE THREAD

**Issue by cruudesign** [mltframework/shotcut#1365]
I loaded a 3hr video downloaded from twitch as MP4, tried to scale the whole video to be visible in Timeline, and it only shows 1.5hrs in Timeline.  I can scroll to see the rest.  Everything else is acting as normal thus far in this file.  Moving the slider over about 1/8th or 12.5% of the width takes me to appx 12:30 in video length visible in the Timeline window, whether docked or undocked and at full screen width but not maximized; maximized only slightly changes the numbers displayed in the Timeline for length, but overall is about half the video length.

M1 MBP 16gb
Monterey 12.6.1

**Comment by ddennedy** [comment]
There is a minimum zoom by design. It is not a bug; you are requesting a change, which I decline for good reasons: there should be a slider, a slider has a minimum, if the zoom can be made less than slider minimum it will be reported as a different kind of bug, zoom-to-fit depends on the width of your timeline panel, trying to fit an extremely long video into a small sized like below makes the slider unusable.
![image](https://github.com/user-attachments/assets/3b8bd688-bfb1-426d-b9e6-410d4ca104e5)
On a very wide monitor with timeline using max width, I can fit over 3 hours in the minimum zoom level, which is good enough.
