### ISSUE TITLE
Keyframes are relative to the selected clip section start

### ISSUE THREAD

**Issue by lukash** [mltframework/shotcut#1375]
When adding keyframes (in my case for the Time Remap filter, but I assume it's universal), the time mark of the keyframe is relative to the start of the current section of the clip that's being used. If I later move the start of the clip section being used, the keyframes get shifted and "messed up".

At least in my use case, I don't see a reason why one would want the keyframes to move with the current section. They are tied to the video content and therefore should be absolute (tied to the start of the source clip).

FWIW once one learns how this works, for the Time Remap in particular, this can be somewhat workarounded by having the selection start the beginning and then use the time mapping to select the proper range. That way at least the keyframes don't get "messed up", though then it can be quite tedious to adjust the beginning of the used clip section.

Os: NixOS, version: 22.10.25

**Comment by bmatherly** [comment]
This is a fair comment. There has been similar conversation on the forum about it. I think that eventually we will implement an option to "ripple keyframes".

Here is an example of one such discussion:
https://forum.shotcut.org/t/experiments-with-the-time-remap-filter/25514/31

I'm going to close this issue because we only use this issue tracker to track bugs and this is more of suggestion. I don't want to discourage the conversation - it's just that there is no audience here. I would encourage you to start a topic of discussion on the forum. I think you will find other people interested in your comment.
