### ISSUE TITLE
Crash when deleting video track by shortcut

### ISSUE THREAD

**Issue by pitagoriusz** [mltframework/shotcut#1385]
If on the videotrack is more then 1 part and I use Ctrl+Alt+U program is getting crashed. 
If in the same situation I use RMB and chose from menu - it's ok.

**Comment by ddennedy** [comment]
I did not reproduce this on Linux (Pop!_OS 22.04) on either Shotcut 22.11.25 or the 22.12 beta. I did not reproduce it on Windows either with version 22.11.25. In order to make this a valid bug report you must provide all details including OS version, Shotcut version, and the steps using the names of the UI elements in English, starting with an empty project.

**Comment by pitagoriusz** [comment]
OS - Windows 10 Pro 2022H2 19045.2311
Shotcut - 22.12.04 beta, but the same was on previous stable version.

Steps:
open new project
add file to playlist
select part of the file (I and O)
add to timeline (A)
select another port of the file (I and O)
add to timeline (A)
change to source view (P) - this is key point - if missed deleting track is working properly
change to Project view (P)
try to delete track (Ctrl+Alt+U)

Every time I do this way SC crashed.

Hope it's more helpfull.

P.

**Comment by ddennedy** [comment]
Thanks for the details. Fixed for the 22.12 release due by Dec. 22
