### ISSUE TITLE
Add Build for Windows on ARM

### ISSUE THREAD

**Issue by fzhwenzhou** [mltframework/shotcut#1390]
It would be nice if shotcut can run natively on Windows on ARM just as it can run on Mac OS X on Apple Silicon. Because MSYS2 added the "clangarm64" branch recently, it might be easy to build now.     

If there is any problem on compiling or testing, I would be glad to offer my hand as I just bought a Snapdragon 8cx Gen 3 powered laptop.

Thank you for your time and effort!

**Comment by ddennedy** [comment]
Thanks for your interest, but we only accept hard defect bug reports in Issues and feature requests in Pull Requests (along with a decent attempt at the changes required). Making a Windows ARM64 build is not so easy at this time because GitHub Actions does not have runners capable of building for that architecture outside of cross-compiling which is difficult and time consuming to get working. It is not enough that msys2 supports it, we still build several dependencies ourselves. Plus I will not publish a build of a release that I or another developer on the team can run and test. All this means it will have to wait until one of has a machine for both build and test. Based on what I have read and watched, I am still not confident the Snapdragon 8cx is suitable for a video editor like Shotcut that is heavily CPU-based rather than GPU.

If you have the technical ability to give it a try!  You do not necessarily need to build it exactly the way we do. Shotcut's direct dependencies are:
- https://packages.msys2.org/package/mingw-w64-x86_64-mlt
- https://packages.msys2.org/base/mingw-w64-qt5-winextras
- https://packages.msys2.org/base/mingw-w64-fftw

See also https://github.com/mltframework/shotcut/blob/master/.github/workflows/build-windows.yml

**Comment by thiru31** [comment]
Hey @fzhwenzhou , I'm **curious if you've made any progress** compiling and building **Shotcut on clangARM64**. Have you experimented with any specific steps to achieve this? Particularly, I'm interested in how you **dealt with dependencies that aren't supported on ARM**, such as **_libspatialaudio and glaxnimate_**.

Looking forward to hearing about your experience! 

Thanks in advance for sharing.
