### ISSUE TITLE
Frames / second = video: 240fps -> limit: 80fps -> need: 30fps

### ISSUE THREAD

**Issue by MSGCZ** [mltframework/shotcut#1430]
OS: `Windows 10 x64 22H2`
Shotcut: `22.12.21` (but the bug is in older versions)

If I want export video from (for example: GoPro HERO 11) which has 240 frames/sec (slow motion) MP4 and I need only 30 frames/sec OR maybe 60 frames/sec. Shotcut won't let me drop frames/sec below 80. Why?

![80fps](https://user-images.githubusercontent.com/80202249/233825155-bf380862-24d1-4428-a2a8-cd283563349d.gif)

**Comment by ddennedy** [comment]
You should change video mode instead of Export settings. This is a limitation due to how the retiming works here, in export, instead of Video Mode setting. Also you cannot properly take advantage of slow motion (smooth) by changing Properties  > Speed unless you have changed Video Mode to something lower than the source’s 240 fps.
