### ISSUE TITLE
Detection of hardware encoding (h264_nvenc) broken after 23.09.29 version

### ISSUE THREAD

**Issue by vgambitx** [mltframework/shotcut#1496]
Detection and functionality of hardware encoding is broken (h264_nvenc) after 23.09.29 version: in versions 23.11.29 and 231215 it's not working (even if select it manually). My hardware is  Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz / TUF Z390-PRO GAMING / 32 Gb RAM / Gigabyte GeForce GT 710 Silent 2048MB. OS: Windows 11 Pro x64 , Nvidia driver 474.64.
If install version 23.09.29 all is working correctly.

**Comment by ddennedy** [comment]
To add support for AV1 the [NVIDIA SDK was updated](https://github.com/FFmpeg/nv-codec-headers/tree/sdk/12.0) such that minimum driver version increased:

> Minimum required driver versions:
> Linux: 520.56.06 or newer
> Windows: 522.25 or newer

Your GPU might be too old to update the driver. If so that is too bad, but if you want to continue to use old hardware then you must continue to use an older version of the app.
