### ISSUE TITLE
21:9 project viewer not working properly

### ISSUE THREAD

**Issue by Brisou394** [mltframework/shotcut#1515]
Hi,
I don't understand why the project view doesn't match my video footage resolution ?
Working with 21:9 (somewhat ultrawide aspect ratio) 3440x1440 p60

![Capture d'écran 2024-02-10 115802](https://github.com/mltframework/shotcut/assets/29820982/03269f6c-7fca-43ce-ba20-0562623dcde9)
Seems like first profile arn't saved; I don't thing the too long name is the problem "3440x1440p59,4 (21:9)"
![Capture d'écran 2024-02-10 121443](https://github.com/mltframework/shotcut/assets/29820982/897f6308-9ded-4e17-a362-b59f96dac3ed)

I then created another same profile (name is different) that I switched to and it **almost fixed** the viewer
![Capture d'écran 2024-02-10 115737](https://github.com/mltframework/shotcut/assets/29820982/be40767a-2def-4962-b003-83f55fc3d997)
![Capture d'écran 2024-02-10 120704](https://github.com/mltframework/shotcut/assets/29820982/186f21d9-51fd-4efe-bc23-8d958979d0c2)

Setting it as a 21:9 and not a 3440x1440 fixed it (top to bottom)
![Capture d'écran 2024-02-10 120623](https://github.com/mltframework/shotcut/assets/29820982/1bb2275f-ed9c-4ded-8cc3-b3c98a02fabe)

I had too check if it was a footage problem. Other programs picked it no problem
![Capture d'écran 2024-02-10 115417](https://github.com/mltframework/shotcut/assets/29820982/a410952a-c6e6-493a-a25b-3134fb2c46af)

Thanks
v24.01_Win11

**Comment by Brisou394** [comment]
> Shotcut is not adding those black bars - they are already there.

Look, I am not talking about the black bars on the sides...
- profiles are not saved properly and sometimes they messes with default resolution or something as shown in first image
- profile names are not showing after [ : ]
- Shotcut don't treat video signal 21:9 as same as 3440x1440 (video is shrunken and it adds black bars on top and bottom)

**Comment by ddennedy** [comment]
> I don't understand why the project view doesn't match my video footage resolution ?

Because you did not use Automatic Video Mode and assumed that your content is 21:9 when it is not.

> Working with 21:9 

Your fourth screenshot shows that your source video aspect ratio is 3440:1440.  3440/1440 does not equal to 21/9.  The reduced aspect ratio is 43:18. It's funny that in those numerous screenshots not once did you show the Custom Video Mode dialog (or Timeline > Output > Properties) to actually show us what you did. 

I tested both 3440x1440 21:9 and 3440x1440 3440:1440, and it works fine.

![image](https://github.com/mltframework/shotcut/assets/1146683/85467699-5fa5-473d-875d-b0b564290cd1)

**Comment by bmatherly** [comment]
> Shotcut don't treat video signal 21:9 as same as 3440x1440 (video is shrunken and it adds black bars on top and bottom)

21 / 9 = 2.33333
3440 / 1440 = 2.38888

They are not treated the same because they are not the same ratio

> profiles are not saved properly and sometimes they messes with default resolution or something as shown in first image
> profile names are not showing after [ : ]

These are the same problem because the profile is saved in a file with the same name as the profile. And [:] is not allowed in a windows file name. I will make a change for the next release to forbid un-allowed characters from the profile name.

**Comment by bmatherly** [comment]
> I will make a change for the next release to forbid un-allowed characters from the profile name.

Done: https://github.com/mltframework/shotcut/commit/e420155fc8618cebfe8636bc775a5e94dffe9854

**Comment by Brisou394** [comment]
Indeed once more, Thank you guys !

I didn't knew it would do such a big difference. I looked for it but it was hard to find since it's not Settings > Video Mode > Timeline Properties (there might be some reason for not beeing this way)
![Capture d'écran 2024-02-10 200916](https://github.com/mltframework/shotcut/assets/29820982/9cc307b5-5954-453a-ab32-bf3343abe4dc)
Shouldn't there be a suggested ratio or format based on the resolution. I mean, I knew about 43:18 I would of selected it if it was suggested to me after putting my resolution..? (21:9 was easier to remember)

**Comment by Brisou394** [comment]
> Because you did not use Automatic Video Mode and assumed that your content is 21:9 when it is not.

I did try it but after I closed my projet, automatic video mode does nothing if you already closed your work once..
