### ISSUE TITLE
Shotcut appends the wrong file to the timeline

### ISSUE THREAD

**Issue by pawjast** [mltframework/shotcut#1531]
When I try to append a file from a `playlist` to a `timeline`:  
* Shotcut appends the file that is loaded in the playlist preview (❌)
* It should append the video that is selected in the playlist (✅)
 
See the evidence below.

https://github.com/mltframework/shotcut/assets/8880777/237a0027-a25d-4a87-b6ef-e0dd72c45206

I'm on Windows 10.

Shotcut version 24.02.29.

**Comment by ddennedy** [comment]
You are wrong. It is not supposed to do what you want. It appends from Source by design.

**Comment by pawjast** [comment]
That wouldn't be my intuition to design it this way but I understand.

In this respect, would you consider implementing an option or a preference to tick on/off so a single click on a clip in the playlist (effectively selecting it) loads it to the Source?

Currently you need a double click to load a clip to a Source.

That's a lot of clicking if you want to check every clip in the Source first before adding it to a timeline.

**Comment by ddennedy** [comment]
- It is the design of most preceding NLEs.
- **Source** is the "source" of editing actions.
- The workflow you describe is actually preferred by more advanced editors (users) because they will trim the shot in the source player before adding it to the timeline instead of trimming on the timeline.
- **Playlist** has a menu button with **Add Selected to Timeline**  in it. (You can add a custom keyboard shortcut for this in **Help > Actions and Shortcuts**.)
- You can drag-n-drop from the **Playlist** to the **Timeline** (including multiple).
- You can drag-n-drop from a file manager directly to the timeline.

**Comment by pawjast** [comment]
> * **Playlist** has a menu button with **Add Selected to Timeline**  in it. (You can add a custom keyboard shortcut for this in **Help > Actions and Shortcuts**.)

I've found it now. This + custom shortcut will do.

Thanks.
