### ISSUE TITLE
Input not Loaded in Compiled Shortcut Application

### ISSUE THREAD

**Issue by thiru31** [mltframework/shotcut#1534]
**Description:**
I have encountered an issue while compiling and building the Shortcut application on Windows. Despite successful compilation and build of the `shortcut.exe` file, the input is not loaded inside the Shortcut application. Upon reviewing the application logs, I noticed that the logs from the application I built and the logs from the portable version of the Shortcut application match exactly. However, the logs from my built application contain a few extra lines compared to the portable version.

```
[Info   ] <Util::isMemoryLow> available RAM =  4152780 KB
[Info   ] <Util::isMemoryLow> available RAM =  4041368 KB
[Debug  ] <MainWindow::closeEvent> begin
[Debug  ] <MainWindow::closeEvent> end
```

**Expected Behavior:**
The compiled Shortcut application should load the input as expected.

**Actual Behavior:**
<img width="959" alt="actual behaviour" src="https://github.com/mltframework/shotcut/assets/81082960/93588f2f-0269-4c1c-8023-a1a179cfbf0e">

**Environment:**
- **OS:** Windows 11 Pro 22H2
- **Compiler/Build Method Used:** Mingw [msys2]
- **Shortcut Version:** v24.04
- **Additional Libraries/Dependencies Used:**
  - MLT: multimedia authoring framework
  - Qt 6 (6.4 minimum): application and UI framework
  - FFTW
  - FFmpeg: multimedia format and codec libraries
  - Frei0r: video plugins
  - SDL: cross-platform audio playback
  (All installed using pacman)

**Logs of Application:**

[compiled version.txt](https://github.com/mltframework/shotcut/files/15210639/compiled.version.txt)
[working-portable version.txt](https://github.com/mltframework/shotcut/files/15210640/working-portable.version.txt)

Could you **please provide comprehensive instructions** on how to:

- Set up the development environment on Windows.
- Install the required dependencies if there is any specific suggested method.
- Configure the build process to ensure compatibility with Windows.

Having **clear documentation will greatly help** me and other **Windows users to contribute to the project** and **utilize its features** effectively.

Thanks in advance for your assistance!

**Comment by ddennedy** [comment]
This is not a bug, and the template states this area is only for bugs.
We provide a [SDK](https://shotcut.org/notes/windowsdev/) with some instructions.
Also, our GitHub Actions [workflow](https://github.com/mltframework/shotcut/blob/master/.github/workflows/build-windows.yml) provides precise step-by-step directions. Of course, that also involves a lengthy and complicate build script. Otherwise, it should be fairly easy as Shotcut only directly depends on Qt, MLT, and fftw. Most likely there is a problem with your MLT or FFmpeg. Your log makes it very clear:
```
[Warning] <MLT> mlt_repository_init: failed to dlopen C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt/libmltfrei0r.dll  ("C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt\libmltfrei0r.dll": The specified procedure could not be found.)
[Warning] <MLT> mlt_repository_init: failed to dlopen C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt/libmltopencv.dll  ("C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt\libmltopencv.dll": The specified module could not be found.)
[Warning] <MLT> mlt_repository_init: failed to dlopen C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt/libmltplus.dll  ("C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt\libmltplus.dll": The specified procedure could not be found.)
[Warning] <MLT> mlt_repository_init: failed to dlopen C:\msys64\home\mcw\shotcut\src\shotcut\build\lib\mlt/libmlt
```

I think the problem is that you are applying a *nix-like approach to your build of a Windows relocatable application. Our Windows build needs to target a classical Windows-style relocatable app. Relocatable means dependencies are resolved relative to the executable, and in Windows apps it is preferable to have DLLs in the same dir as the .exe. Our build script has to "deploy" the application. For Windows development, even I use the SDK! I am the primary user of the SDK. In the SDK instructions you can see that it does a "make install" or "ninja install" step to copy the exe and QML files to the staged directory. Then, you run the installed `shotcut.exe`. But I can see in your log that you are trying to run the uninstalled shotcut.exe:
`[Info   ] <qMain> install dir = "C:/msys64/home/username/shotcut/src/shotcut/build/src" `

Shotcut is not a simple project. It is not a standalone exe. Things need to be in expected locations for things to work in a non-simple project like this.

**Comment by ddennedy** [comment]
If you want documentation for a different approach than what we offer, then you need to figure them out and document it. It is not our responsibility to make build docs for you preferred method. What I have provided is what I use.

**Comment by thiru31** [comment]
I followed the SDK method outlined in [this guide](https://shotcut.org/notes/windowsdev/) for building Shotcut. However, during the build process, everything was successful except for the generation of the shotcut.exe file. The build process stopped with the error message: ninja: build stopped: subcommand failed.

```
`FAILED: src/shotcut.exe 
cmd.exe /C "cd . && C:\Qt\Tools\mingw1120_64\bin\g++.exe -DQT_QML_DEBUG -g -mwindows @CMakeFiles\shotcut.rsp -o src\shotcut.exe -Wl,--out-implib,src\libshotcut.dll.a -Wl,--major-image-version,0,--minor-image-version,0  && cd ."
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/CMakeFiles/shotcut.dir/spatialmedia/box.cpp.obj: in function `Box::load(std::basic_fstream<char, std::char_traits<char> >&, unsigned int, unsigned int)':
C:/Projects/Shotcut/src/shotcut/src/spatialmedia/box.cpp:191: undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/CMakeFiles/shotcut.dir/spatialmedia/box.cpp.obj: in function `Box::save(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, int)':
C:/Projects/Shotcut/src/shotcut/src/spatialmedia/box.cpp:254: undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/CMakeFiles/shotcut.dir/spatialmedia/box.cpp.obj: in function `Box::index_copy(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, Box*, bool, int)':
C:/Projects/Shotcut/src/shotcut/src/spatialmedia/box.cpp:309: undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/CMakeFiles/shotcut.dir/spatialmedia/container.cpp.obj: in function `Container::load(std::basic_fstream<char, std::char_traits<char> >&, unsigned int, unsigned int)':
C:/Projects/Shotcut/src/shotcut/src/spatialmedia/container.cpp:45: undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Projects/Shotcut/src/shotcut/src/spatialmedia/container.cpp:95: undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/CMakeFiles/shotcut.dir/spatialmedia/container.cpp.obj:C:/Projects/Shotcut/src/shotcut/src/spatialmedia/container.cpp:98: more undefined references to `std::istream::seekg(std::fpos<_Mbstatet>)' follow
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
17:25:52: The process "C:\Qt\Tools\CMake_64\bin\cmake.exe" exited with code 1.
Error while building/deploying project shotcut (kit: Desktop Qt 6.7.0 MinGW 64-bit)
When executing step "Build"`
```

I would appreciate any guidance or assistance in troubleshooting this issue and successfully generating the shotcut.exe file.

**Comment by ddennedy** [comment]
I configured Qt Creator to use the gcc in msys2 since that is what is used for building the SDK

![image](https://github.com/mltframework/shotcut/assets/1146683/58b3e541-8552-4fba-bf26-0b476f57975f)

If you change the compiler in the Kit the project is already configured, you should clean or rebuild.

Another thing I did not mentioned in the SDK page is to add `C:\msys64\mingw64\bin` to the `Path` **Build Environment** variable in the project configuration. I forget exactly what this was for, but I suspect it is to use the msys2 `pkg-config` utility instead of another one:

![image](https://github.com/mltframework/shotcut/assets/1146683/7e58d321-d6ea-445b-823f-42efaaced287)

(The other Path added is for a specific version of the `astyle` utility we use for code formatting with the `astyle` ninja target--not needed for building but for commits.)

Your error seems to occur because libstdc++ is not included when linking since "undefined reference" is an under-linking error (missing lib), and `std::` is libstdc++ for g++. However, when I look in my CMake-generated `CMakeFiles\shotcut.rsp` file in my build directory, I do not see an explicit c++ library.
...`-ld3d11  -ld3dcompiler  -lexchndl  C:/Projects/Shotcut/lib/libmlt++-7.dll.a  C:/Projects/Shotcut/lib/libmlt-7.dll.a  C:/Projects/Shotcut/lib/libfftw3.dll.a  C:/Qt/6.4.3/mingw_64/lib/libQt6OpenGLWidgets.a  C:/Qt/6.4.3/mingw_64/lib/libQt6Widgets.a  C:/Qt/6.4.3/mingw_64/lib/libQt6Quick.a  C:/Qt/6.4.3/mingw_64/lib/libQt6OpenGL.a  C:/Qt/6.4.3/mingw_64/lib/libQt6Gui.a  -ld3d11  -ldxgi  -ldxguid  -luser32  C:/Qt/6.4.3/mingw_64/lib/libQt6QmlModels.a  C:/Qt/6.4.3/mingw_64/lib/libQt6Qml.a  C:/Qt/6.4.3/mingw_64/lib/libQt6Network.a  -lws2_32  C:/Qt/6.4.3/mingw_64/lib/libQt6Core.a  -lmpr  -luserenv  -lmingw32  C:/Qt/6.4.3/mingw_64/lib/libQt6EntryPoint.a  -lshell32  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`

**Comment by ddennedy** [comment]
I created a project configuration similar to yours (Qt Creator MinGW 11.2 C++ compiler) plus my SDK directions, and it compiled and linked without a problem. I do not know exactly the cause of your problem.

**Comment by thiru31** [comment]
Following your instructions proceeded **[configured Qt Creator to use msys2 ]** and landed up in successful compiling and building. 

but **unable to run the shotcut.exe**
Tried **moving the dll files also to the same directory** as of shotcut.exe but still the same Error

![image](https://github.com/mltframework/shotcut/assets/81082960/fcea0cb6-f37d-4577-9d7b-058301c7a690)

**Comment by thiru31** [comment]
Thanks for your guidance. Now I built shortcut successfully using the workflow scripts, and will try with qt creator too.

I have a suggestion like if its possible to get a script to just for the deploy function alone, to move the dlls to appropriate places, so we can build manually and use scripts just to deploy dlls alone.

Thanks
