### ISSUE TITLE
VMAF Build Fail During Shotcut Build on ARM

### ISSUE THREAD

**Issue by thiru31** [mltframework/shotcut#1551]
**Description:**
While compiling Shotcut on an ARM architecture, I encountered an issue where the unit tests for VMAF, specifically `test_predict` and `test_feature_extractor`, fail during the build process. This issue is obstructing the successful compilation of Shotcut on ARM.

**Behavior:**
The build process fails due to the Build error in  `test_predict` and `test_feature_extractor` unit tests in VMAF.

**Possible Solutions:**
1. Modify the Meson options file in the VMAF repository() to turn off the build tests by setting the appropriate option to false.

> path:[vmaf](https://github.com/Netflix/vmaf/tree/master)/libvmaf/meson_options.txt

`option('enable_tests',
    type: 'boolean',
    value: true,
    description: 'Build libvmaf tests')`

2. Remove or exclude the `test_predict` and `test_feature_extractor` unit tests from the build process.
[vmaf.patch](https://github.com/user-attachments/files/16038786/vmaf.patch)

**Additional Context:**
This issue is specific to the ARM architecture and does not appear when compiling on X86.

I would appreciate any guidance or solutions to address this issue. Thank you for your assistance.

**Comment by ddennedy** [comment]
> This issue is obstructing the successful compilation of Shotcut on ARM.

I was able to build it successfully using msys2/clangarm64 multiple times and offer a download to users. Why don't you use it?

The only special thing I had to do was add a link library:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut-msys2.sh#L652

Soon I will post an Actions log that shows what happens on my build runner. 

I am closing this because you should be using the VMAF GitHub project for this.

**Comment by ddennedy** [comment]
Here is a [link to a build log](https://github.com/mltframework/shotcut/actions/runs/9723970533/job/26843906397#step:4:2008) where it shows VMAF configure, compile, and install.

**Comment by thiru31** [comment]
Thanks @ddennedy
