### ISSUE TITLE
Shotcut can't be used on Windows without administrator privileges

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#157]
Installation of Shotcut requires admin rights.

This was at least the case at a media school for kids/teens where I did a game development beginner workshop and wanted to include video editing videos of participants' games on Windows 7.

We were able to run exe files of an open source game that we modded, portable open source notepad++ and portable open source love2d game engine but installing Shotcut required admin rights.

This might be possible to solve by changing something in the installer or by providing a standalone/portable .zip release of Shotcut.

This defect most likely makes it impossible to use Shotcut on many schools' and universities' computers, negatively affecting user base & community growth.

**Comment by ddennedy** [comment]
This is by design. Some (most?) environments do not want ordinary users to be able to install Windows software because it can introduce problems. I know at times I did not give my children admin access to prevent exactly that.
As a workaround, an administrator can install it on one machine, zip the program folder and copy it elsewhere.
