### ISSUE TITLE
Resizing for exports

### ISSUE THREAD

**Issue by itagagaki** [mltframework/shotcut#1581]
Windows 10 Pro 22H2 / Shotcut 24.09.13

When I try to enable resampling on export, the following warning message appears

```
Reframe is for exports and may not do what you expect.

Do you want to change Video Mode in the Settings menu?
```

Firstly, is 'Reframe' in this message a mistake for 'Resample'?

And the meaning of 'may not do what you expect' is ambiguous.
This option to select the resolution of the exported video file is fine, isn't it?
But the message worry me.

If I answer ‘Yes’ to this dialog, nothing happens. This also puzzles me.
I think it would be better to clarify the question and the action for the answer.

**Comment by ddennedy** [comment]
I fixed the typo. As for the question and action when you choose yes, it is intentionally tricky because people keep misusing this function and report about incorrect results. You need to click No for something to happen. The question is clear.

**Comment by ddennedy** [comment]
"the meaning of 'may not do what you expect' is ambiguous." is ambiguous because often the results of using these fields is ambiguous to the user because they do not understand the difference between render and export.

Here is how it looks after fixing the typo
![image](https://github.com/user-attachments/assets/67967989-5235-4201-aab0-9bd84ceb48f0)

**Comment by bmatherly** [comment]
> Did you know that when you change the resolution in export Shotcut still renders the timeline or playlist using the Video Mode resolution and then scales and/or pads to the export resolution if it is different.

I think this is an important concept. The Reframe and Resample features help the user make better use of this architecture. But maybe they do not go far enough to educate the user on the underlying architecture. We don't use the term "render" anywhere that I see.

How about this for the message:

> When Resample is used, the project will be rendered using the Video Mode and then scaled and padded to match the Export resolution. The resampling process might reduce the image quality.

That is longer, and would make the message box bigger. So there are pros/cons.

Also, I wonder if clicking "Yes" could trigger the Video Mode menu (I'm not sure if that is possible). Maybe there should also be a "Cancel" option. I dunno.

**Comment by ddennedy** [comment]
Yeah, I was trying to be brief. Verbose dialog boxes can be annoying. I would add to your message, "or add unexpected black bars." A key point not easy to convey is that this feature is not WYSIWYG. That is the meaning of "may not do what you expect" without getting technical: the warning is for non-experts! Then, when you do change Video Mode of a project now there is a warning to review the result.

> I wonder if clicking "Yes" could trigger the Video Mode menu (I'm not sure if that is possible

Actually, on macOS there is a standard shortcut for all apps to open Settings. Most apps use a dialog. I mapped this in Shotcut to open the Settings menu. So, it can, but the tricky part is opening it at the correct coordinates since they must be provided (different on mac since it has a global menu). It could open the Custom Video Mode dialog, but that has this warning now. So, this would trigger a series of 3 dialogs: warning, warning, custom video mode. Plus, the Name field in the dialog looks weird in the context of this flow. The current approach encourages using that menu now and in the future. I will try to make Yes open the menu.

**Comment by ddennedy** [comment]
<img width="461" alt="image" src="https://github.com/user-attachments/assets/f17a353a-aaaf-4909-a1fa-51bd7b8f263e">

**Comment by bmatherly** [comment]
LGTM

**Comment by itagagaki** [comment]
Looks good. Thank you!
