### ISSUE TITLE
SVG text is not rendered properly

### ISSUE THREAD

**Issue by petaflot** [mltframework/shotcut#1585]
text that is centered and/or wrapped is not displayed properly.

![shotcut0](https://github.com/user-attachments/assets/b69ef49d-a37e-4865-9777-6aea8abdbc13)
![shotcut1](https://github.com/user-attachments/assets/8d724b45-81b7-407e-99f7-92be11255bba)

**Comment by ddennedy** [comment]
You did not provide your OS and Shotcut version. You also did not include your SVG.

Shotcut uses Qt library via [MLT](https://www.mltframework.org) to render SVG, and Qt only supports non-animated SVG 1.2 Tiny, which you can [read about here](https://doc.qt.io/qt-6/svgrendering.html#rendering-svg-files). I do not modify the Qt included in our builds or work on Qt myself.

SVG has problematic interoperability because it is complex, interpreted, and has many versions. So, it is generally not a reliable format. You can read more about versions on [Wikipedia](https://en.wikipedia.org/wiki/SVG).

Complex multimedia formats work best when you have more control over both the authoring tool and rendering engine. Therefore, I recommend using Glaxnimate (bundled in our builds) for vector graphics that can also be animated.

**Comment by petaflot** [comment]
currently running Shotcut 24.09.22 on Gentoo (profile: default/linux/amd64/23.0/desktop)

I understand how SVG could be rendered differently by different backends.

Here is the SVG file (I added some complexity that shows other variations of the problem) with some screenshots. Text in top rectangle: multi-line, centered text. Text in bottom rectangle: two single lines, left aligned. There is no animation.

![presents_2](https://github.com/user-attachments/assets/781c50ab-295c-42c8-b0a3-fc0f394bd95f)
![1](https://github.com/user-attachments/assets/5342fc15-8961-456b-9860-d7c2012f8d2b)
![2](https://github.com/user-attachments/assets/960cbdf5-0dff-4594-8d3d-8f606398e3ff)

Since a user is likely to use a single editor for SVG (in my case, inkscape), and since most programs insert clues in the SVG document that allows one to know which program was used to create the SVG, I suppose it shouldn't be too hard to use the same program to render the document (either by user config or dynamically based on the file's content).

For now, I will export manually and insert a PNG instead of the SVG. it's as easy as `inkscape --export-type="png" my_svg.svg`

**Comment by ddennedy** [comment]
> I suppose it shouldn't be too hard to use the same program to render the document

That is impossible to automate in an engine of a video editor, or at least a very bad software architecture. That will not be done, but the user can do that.
