### ISSUE TITLE
In locales with comma as decimal point, dragging the handle to a negative x/y in Size and Position filter results in black screen

### ISSUE THREAD

**Issue by metellius** [mltframework/shotcut#166]
Steps:
- Start shotcut with LC_ALL=nb_NO.UTF-8
- Add size and position filter to any content
- In the VUI, drag the position handle up or to the left such that x or y values become negative.

Now the video goes black, and the filter ui shows that the size is changed to 0x0 and negative x/y set to 0.

Debugging showed that the ui sets the following string as the rectproperty:

```
[Debug  ] <void QmlFilter::set(QString, QString)> "−1,77%/−0,19%:100,00%x100,00%"
[Debug  ] <void QmlFilter::set(QString, QString)> "−1,88%/−0,19%:100,00%x100,00%"
[Debug  ] <void QmlFilter::set(QString, QString)> "−1,98%/−0,19%:100,00%x100,00%"
```

But, if I set LC_ALL=en_US.utf-8 then it works as expected, and prints:

```
[Debug  ] <void QmlFilter::set(QString, QString)> "-1.46%/0.00%:100.00%x100.00%"
[Debug  ] <void QmlFilter::set(QString, QString)> "-1.56%/0.00%:100.00%x100.00%"
[Debug  ] <void QmlFilter::set(QString, QString)> "-1.67%/0.00%:100.00%x100.00%"
[Debug  ] <void QmlFilter::set(QString, QString)> "-1.88%/0.00%:100.00%x100.00%"
```

So the comma seems to be the cause here.
This code here in SizePositionVUI.qml looks relevant:

``` qml

onRectChanged:  {
    filterRect.x = Math.round(rect.x / rectangle.widthScale)
    filterRect.y = Math.round(rect.y / rectangle.heightScale)
    filterRect.width = Math.round(rect.width / rectangle.widthScale)
    filterRect.height = Math.round(rect.height / rectangle.heightScale)
    filter.set(rectProperty, '%1%/%2%:%3%x%4%'
                .arg((filterRect.x / profile.width * 100).toLocaleString(_locale))
                .arg((filterRect.y / profile.height * 100).toLocaleString(_locale))
                .arg((filterRect.width / profile.width * 100).toLocaleString(_locale))
                .arg((filterRect.height / profile.height * 100).toLocaleString(_locale)))
}
```

**Comment by mxa** [comment]
A problem seems to be that the local decimal divider is written in the .mlt XML file. This

- makes the file not shareable with someone who has the other decimal divider
- causes the file consistency check to report this file as damaged, and the automatic repair will "fix" the file and thus break it on the system with a comma as a decimal divider.

https://forum.shotcut.org/t/decimal-divider-localization-issue/845

**Comment by ddennedy** [comment]
Yes, the locale defined decimal point is written into the file by design. Also, the top of the file declares the locale in the LC_NUMERIC attribute. To facilitate file sharing, at the MLT level, the intention is to interpret all values using the declared locale. However, in reality and within Shotcut, things get messy quickly when possibly operating in a mixed mode (values from one decimal point system used in the context of another decimal point system). As a result, the repair system tries to simplify things by converting the file to the current system. However, it is not able to convert all properties. It only attempts attributes or properties with names: in, out, length, geometry, and rect.

**Comment by mxa** [comment]
I think there might be a bug in the repair tool then. My file has` LC_NUMERIC="de_DE.UTF-8"` before **and** **after** the "repair", yet commas get changed to points.

**Comment by ddennedy** [comment]
You are correct about a bug. There was an attempt to fix a bug for macOS in v17.01 that resulted in a regression for Linux and Windows and did not even work correctly on macOS. I reproduced the problem in your immediate reply above. Reverting the change fixes it for me using German for the region/language and English (period) for the numeric settings. If you want, you can test with v16.12 to check the behavior since that is what it is going back to essentially.

Regarding shareable, I think your map is exaggeration. What does "it" in "it" specifically refer to? How does standardizing on period make it more shareable than comma? It depends on the software to support it.

Some parts of the software needs to convert between strings and numbers, and some of this software is very deep within the engine. Other parts of the software like the UI needs to supports the local decimal point setting to match user expectation. Sometimes a numeric string value a user supplies may be delivered to the engine as string because the system for parameters is not strongly typed. So, the engine needs to understand the local decimal point setting to convert it correctly. In addition, the melt command line and XML authored manually are also interfaces that arguably ought to respect the local decimal point setting. It can be counter-argued that the XML should standardize on period per convention (see various programming languages and markups) and that XML reader/writer in MLT should always operate in that standard (what we call the "C" locale). I will think about that, but I have to check if it can be done safely in a cross-platform manner (without temporarily putting the entire process into a C locale while another thread supplies a numeric strings using the local decimal point).

**Comment by mxa** [comment]
Ah, I understand now. Thank you for taking the time for the detailed reply. I am in no way qualified to give you any advice, but it seems to me that the best way to avoid problems would be to have points as the decimal dividers anywhere in the code and the file format. The regional decimal dividers can be converted in the GUI depending on the locale.

**Comment by ddennedy** [comment]
This was fixed a while ago when much code was changed to use rect types (mlt_rect, QRectF) and serialized correctly using other locale-oriented fixes. Now, it is a legacy issue including other issues raised here with the resolution of #713.
