### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by rdbu** [mltframework/shotcut#174]
Crashes on multiple operations in the time line on Windows 10 computer:
- Drag mp3 file into timeline (multiple attestations)
- Adapt the length of fades by dragging the right edge of the fade effect
And many more that I already forgot. I had more than 5 crashes in the last half hour. Program with great potential, but as it is it is too unstable to use for actual editing work.

**Comment by ddennedy** [comment]
Unable to reproduce and not specific enough. It sounds like Shotcut is not very compatible with your system. You should try the different options under Settings > Display Method. Many people have more success with the DirectX option because Automatic prefers OpenGL but is unable to determine that is problematic on this system.
