### ISSUE TITLE
Filters don't apply or can't be modified

### ISSUE THREAD

**Issue by NicoPy** [mltframework/shotcut#211]
Bugs present on two machines running Windows10 x64 :
1) When adding a filter to a clip that is on the timeline, it often doesn't apply.
2) When a filter is applied to a clip that is on the timeline, modifying filter parameters often does nothing.
Version 16.03.01 is used.

**Comment by ddennedy** [comment]
Unable to reproduce. Provide exact steps from the beginning.

**Comment by NicoPy** [comment]
- Launch ShotCut
- File / Open other... / Colour / OK
- Drag and drop from source to timeline
- Click "+" in "Filter" view / Text / replace "#timecode#" with "The end"
- File / Open other... / Colour / select red colour / OK
- Drag and drop from source to timeline (after black colour)

Now, playing timeline : "The end" shows on black screen AND on red screen. After some clicks (to select a clip, play, stop...), neither black nor red have a filter appearing in filter view but "The end" still shows on both when playing.

Close Shotcut and start again.
Do the exact same steps than above (I beleive so).
Now, everything is perfect.

Globally, the behaviour is inconsistent. Sometimes it works, sometimes, it doesn't.
Most often, a filter can't be ajusted (modifications are forgotten)

**Comment by metellius** [comment]
I was able to reproduce it on Linux. An significant detail here is that after dropping the clip on the timeline, you don't click on the clip, so what you're modifying does not seem to be the actual clip in the timeline. I'm a bit unsure what you're modifying really, because when I again deselect the clip by pressing Ctrl-D, the set filter is back... My initial thought was that it's adding trackhead filters, but when I click the trackhead the filter list shows nothing.

**Comment by ddennedy** [comment]
By design, filters can be attached to clips, tracks, or the timeline as a whole. Pay attention. There is a text above the filter list that says if you are applying to a track or the Timeline. Yes, after adding something to the timeline, it is not automatically selected. Click the top left corner of the timeline to see filters attached to the timeline. I believe this is operator error. Playhead position does not determine the filter list. Whatever is selected does.

**Comment by ddennedy** [comment]
Reopening to improve auto-selection and indication of selection both on Timeline and Filters.

**Comment by NicoPy** [comment]
I made another try with carefully selecting clips. I was not able to reproduce the problem.
I can see "timeline" and "v1:" shown when corresponding item is selected. Precious piece of information. Using a vivid coulour could be usefull to warn about these special cases.
