### ISSUE TITLE
Can't switch timeline clips

### ISSUE THREAD

**Issue by KuenzelIT** [mltframework/shotcut#242]
Hey,

I'd like to move a clip to the front while moving all clips, which are in the way, to the right. Just dragNdrop does not work, if there is not enough space. All other tries weren't successful either.

Thanks!

**Comment by ddennedy** [comment]
This is simply not available yet. You have to either use another track or the Source player to move things around. For example, you can right-click a clip on timeline, choose Open, which opens a copy of it in the Source player. Then, delete the timeline clip, move playhead to the new position, and finally click the Insert button on the timeline toolbar, which copies it from the Source player to the timeline. Yes, I know that stinks, and it would be nice to simply drag-n-drop to reorder, but lots of things would be nice, and that is simply the way it is for now.

There is another workarounds if the clip you want to move is also in Playlist. Then, you can skip the first part of copying the timeline clip to the Source player. Next, delete the timeline clip you want to move, make sure ripple mode is enabled on the timeline toolbar, and then drag-n-drop from the playlist to the timeline. Ripple mode makes dropping on the timeline an insert operation instead of overwrite.

**Comment by zhouhuirun2015** [comment]
Ver16.05 is hardly drag clip from one video track to anthor.

**Comment by ddennedy** [comment]
FYI, reordering clips on a track will be easier in the next release (16.06) with new cut and paste commands.
