### ISSUE TITLE
Selecting OpenGL driver

### ISSUE THREAD

**Issue by sollapse** [mltframework/shotcut#247]
This is probably my system's configuration but after compiling Shotcut and running the output lists MLT's GL Widget detecting OpenGL Gallium LLVMPipe and a 3.0 GL context. For some reason Shotcut throws an error dialog of OpenGL 2.0 being needed. Is their an appropiate way to force the correct GL driver?

**Comment by ddennedy** [comment]
No, and Shotcut has been tested with Mesa and llvmpipe - mainly in virtual machines.

**Comment by sollapse** [comment]
I understand this might not be related to the application but do you have any suggestions on getting the program to detect the driver?

**Comment by ddennedy** [comment]
What does `glxinfo | grep OpenGL` say?
Does the binary provided by the project work?

**Comment by sollapse** [comment]
I'm currently using Mesa SWX11. The weird thing is when I changed to this driver, even after removing references to the llvmpipe library MLT still 'sees' the gallium driver.

OpenGL vendor string: Brian Paul
OpenGL renderer string: Mesa X11
OpenGL version string: 2.1 Mesa 10.3.2
OpenGL shading language version string: 1.20
OpenGL extensions:

**Comment by ddennedy** [comment]
I do not know what you mean claiming it is something MLT. Here is where it fails on you according to the original description:
https://github.com/mltframework/shotcut/blob/master/src/widgets/gltestwidget.cpp

That is in Qt, and since you are compiling from source, you can easily look into it deeper on your own. Even after this, the only time MLT has anything to do with OpenGL is when you enable GPU image processing, which is another level beyond the basic GL used to draw some UI (Qt Quick) and display the video, which is all Qt-based code:
https://github.com/mltframework/shotcut/blob/master/src/glwidget.cpp
