### ISSUE TITLE
debian packages

### ISSUE THREAD

**Issue by arthurzenika** [mltframework/shotcut#26]
It would be great to install shotcut through debian packages, either : 
- simply through a .deb file
- providing a third party debian source
- through an ubuntu PPA
- by proposing shotcut to be distributed by debian and/or ubuntu

**Comment by johanneswilm** [comment]
@ddennedy I understand your argument about not wanting to support other versions. However, this seems to make it kind of impossible ever to get included in any of main linux distributions. Is this only meant until it becomes stable, or is this meant as your policy for all future? If it is the second, then I would think it would be a good idea to start packaging this under another name as soon as possibly so that that other name can become known among all those wanting to install this on their system.

Btw, where can I find that registered trademark? The one for Firefox I found here: http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4805:9haxp9.2.9 . For Shotcut I found nothing in the trademark database, nor anything about Trademarking on the Shotcut website. If you plan on enforcing a trademark, it would probably be a good idea to write about that on the website.

Also: Is there any alternative name you would prefer for a deb package?

**Comment by ddennedy** [comment]
In the US, a trademark does not necessarily need to be registered: http://www.uspto.gov/trademarks/basics/register.jsp
I will soon add a trademark disclosure on the web site and About dialog. If someone wants an editor for Linux desktop through their package manager, then consider to use Kdenlive or Flowblade -  two other fine MLT-based projects.

**Comment by johanneswilm** [comment]
Yes, but a non-registered trademark doesn't have the same type of protection. Internationally there is no protection at all, and within the US you only have limited enforcement. Otherwise everyone forking any github project would need to change the project name immediately. I don't think you can forbid anyone from packaging the app under the name that it has as long as you don't have a registered copyright. And even if you were to acquire it now, people could make claims of prior art and therefore not be affected.

But don't worry, if you don't want others to use the name Shotcut for a packaged version, I am sure everyone will respect that anyway, also without a registered trademark. It's just not comparable to the Mozilla Firefox case.

As for your last point: Can you elaborate on this? Is Shotcut not meant to be used in production use? Is it just something meant for internal testing and demoing?  If that is the case, then it would probably also be a good idea to specify that on the site, otherwise people will think it's meant to be an alternative to the existing editors. Kdenlive is fine and all, but at least I was under the impression that Shotcut was developing new features and would be a viable alternative some day.

**Comment by metellius** [comment]
If any of you are interested I am experimenting with a debian package that simply installs the official shotcut release into /usr/lib/shotcut. It's currently available as a PPA here: https://launchpad.net/~haraldhv/+archive/ubuntu/shotcut/

**Comment by ipatrol** [comment]
I'm wondering if this could be reopened now that Debian has moved back to FFmpeg.

**Comment by probonopd** [comment]
> I only want to support and have people using very fixed software configurations regardless of OS or distribution. I do not want to make packages that install into the system and includes components that may conflict with already installed software or packages from the repository.

Would you be interested in having an [AppImage](http://appimage.org)? What you describe is exactly what AppImage is made for, enabling upstream application authors to ship software to end users in precisely the way and with precisely the components they want.

An AppImage is just a self-mounting filesystem image which contains whatever you put in there. Very similar to a `.dmg` on macOS. 

As for a test, I have taken your officially-provided binaries and put them into an AppImage:
https://bintray.com/probono/AppImages/Shotcut/_latestVersion#files

**Comment by ddennedy** [comment]
>  would you be interested in having an AppImage? @probonopd 

Maybe, I have been aware of that option for a couple of years. Except, now there are Snaps and Flatpaks. And all of them have a weakness compared to my current archive approach: one must be running the app to have the filesystem mounted in order to take advantage of the other executables Shotcut provides: melt, qmelt, ffmpeg, and ffprobe.

However, I think these do all have the advantage of preventing people from running the binary executable instead of the script wrapper. Also, some desktop environments do not support Shotcut's current launch icon that uses a hack in order to run an executable relative to the icon's directory - something not expressly permitted in the FreeDesktop.org spec.

**Comment by Sunderland93** [comment]
Deb-packages of Shotcut available in Deb-Multimedia repo https://deb-multimedia.org/pool/main/s/shotcut-dmo/shotcut-dmo

**Comment by Sunderland93** [comment]
A little later I create PPA for Ubuntu

**Comment by metellius** [comment]
> Deb-packages of Shotcut available in Deb-Multimedia repo https://deb-multimedia.org/pool/main/s/shotcut-dmo/shotcut-dmo

@ddennedy has requested in his exact github issue that people do not do this. Have you checked with him before uploading the package?

**Comment by Sunderland93** [comment]
> @ddennedy has requested in his exact github issue that people do not do this. Have you checked with him before uploading the package?

This is not my package. I just found it in Deb-Multimedia

**Comment by Sunderland93** [comment]
If I correctly understood - a problem in name only? What should I do to put the package in Debian and Ubuntu repositories? Rename Shotcut into something else?

**Comment by davidgiven** [comment]
Are there any updates on this? I'd really like to have this available from Debian, as it makes keeping the dependencies updated so much easier.

**Comment by ddennedy** [comment]
It is available in [Debian Multimedia repo](https://www.deb-multimedia.org/dists/testing/main/binary-amd64/package/shotcut).

**Comment by trebmuh** [comment]
FWIW: it is **not** Debian Multimedia (which is a team, part of Debian), it is deb-multimedia which is an external one-man-project repo.
