### ISSUE TITLE
Can't set duration of images.

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#262]
Shotcut 16.06.08, Windows 10.

I am unable to set the duration of JPG's that I'm trying to put in the timeline.  It's always stuck at 4 seconds.  Either using the arrow keys, or keying in the time manually, then hitting enter, does not change the time whatsoever.

**Comment by ddennedy** [comment]
I reproduced the problem exactly as described. However, there are workarounds. If the image is already on the timeline, drag the right edge of the clip. You can also adjust duration in the Source player - before adding it to the timeline - either by trimming or changing the duration field in Properties.

**Comment by lnx64** [comment]
I'll need to try the first recommendation, with the right edge dragging in the timeline, when I'm back at work (I left my laptop there).  However adjusting the properties when in the source player, was not working for me either, as it seemed to work for you.  When I get to work, I'll get a video of what it's doing, that apparently works for you.  I'm kind of curious what is causing this.  Out of all the free video editors, this one is without a doubt, the absolute best!

**Comment by ddennedy** [comment]
FYI, changing the duration in Properties of a still image in the Source player affects the **trimmed** (aka selected region in the scrub bar) duration. This is by design. The maximum/potential duration is fixed at 10 minutes to allow you to adjust the duration by trimming either in the source player or in the timeline.
