### ISSUE TITLE
Memory leackage bug?

### ISSUE THREAD

**Issue by vidcutter** [mltframework/shotcut#267]
Dear Shotcut developers,

I am running Shotcut 16.04. on Windows 10. When importing only 3 JPEGs (each less than 5 MB) Shotcut will allocate more than 2 GB of RAM. Importing videos instead doesn't require much RAM at all.

(My goal is to import several pictures up to about 50 in order to create a diashow with pan & zoom effects.)

Kind regards
Sachs

**Comment by ddennedy** [comment]
This is not due to a leakage, but rather usage. The engine, MLT, reads and uses images at their full resolution - not the project resolution - by design. It does this to provide the highest quality result for crop, pan, and zoom operations. You would not want to make an image from the original at project resolution, then crop it, and then zoom in on it. When images at full resolution are combined with caching, playback buffering, and memory pooling, it can use a lot of memory for just a few images. However, the caching mechanism is what also allows many images such as 50 or more without much more memory usage than just several images. Slow, smooth, high quality pan & zoom animation effects are in the engine but not yet exposed through the app.
