### ISSUE TITLE
shotcut not work on Lubuntu 16.04

### ISSUE THREAD

**Issue by Laui77** [mltframework/shotcut#273]
OS Lubuntu 16.04 64bit
I installed shotcut from the PPA
`ppa:haraldhv/shotcut`
but it doesn't work/start
In the Terminal with
`shotcut`
it doesn't start, see the attachment
[shotcut.txt](https://github.com/mltframework/shotcut/files/354803/shotcut.txt)

**Comment by ddennedy** [comment]
It works on Lubuntu 16.04 - just not on your system due to an adequate OpenGL 2.1+ implementation due to the nouveau driver or at least nouveau on this hardware. This is explained in some places in the [FAQ](https://shotcut.org/FAQ/), We try to detect a compatible OpenGL and present an error dialog at startup, but it is not foolproof. We do not strive to provide a lowest common denominator solution and will not fix this.

**Comment by ddennedy** [comment]
I switched my system over to nouveau, and I did not have this problem:

ddennedy@MS-7593:~$ glxinfo | grep OpenGL
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVC1
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

ddennedy@MS-7593:~$ lspci | grep VGA
03:00.0 VGA compatible controller: NVIDIA Corporation GF108 [GeForce GT 440] (rev a1)

So, maybe it is a problem with your nouveau on your hardware, or maybe it is something else completely different, but I do not know and cannot fix it. Shotcut is known to not work on some systems for reasons unknown due to lack of patches. So, either it works for you, or it does not, and if it does not, you can debug it and submit a patch.
