### ISSUE TITLE
Shotcut German Version Startup Error - Missing ordinal number 3906

### ISSUE THREAD

**Issue by PeterBluewin** [mltframework/shotcut#280]
OS-Version: MS Windows 10 64 bit
Grafic: AMD RADEON HD 6450
Shotcut version 16.07.01

Error: Missing ordinal number 3906 in DLL C:\Windows\system32\ssleay32.dll
This message is popup in a single message box after starting Shotcut.

Reported from: Peter Bluewin, peter.bluewin@wipn.de

**Comment by ddennedy** [comment]
I do not think this is specific to the German version. Our application toolkit (Qt) supports OpenSSL by trying to load it dynamically at load time, but neither Qt or Shotcut ships with a complete OpenSSL set of DLLs due to legal restrictions. Therefore, it is finding it in your system folder (or elsewhere in your PATH for other affected users), but those versions of the DLLs are incompatible. Therefore, this is a system-specific problem.

Is this issue preventing you from using Shotcut?

Windows does not ship with ssleay32.dll and the related libeay32.dll. They were installed to your system folder by some other application, tool, SDK, or runtime. I do not want to tell you to remove those DLLs from system32 because it might affect other software on your system. However, you can try to temporarily remove those DLLs from system32 **temporarily** just to verify the problem goes away.

In the future, we hope to provide our build of Qt instead of using the one provided by the project itself, and then I hope I can disable support for OpenSSL to prevent this problem.

**Comment by ddennedy** [comment]
[This](https://slproweb.com/products/Win32OpenSSL.html) is a popular location to get OpenSSL DLLs for Windows (referred to by the official OpenSSL project wiki) that is not a general DLL download site that can be risky. You might be able to fix this without affecting the software that needs OpenSSL in system32 by copying the DLLs this OpenSSL package provides to the Shotcut folder. Maybe try the 64-bit version first.

**Comment by ddennedy** [comment]
I just noticed that my 64-bit version of the Qt Creator tool includes these DLLs in its application install folder. You can try to download this zip file and extract it into your Shotcut folder (C:\Program Files\Shotcut or similar).

[openssl-1.0.2d-win32-dlls.zip](https://github.com/mltframework/shotcut/files/380454/openssl-1.0.2d-win32-dlls.zip)

**Comment by PeterBluewin** [comment]
Hi ddennedy,
" You can try to download this zip file and extract it into your Shotcut folder (C:\Program Files\Shotcut or similar)." 
Great, that fix the problem. Many thanks. Shotcut start now without any problems.
Thanks, Peter

**Comment by ddennedy** [comment]
The next version 16.09 due Sept. 2 is using a custom Qt 5.6.1 build that does not depend on OpenSSL. Closing as resolved.
