### ISSUE TITLE
Cannot encode, major issue

### ISSUE THREAD

**Issue by Hit-Bug** [mltframework/shotcut#284]
I get encode failures, when I check the log I get:

/usr/bin/nice: /usr/bin/qmelt: No such file or directory

===============================================
OS:-
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
Linux 4.1.27-27-default #1 SMP PREEMPT Fri Jul 15 12:46:41 UTC 2016 (84ae57e) x86_64 x86_64 x86_64 GNU/Linux

Shotcut version 16.07.26

**Comment by bmatherly** [comment]
Where did you get Shotcut from? Did you download it from here?
https://shotcut.org/download/

**Comment by ddennedy** [comment]
We do not support builds not provided by us. Debug it on your or ask your provider for help.

**Comment by Hit-Bug** [comment]
I downloaded the package from here:
https://software.opensuse.org/download.html?project=multimedia:apps&package=shotcut

**Comment by bmatherly** [comment]
Yes. You will have to talk to the openSUSE packager. We can not possibly support every build from every packager on the planet. So we just support our own build.

**Comment by plater** [comment]
This issue has just appeared in openSUSE's bugzilla and it appears to me that melt only supplies 
/usr/bin/melt. Can you give me an idea how I can enable qmelt. This is building the latest release of mlt 6.2.0 locally with all the qt5 dependencies for building shotcut installed. I've only recently started maintaining shotcut in openSUSE.

**Comment by bmatherly** [comment]
This is the build script that we use to make our shotcut build:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh
You should be able to infer what you need from it.

**Comment by plater** [comment]
After lots of searching, I did find reference to qmelt in your build script, unfortunately linux distributions are about shared libraries and minimizing system sizes as opposed to ms windows where every package has it's own dependencies in a directory under program files  also our build service doesn't allow downloading from git during the build process. webvfx isn't listed as an essential dependency and I can't find it in any major distribution. there is a line cmd make -j$MAKEJ -C mlt/qmelt but the latest release of mlt-6.4.1 doesn't have any reference to qmelt except in src/melt/melt.c concerning osx.
Does this mean that shotcut is unable to export files without me creating the new package webvfx?
I started giving shotcut tlc because I thought it was a good easy to use video editor and I'm sure it used to export to other formats a few versions ago.

**Comment by plater** [comment]
After lots of searching, I did find reference to qmelt in your build script, unfortunately linux distributions are about shared libraries and minimizing system sizes as opposed to ms windows where every package has it's own dependencies in a directory under program files  also our build service doesn't allow downloading from git during the build process. webvfx isn't listed as an essential dependency and I can't find it in any major distribution. there is a line cmd make -j$MAKEJ -C mlt/qmelt but the latest release of mlt-6.4.1 doesn't have any reference to qmelt except in src/melt/melt.c concerning osx.
Does this mean that shotcut is unable to export files without me creating the new package webvfx?
I started giving shotcut tlc because I thought it was a good easy to use video editor and I'm sure it used to export to other formats a few versions ago.

**Comment by ddennedy** [comment]
WebVfx is required, and the README is a a bit of an after thought. but I just added it. If you really do not want to include it, then I suggest you also not build the WYSIWYG HTML editor code, remove the integration of that, and thereby remove the dependency on QtWebKit module. qmelt became a dependency to get combinations of Movit GPU processing in conjunction with WebVfx working in stable manner. Oh, are you including Movit as well? I just added that to the README as well. However, at that point if not including WebVfx and Movit, I kindly request you not call the package Shotcut and to rebrand it.

**Comment by plater** [comment]
I'll have to create a WebVfx package then. Other packages tend to include rare dependencies in their sources as third party packages. Movit is a common package in all major distros except Fedora, Altlinux also has shotcut-17.06 but no webvfx.
Movit-1.5.1 was just accepted into Factory 3 days ago.

**Comment by plater** [comment]
I'm assuming that I need github.com/mltframework/webvfx.git for the package, the releases look old.

**Comment by plater** [comment]
@ddennedy I've hit a brick wall packaging webfx due to the fact that it needs mlt sources, I will attempt to build it within the mlt package or is there another solution?

**Comment by plater** [comment]
I've packaged webvfx as a link of the mlt package that somebody named libmlt a long time ago. Shotcut now works as expected. In future I will parse the build-shotcut.sh script in future to find build and runtime dependencies. You seemed concerned about the shotcut produced by openSUSE, if you wish to inspect the builds of shotcut, libmlt and webvfx use the following links:
https://build.opensuse.org/package/show/multimedia:libs/webvfx
https://build.opensuse.org/package/show/multimedia:libs/libmlt and
https://build.opensuse.org/package/show/home:plater/shotcut I haven't submitted shotcut yet as I have to update the changes file
