### ISSUE TITLE
Tracks are sometimes moved around when trying to add new video track

### ISSUE THREAD

**Issue by XyllyX** [mltframework/shotcut#296]
I've run into a new issue, after trying to add in a video track below my "base" track, removing it again (it had become a triple-video track timeline, then back to double), it set both my original video tracks to composite, and then after opening the project again (via open file), my video track was turned into an audio track but somehow the software still reads the audio clips as videos?

I did try to click below to try create a video track below, but new video track still made it above - I believe it's intended to be working correctly this way, but judging by what happened when I loaded up the file and such, I'm not sure if it's actually supposed to create a new track below and that the feature is just broken

Here's a link to a screenshot showing what had happened to my video track
http://i.imgur.com/bufRrsM.png

Here, it shows the playback still showing the correct part for that segment in the audio section
http://i.imgur.com/8IYtP4H.png

switching on composite on the video track does not show the intended effect
http://i.imgur.com/yZTkPiM.png

I've somewhat worked around this issue by making another new video track and replacing everything manually, ideally I'd rather not have to
http://i.imgur.com/dydi3ur.png

Windows 10 64-bit home
i7 - 6700HQ
16GB DDR4
GTX 960m 2GB

**Comment by ldennedy** [comment]
I've tried reproducing this issue on both OSX and Windows 10, but I can't get it to work and I'm not sure if I'm misinterpreting the report or not.

From what I can understand, you're saying the problem is a video track represented as an audio track but still plays video. By attempting to add a video track below V1, a new one was added above instead, so you've deleted it. After deleting it, both remaining video tracks became composite tracks. Saving and reloading the project file shows the issue.

Do you suspect the default placement of new tracks is the problem? I think it may just be an error with how their project file was saved and/or loaded. I've been trying to reproduce it by doing what you've said with multiple tracks but nothing ever appears out of order.

**Comment by ddennedy** [comment]
I believe this was caused by the bug in #293, which has since been fixed.
Is "base track" V1 (if you did not rename it)? Shotcut does not provide a way to insert a video track below V1. We have not been able to reproduce "my video track was turned into an audio track." If you can still reproduce the problem in v16.08.12, then please try to state them clearly.

**Comment by XyllyX** [comment]
I'll see if I can, it only "turned" into an audio track after I restarted the program after attempting to create a track below the original V1 (the first video track I created), I believe I also deleted that new track after making it and then saving, and re-opening (there were 3 video tracks at one point)

V1 was the first video track, the only video track after that was also changed to V1 it seems, but it was V2 before, and the original V1 had changed into an audio track

I'm describing it as best I can, but I saved it as it were in the last screenshot (as far as I can remember, some other things might have changed)

All I can say right now is that it hasn't been an issue since it first happened, but I don't know what could've caused it to change to an audio track, and as you can see from the screenshots, it was playing the video even where there was no video track, sorry if I can't say much else :(

I'll definitely let you know first thing and try to keep an eye out if this ever happens again
