### ISSUE TITLE
Filters are deleted when changing picture properties

### ISSUE THREAD

**Issue by matevz** [mltframework/shotcut#297]
When changing duration of an element on the track (e.g. a background image) using the Properties tab, all element filters get deleted.
Tested with Shotcut 16.08.12 on Ubuntu Linux.

**Comment by ldennedy** [comment]
Testing this, I found the bug only occurs with images, not videos. You said this happened to you when working with a background image, so I assume that was what happened. I'm going to change the title from "element" from "picture".

This seems like an easy fix though, since a similar bug occurred for videos, so hopefully one will be on the way soon.
