### ISSUE TITLE
Changing the text of a text filter causes crash when GPU processing is enabled

### ISSUE THREAD

**Issue by max-maag** [mltframework/shotcut#298]
First of all, this is pretty much a duplicate of #130. However, that issue is almost a year old and "might have been fixed [together with #220]" so I decided to open a new issue instead.

**Steps to reproduce**
1. Enable GPU processing.
2. Add clip to timeline.
3. Add "Text" filter.
4. Change text.
5. If no crash yet, go to 4. Sometimes it takes two or three tries.

**Result**
* Shotcut crashes and the standard Windows "shotcut.exe stopped working" error dialog appears.
* When no crash happens after changing the text, the preview of the text gets distorted beyond recognition.

**System information**
Shotcut 16.08.04 as well as 16.08.12
Windows 8
EVGA GeForce GTX 670 FTW+ 4GB, Game Ready driver v372.54

**Misc**
I can't reproduce #220 (i.e. resizing the text doesn't crash shotcut) so either this is a seperate issue from #130, or #130 and #220 weren't related to each other after all.

Also I have seen people upload log files. If someone could tell how to obtain those I'd be happy to upload them too.

**Comment by ldennedy** [comment]
Unfortunately this has to be closed, since it is a duplicate report. Thank you for your good intentions about bringing up an old issue that may appear to be abandoned, but some problems about the application and its development are of higher priority than others. Time and motivation plays a big part in furthering development. The GPU processing is still clearly experimental, so any of the issues concerned with that are kind of expected.

You can read about how to access log files in the FAQ.
https://www.shotcut.org/FAQ/#where-are-the-log-presets-database-and-settings-stored
