### ISSUE TITLE
HiDPI issue - Tiny icons

### ISSUE THREAD

**Issue by BraindeadBZH** [mltframework/shotcut#300]
Hello,

I'm on a Windows 10 15" laptop with a UHD display (2160p). While most of the UI is scaling properly, the icons are way too small
![shotcut-1](https://cloud.githubusercontent.com/assets/3399852/17822288/8fd97734-6656-11e6-84f7-3903edc96b94.png)

Maybe upgrading to Qt 5.7 would solve the issue.

**Comment by XYQuadrat** [comment]
I am also experiencing this issue. Using Kubuntu 16.04.

**Comment by metellius** [comment]
Shotcut is unfortunately not very high-dpi friendly at this time. There are a lot of hardcoded pixel sizes, and moving to a scalable design requires a significant effort.

**Comment by ddennedy** [comment]
This is not about a completely scalable UI, but the subject. Already Shotcut and Qt work and look good on a Retina Mac running OS X. We just want it to be the same on other OSes when using a [devicePixelRatio](http://doc.qt.io/qt-5/qwindow.html#devicePixelRatio) of 2.0. (Non-integer values can be awkward, and I have not yet seen Qt supplying that when using 125 or 150% in Windows 10.) To that end, in many places (on OSX), Qt multiplies pixel values used in Quick and Widgets. To that end, Shotcut already uses this ratio in most of its custom drawing code (e.g. GLWidget and color wheels). Most icons are 32x32 placed in a UI that specifies 16x16. When Qt applies the devicePixelRatio=2.0 at render time, then a 32x32 icon is displayed as 32x32. For this bug, as reported, it is as simple as that. I am attaching a screenshot from OS X for sake of comparison.
<img width="1259" alt="retina-screenshot" src="https://cloud.githubusercontent.com/assets/1146683/17832817/3f950e4e-66c1-11e6-8777-0e10c616cc5f.png">
I tend to close issues that are not hard defects in our code (or MLT) as "wontfix" aka "not my bug." This is largely a cosmetic enhancement request that depends on Qt. I am in the process of upgrading Shotcut to Qt 5.6.1, and we will see how it helps. My Windows 10 machine has a 40" 4K TV I use as a monitor, but due to its size I tend to run it at 125 or 150%. I will test the new build on Qt 5.6.1 at 200%.

**Comment by ddennedy** [comment]
Here is how Shotcut Qt 5.6.1 build looks (great!) running at 200% in Windows 10 Settings after I add one line of code to enable it: `QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`
![capture](https://cloud.githubusercontent.com/assets/1146683/17833613/b400bab6-66d6-11e6-99ea-866b153da85a.PNG)

I am targeting an early September release 16.09 using Qt 5.6.1.

**Comment by ddennedy** [comment]
See also https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by metellius** [comment]
I stand corrected, I had no idea qt did this much for free.

**Comment by XYQuadrat** [comment]
So this means that in the upcoming release this will be "fixed"? If so, amazing!

**Comment by ddennedy** [comment]
Closing because this it will be in next release due Sept 2.
