### ISSUE TITLE
Thumbnail is grabbed one frame too early

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#307]
How to reproduce:
- Import a clip with cuts in it. 
- Go to the last frame, just before a visible cut in the clip.
- Split the clip at that frame.
- The new clip shows the thumbnail of last frame of the old clip, and not the first frame of the new clip.  
  (I posted about this in the forum, I hope it's okay to post it here too, so it won't get lost?)

**Comment by ddennedy** [comment]
Is your Settings > Video mode set to Automatic?
If not, what is frame rate of your video mode and the frame rates of the clips exhibiting this problem?

**Comment by tin2tin** [comment]
It's a h.264, 24 fps clip in a mp4 container. It's the same thing if set as Automatic or 24 fps. Actually I need to step 3 frames to the right(from last visible frame of the previous clip in the player), to get the first clip on the left side and the second clip on the right side after a split cut.

**Comment by ldennedy** [comment]
I've noticed this on Windows 10 and OSX. Cannot currently access a Linux machine but I think it would be likely the same thing happens as well. Tested with default video mode settings, one mp4 25 fps clip, one MPEG 29.97 fps clip, and an mp4 23.97 fps clip.

**Comment by ddennedy** [comment]
> Go to the last frame, just before a visible cut in the clip.

This is not how split works in Shotcut by design. You should position the playhead to the first frame of the clip after the cut before making the split.

I retested this on the latest version 20.02 on a couple of clips with different frame rates, and it is working fine. If FFmpeg and MLT struggles with frame accurate seeking on a file/format, then it must be converted, and there is a function in Properties to Convert to Edit-friendly....
