### ISSUE TITLE
Jittery playhead at the beginning

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#318]
Shotcut 16.09.01, Windows 10 64-bit

When trying to move the playhead towards the beginning, it appears to get very jittery, and you can't control it until you let go of the mouse button.  I have made a video showing what is going on exactly so you can properly see the issue in action.
https://www.youtube.com/watch?v=UkcloHQVzVo

**Comment by lnx64** [comment]
I'm now on Linux, and on Shotcut 16.10.01, this weird playhead jitteryness happens on this platform also.  64-bit.

**Comment by ldennedy** [comment]
In the Timeline.js file, scrolling by dragging the playhead is handled by a dragging function. The right edge works well enough, but the left edge gets caught once there is nowhere left to scroll.
```
if (pos.x > headerWidth + scrollView.width - 50) {
            // Right edge
            scrollTimer.backwards = false
            scrollTimer.start()
        } else if (pos.x >= headerWidth && pos.x < headerWidth + 50) {
            // Left edge
            if (scrollView.flickableItem.contentX < 50) {
                scrollView.flickableItem.contentX = 0;
                scrollTimer.stop()
            } else {
                scrollTimer.backwards = true
                scrollTimer.start()
            }
        } else {
            scrollTimer.stop()
        }
```
The line `scrollView.flickableItem.contentX = 0;` specifically has a bad effect on this, because it's trying to reset the position all the way to the start. This causes that flinging left you described in your video. Removing this line does solve the problem of the playhead being pushed back, but it's still shaky.

I'm not going to say it's 100% fixed but consider this progress... :confused:
