### ISSUE TITLE
Can't switch between source/project tabs for existent project

### ISSUE THREAD

**Issue by itspec-ru** [mltframework/shotcut#341]
Shotcut version: 16.11
OS: Gentoo Linux x86_64
Reproduce:
1. Run shotcut.
2. Open existent project file.
3. Try switch between source/project tabs.

Switching from "project" to "source" tab **disallowed**.
Output In console:
[Debug  ] <TimelineDock::setSelection> Changing selection to (0)  trackIndex -1 isMultitrack false

4. Reopen the same project file.
Then switching from "project" to "source" tab **allowed**.

**Comment by ddennedy** [comment]
This is by design. At step 3, there is nothing in Source. It is only a multitrack timeline. The fact that you can switch between Source and Project after step 4 is because we need to close the current project to load a new one, and close tries to close everything including Source. In this case, it does not first check if Source is empty; it simply clears it with a black clip.
