### ISSUE TITLE
Drag and drop png images crash

### ISSUE THREAD

**Issue by Anatolt** [mltframework/shotcut#375]
I check it in Windows 7 and Windows 8.

https://www.youtube.com/watch?v=xnYH5cCRDXw

**Comment by ochilan** [comment]
Seems like a regression from shotcut 16.12 to 17.01. Could only reproduce on Windows, not Linux. I guess the problem is that the image is added with an enormous duration (also seen in the video) to the playlist and adding it to the timeline causes a crash/hang.
Also probably related, dragging an image in the Source panel shows the image with the path "/Live" and doesn't allow it to be added to the timeline at all. With 16.12, this all works as expected as far as I can see.

**Comment by ddennedy** [comment]
This was resolved recently by the fix for #369.
