### ISSUE TITLE
Muted/Unmuted Volume Clarity

### ISSUE THREAD

**Issue by snakehill** [mltframework/shotcut#376]
In either of the Fusion themes, it is nearly impossible to tell whether the volume is muted or not. Besides, there isn't any indication on the volume button or elsewhere showing whether the volume is muted or not at first sight to help with it.

![mutedornot](https://cloud.githubusercontent.com/assets/20109369/21962428/01c0c8f4-db26-11e6-9199-f443c99831a5.png)

[Windows 10 Pro; Shotcut 17.01.02]

**Comment by ddennedy** [comment]
I agree the depressed state is difficult to see in Fusion Dark but not Light. Unfortunately, the only control we have over the theme is to set colors, and the GUI toolkit simply makes disabled or depressed things darker such that dark -> darker is difficult to see. However, I agree there is general problem including the state of the player toolbar button. Instead of making the button "depressed" we can alter the image icon such that "x" means muted and ")))" means not.

**Comment by snakehill** [comment]
It's true the difference is easier to see in the Fusion Light theme, although the represented state is not clear at first sight (that is, whether it's pressed or depressed), until you toggle between the states and see that the darker one is supposed to represent a pressed button. This is mainly because the volume bar's general color is right in between the colors of both mute button states.

Altering the volume icon instead of the mute button as described would solve it all. Besides, doing that would also make it so one could see whether it's muted or not right away, without having to click it and needing to look at the bar and mute button first.

Thanks for the consideration.
