### ISSUE TITLE
SegFault when exporting videos 

### ISSUE THREAD

**Issue by BlitzKraft** [mltframework/shotcut#382]
OS: Sabayon, Kernel 4.9.0. 

I had about 10 videos queued to be rendered. I was watermarking my videos with a png file. This happened when I added the last file be exported. First two videos exported and were done. The third one in the queue was about 10% done and as soon as I clicked export, it crashed. 

The tail end of the log is here: http://pastebin.com/swAFBmKi 

I the mlt was saved at /tmp. However, the last two hours of my work was gone. Is there a way to recover the job queue? 

The tmpfiles created by autosave all had the name ending in 14734 as such: 

```
-rw------- 1 bk   bk   10101 Feb 14 20:48 shotcut-Q14734.mlt
-rw------- 1 bk   bk   12641 Feb 14 20:41 shotcut-P14734.mlt
-rw------- 1 bk   bk   10096 Feb 14 20:15 shotcut-m14734.mlt
-rw------- 1 bk   bk   11814 Feb 14 20:12 shotcut-O14734.mlt
-rw------- 1 bk   bk   10955 Feb 14 20:07 shotcut-R14734.mlt
-rw------- 1 bk   bk   10096 Feb 14 20:04 shotcut-q14734.mlt
-rw------- 1 bk   bk   11780 Feb 14 19:45 shotcut-z14734.mlt
-rw------- 1 bk   bk   11780 Feb 14 19:43 shotcut-Y14734.mlt
-rw------- 1 bk   bk   11780 Feb 14 19:40 shotcut-H14734.mlt
-rw------- 1 bk   bk   11780 Feb 14 19:33 shotcut-C14734.mlt
```

I mention this because this number is referenced in the last line of the log. I am not sure if it's relevant.

**Comment by ddennedy** [comment]
Shotcut does not provide a way to recover the job queue, but since you located the temp files, you can probably use the command line to process all of the temp .mlt files. Are you using Shotcut from a build provided through the shotcut web site or here on Github? If so, you can run `Shotcut.app/qmelt /tmp/shotcut-Q14734.mlt` in a terminal window, and so on for each file to process them. These temp files are not the project autosave, but what is written out for each job added to the queue. They are XML, and if you read them, near the top is a `<consumer>` block that includes the name of the output file - in case you want to see which temp file will create which output file.

The log file you provided shows a crash in the GPU processing code (see Settings menu in Shotcut), which is experimental and not very stable.

**Comment by BlitzKraft** [comment]
I forgot to mention, I downloaded the 17.02 sources from shotcut.org . Yes, I was using GPU acceleration. I first tested it with some videos and was faster. So, I chose to keep it turned on. Now that I know what to do in case of a crash, I will still be using that feature. 

Thank you for the fast response. This helped me a lot. Especially because I don't have to do the same stuff again.

**Comment by BlitzKraft** [comment]
Hey @ddennedy, thank you for the help. This has saved me an entire day of frustration. I really love that when it crashes, only one video has to be redone, even if there are a lot more in the job queue. Thank you very much!!
