### ISSUE TITLE
Timeline in new window crashes when opened

### ISSUE THREAD

**Issue by Lonswaya** [mltframework/shotcut#391]
System - Windows 7 Professional

So I reproduced this twice following these steps:
1) Open shotcut
2) Open timeline view
3) Drag timeline view to be its own separate window
4) Close timeline view only
5) Restart shotcut
6) Click the timeline button again

Timeline opens in the same spot in a new window, but with a black screen. Then, shotcut crashed.

Let me know if you need any more information about this bug.

**Comment by ddennedy** [comment]
I have not been able to reproduce the crash yet, but I am on Windows 10 with NVIDIA (GTC 980 Ti). The reason I mention the GPU is because the Timeline uses OpenGL for drawing, and this bug might depend on your GPU drivers. I do reproduce the black Timeline window. What is your GPU? If you use Settings > Display Mode > DirectX (which uses an OpenGL to DirectX mapping library called ANGLE), does the problem go away, or are you already using that?

**Comment by Lonswaya** [comment]
Doing that stops the crashing, but does have a black screen too. Closing and re-opening the timeline fixed the black screen.

The setting was originally on "Automatic", and my rig had a GTX 1060, by the way.

**Comment by ddennedy** [comment]
I will see if I can reproduce it on some other systems including other operating systems.

**Comment by ddennedy** [comment]
Also not reproduced on Linux with v18.01.

**Comment by ddennedy** [comment]
Was never able to reproduce and too old now.
