### ISSUE TITLE
Shotcut exporting problem version 17.06.01

### ISSUE THREAD

**Issue by hungkwo** [mltframework/shotcut#431]
i have a problem when i'm exporting my shotcut, it always show pending without going to any progress.
i have waited for 30min and still in pending mode.
i'm using Shotcut version 17.06.01, windows 10, my video is 4mins long with text and several picture and audio.
below is the log and xml code when it happens
[log shotcut.txt](https://github.com/mltframework/shotcut/files/1079810/log.shotcut.txt)
[xml shotcut.txt](https://github.com/mltframework/shotcut/files/1079811/xml.shotcut.txt)

Can anyone help. thanks

**Comment by ddennedy** [comment]
I reproduced this with your XML and my own media. To workaround the problem, disable Parallel processing in the Export panel.
The bug seems due to the first video item being a picture with the Text filter applied to it. If I swap the first two clips (pictures) on V1, then it does work with parallel processing but then gets stuck at 1% on the image with Text. Also, if I change the text on the first clip to reduce the length (remove last line and blank line above it), then it works as well (with parallel processing).

**Comment by hungkwo** [comment]
Ok. i tested it. if i remove the first picture, there are no problem at all. 
is it because the Text is too many? 
at first i thought because i put several videos that have different dimesion.

**Comment by MikeWallaceDev** [comment]
Hello, 
I am using version 18.11.18 and I seem to be affected by the same problem. Or least I have the same (rather specific) conditions.  My first video item is a picture (a generated black color) with some text on it (In this case, 3D HTML text).
My export does not even start. The percentage remains at 0%
The log window is empty
I'm running Shotcut from the command line (via an image) and see very little output (2 irrelevant lines of output)
_Sometimes_ the terminal output says that it can't open the mp4 file AFTER I cancel the job.

I can start a new thread if you think this is not relevant to the original bug report.
![image](https://user-images.githubusercontent.com/5375835/49812718-07747700-fd34-11e8-920d-d7d6e1729c55.png)

**Comment by ddennedy** [comment]
3D Text is very problematic; see the open issues regarding it. Does it work
if you do not include or use it? Does it work if it is not first?  no one
had been able to improve its compatibility or robustness.

**Comment by MikeWallaceDev** [comment]
@ddennedy Thanks for the reply. I don't know if you will be able to reproduce the problem. I think that it's a system configuration problem (I'm probably missing a dependency).
As for the strange way to say it, I first ran the application via AppImage, but when that didn't work I also tried installing a Snap. Both versions can be run from the command line. I was just specifying which version I used :)
So, yes, Solus Linux. Which means that I can not install Shotcut using the package manager.

Do you guys have some kind of script that would just check the dependencies?

**Comment by Butterfly** [comment]
> @ddennedy Thanks for the reply. I don't know if you will be able to reproduce the problem. I think that it's a system configuration problem (I'm probably missing a dependency).
> 
> As for the strange way to say it, I first ran the application via AppImage, but when that didn't work I also tried installing a Snap. Both versions can be run from the command line. I was just specifying which version I used :)
> 
> So, yes, Solus Linux. **Which means that I can not install Shotcut using the package manager.**
> 
> Do you guys have some kind of script that would just check the dependencies?

Most excellent suggestion that would have a broad reaching effect!!

I had something possibly similar occur with a popular browser you install by extracting directories instead of using e.g. `apt-get install` in Debian Linux. DAYS' worth of mind boggling trial and error led to partial success when I tripped over the `libjs` series of available packages.

From my perspective out here, it's about all these nice packages that arrive self-contained so that we *don't* touch things like `apt-get install`. WHAT HAPPENS IS... we then miss out on that handy little tickle that `apt`/`apt-get` and similar package managers put in our face regarding potentially useful *suggested* packages.

It would definitely be nice to have something secondary available to turn to for all those self-contained packages. If it's already out there, some of us just haven't tripped over that, too and yet. :laughing:
