### ISSUE TITLE
Audio distorts when video clip transitions from one clip to another

### ISSUE THREAD

**Issue by smiffalar** [mltframework/shotcut#433]
Trying to transition video clips from one to another by overlaying them which is perfect for the video however the audio track always distorts during the video transition, only for that second or two its fine before and after anyone know how I can fix this?

windows 10 / shotcut version 17.06.01

**Comment by ddennedy** [comment]
Is the distortion a crackling sound like clipping - if you know what that is?
See this blog post about the audio mixing:
https://www.shotcut.org/blog/new-release-1612/

If so, try reducing the volume a little on each of the clips involved in the transition to see if that helps.

**Comment by smiffalar** [comment]
Its like the sound is lagging and playing at a slower speed yet popping at the same time? Gave up on it saved the draft exported it and played the exported video this morning in windows movie player and its absolutely seamless? No distortion at all! Just happens whilst playing it on the timeline mid edit in shotcut! Strange! Thanks for your help though

**Comment by ddennedy** [comment]
More than likely this is because the overhead of processing the transition is causing the playback not to keep up with real time. The engine tries to drop rendering video frames to reduce overhead and keep the audio continuous; however, it still renders a video frame every second just to make it appear that video is not stuck or broken. Not only is transition processing an overhead but also seeking to the in point of a new clip has an overhead if the clip has an inter-frame compression as most files do these days - even from cameras. Next, if you have disabled Settings > Realtime, then the distortion is even more prevalent because then there is no skipping of video frame renders to attempt to keep audio continuous.

I hope that helps explain it to you and others. If things seem choppy or laggy, then it is a really good idea to export and play it to be sure. It is recommended to export your project periodically during its development any ways just to be sure the software is not experiencing a problem. We try hard to make it What You See Is What You Get, but sometimes there is a "Might" thrown in there. :-P
