### ISSUE TITLE
Clicks in audio from preview or timeline (few per second)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#462]
macOS 10.13.1
Shotcut 17.11.07

See demo:
https://cloud.mail.ru/public/FRgT/5uVFnQRDJ

Original source video:
https://cloud.mail.ru/public/E6Du/HSqBu3k1C

**Comment by vitaly-zdanevich** [comment]
With that problem I can not edit my great video project :(

Maybe I can fix something on my side?

**Comment by ddennedy** [comment]
This is a preview problem (playback within the app), and it is exporting fine. So, you can still edit video and get something usable out, but I do agree it is annoying and will look into it further as it this affects all videos and music and not just your file.

**Comment by ddennedy** [comment]
The strange thing about this bug is that I do not reproduce it on any of my development workstations including my MacBook, but I do on a MacBook at work. On that one mac where I reproduce it, Shotcut 17.08.01 does not exhibit this problem while 17.09.04 does. Two big things changed that could account for this: FFmpeg and SDL were upgraded. SDL is used for audio output; so that is more likely. What is also interesting is that running /Applications/Shotcut.app/Contents/MacOS/qmelt to play the file (command line tool to MLT engine of Shotcut) plays without the clicks.

It will be useful if you as well can verify v17.08 works better on your computer:
https://github.com/mltframework/shotcut/releases/tag/v17.08

**Comment by vitaly-zdanevich** [comment]
Ok, thank you.

Downloaded `shotcut-osx-x86_64-170801.dmg` but I can not install this - I see empty drive:
<img width="833" alt="screen shot 2017-11-16 at 9 37 08 am" src="https://user-images.githubusercontent.com/3514015/32877295-e162d6de-cab1-11e7-8750-af0f78edcb7e.png">

**Comment by vitaly-zdanevich** [comment]
Oh, I just opened again this mounted drive from desktop - I see the app, I copied it..

Works, no clicks/cracks!
