### ISSUE TITLE
'Remove' takes one frame too many?

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#475]
Reproduce:
1. Split a clip at ex. 30:00
2. Remove the clip to the right.
3. The playhead moves to 29.29(if fps=30)

I would expect the split to happen after the playhead. 
So split at 30:00 would result in a clip with a duration of 30:00

Uploaded example: splitRemoveStealsAFrame.mp4

**Comment by ddennedy** [comment]
The split occurs at the beginning of the current frame. When paused, the playhead is showing the beginning of a frame's duration. The player cannot play the moment after the last frame of a project. If you split at 01:00 and 02:00, move the playhead to 01:00, and remove the middle piece, the playhead does not move to 00:29 because it has sometime to play. I am not going to change anything here. I am not going to try to make the player be able to go the the moment in time just after the last frame and what? show black that is not in the project? show the last frame even though it does not exist at that time?
