### ISSUE TITLE
Text is no longer in the video filter list in 17.12

### ISSUE THREAD

**Issue by SuperOP535** [mltframework/shotcut#480]
The text filter is gone from the video filter list. The 3D Text is still there but I would like to use the normal text filter in my video.

flv video
shotcut 17.12
windows 10 (recently reseted)
gpu processing enabled

**Comment by ddennedy** [comment]
See #130. The Text filter is incompatible with GPU processing, and a fix has not been found; so, it is intentionally disabled for now when GPU processing is on. You can try using the HTML filter instead.

**Comment by JazzTp** [comment]
I guess that's why both the Text and Stabilize filters are not visible when "GPU Effects" is enabled...?

(I was expecting "GPU Effects" enabled to mean "a few new filters and part of the 'old' ones are experimentally being implemented through GPU computing". not "all filters via GPU, incompatible ones disabled".)

Shotcut 18.08.14, Linux Ubuntu 18.04.1.
P.S.:
I've worked professionally on FinalCut and Avid and used Canopus and Premiere a bit, and I sincerely think that Shotcut is already becoming a **_great_** NLE, congratulations.

**Comment by ddennedy** [comment]
@JazzTp Thanks for the complement. We would like Text and Stabilize to work in GPU mode, but that is unfortunately not the case and they need debugging. "GPU Effects" means _some_ of the filters have a  GPU counterpart (not always equivalent parameters) but also _most_ CPU-based filters are also available. Using both GPU and CPU filters has performance overhead due to memory transfers, which is why we group them in the list of added filters - to limit the transfers. GPU Effects also means GPU (actually, OpenGL) is also used for track compositing (no blend modes yet) and transitions.

**Comment by JazzTp** [comment]
I understand that it is a whole "GPU mode" what gets enabled, in which
using the CPU-based filters would imply unacceptable drawbacks.

Thanks for taking the time to answer!

Maybe by calling it "GPU mode", or something like that, you can avoid
people like me bothering you with the same doubt  :D

(And it was no compliment, it was my most sincere opinion, you're creating
a great NLE there.)
