### ISSUE TITLE
Strange playback behavior with JACK enabled

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#486]
Hello,

when JACK is enabled, navigating clips in the source viewer or in the timeline using J/K/L keys or the buttons below the viewer leads to unexpected results. Rewinding (J) results in forward playback. Rewinding faster (J again) leads to slow backward playback but as soon as playback is paused, the play head jumps to a completely different position. Fast forward playback (L, a few times) leads to a jump backward in time when pausing.

I'm seeing this behavior in shotcut 18.01.02 and a custom build based on 17.09.

**Comment by ddennedy** [comment]
This is tricky because:
- JACK does not support reverse or trick play (not 1X speeds). See [docs](http://jackaudio.org/files/docs/html/group__TransportControl.html). It is basically just start, stop, and seek.
- Shotcut both sends JACK transport commands and receives them.
- Sending a JACK start or stop command results in receiving not two events in response! (depends on clients?)
- Sometimes multiple commands need to be sent such as stop and seek.
- A seek command may result in an addition stop command in response.

I can make it so that rewind or fast forward does not tell JACK transport to start. Also, I can fix seek operations by telling JACK to stop. I am working on adding a guard to prevent processing a received command in response to sending one.

**Comment by ddennedy** [comment]
It is working good for me after the changes even when not using transport sync with another client.
