### ISSUE TITLE
Video stuck for 2 seconds

### ISSUE THREAD

**Issue by Ewber** [mltframework/shotcut#488]
For some strange reason, my video gets stuck for 2 seconds at the beginning, even though the original video never had the issue.

**Comment by bmatherly** [comment]
To make this issue actionable, you will need to provide more detailed information so that a developer can reproduce it and fix it.  An actionable issue includes detailed instructions of how to produce the problem from scratch from an empty project.

You might want to start here: https://forum.shotcut.org/ to see if other users can help you narrow the problem.

**Comment by Ewber** [comment]
Never mind, its just my computer.
