### ISSUE TITLE
Play/preview without losing the cursor position

### ISSUE THREAD

**Issue by john-bonachon** [mltframework/shotcut#502]
Is it possible to play a clip without losing the cursor position?
Like previewing the next frames, keeping the cursor position in the timeline.

**Comment by ddennedy** [comment]
No, and it will not be added. Eventually, there will be a markers feature that will help you return to a marked location, but we do not take or track feature requests without code.

**Comment by john-bonachon** [comment]
I understand your point, I've been lazy. However, I've thought that was a basic/handy feature to propose. Anyway, forget it.

**Comment by bmatherly** [comment]
> I've thought that was a basic/handy feature to propose. 

I would encourage you to take your ideas to the [forum](https://forum.shotcut.org/). There is a captive and active audience there. Feature ideas will receive little consideration in this issue tracker because it is only used for boring stuff like tracking the progress of confirmed bugs - and we like to keep the list of "open" issues free of feature requests so that the list doesn't become overwhelming.

**Comment by john-bonachon** [comment]
oh, got it. missed the forum. thanks.
