### ISSUE TITLE
Dissolve transition ca be inverted when switching to another transition type and back

### ISSUE THREAD

**Issue by zorbama** [mltframework/shotcut#52]
To reproduce:
1. Add two videos to the timeline and make them overlap to create a transition.
2. Click on the transition and open the properties pane.
3. Change the type of transition from "dissolve" to any other type.
4. Change back to "dissolve".

Expected result:
The dissolve transition is not affected by the "inverted" setting.

Actual result:
The video cuts to the second clip, then dissolves into the first clip, then cuts to the second clip again. This means that the dissolve transition is "inverted".

I also feel that the transition settings need to be greyed out when "dissolve" is selected, to better indicate that they are unavailable.

**Comment by ddennedy** [comment]
Are you willing and able to make the code changes to fix these problems?

**Comment by zorbama** [comment]
I'm afraid I'm unable to do that.

**Comment by ddennedy** [comment]
P.S. The transition settings are greyed out when Dissolve is selected, but the dark theme does not show that well. I think on the dark theme perhaps disabled things actually may need to be lightened because it is hard to see darker than dark. Unfortunately, we do not have control over the disabled color through the GUI library.
