### ISSUE TITLE
Crash when adding a movie to the timeline

### ISSUE THREAD

**Issue by PascalMinder** [mltframework/shotcut#548]
Shotcut 18.05.03
macOS  10.13.4

When I open a .mov file (filmed with an iPhone, and converted from the new iPhone standart format) and try to add it to the timeline, shotcut crashes.

**Comment by ddennedy** [comment]
I have not reproduced this, but I do not have an iPhone.

Did you have a previous version of Shotcut installed where this worked? In other words, do you believe this be a problem only with the new version 18.05?

> converted from the new iPhone standart format

I do not understand what this means. Can you explain it more, especially the target format you did not mention? Do you think the problem is specific to this format?

**Comment by PascalMinder** [comment]
I meant the HEVC format. When somebody shares a video form an iPhone to another computer the HEVC gets converted to an mp4 format.

As I found out, the video files itself were damaged. So I think the error is on Apples side. 

And Shotcut did crash because the video file was damaged. So I think this bug can be closed?

**Comment by ddennedy** [comment]
Do you mind uploading one of these corrupt files if you still have one to https://shotcut.org/notes/support-upload/ ? Then, I can see if the fault lies in ffmpeg or MLT.

**Comment by PascalMinder** [comment]
Yeah, I will upload it.

**Comment by ddennedy** [comment]
@natrist You did not mention a version. Version 18.05 is rather unstable due to the introduction of major new features. You should try [v18.03](https://github.com/mltframework/shotcut/releases/tag/v18.03), the latest stable version. If you still have a problem, then I do not reproduce it, and you will have to provide much more information or debug it yourself.

**Comment by natrist** [comment]
@ddennedy I'm using version 18.05.08.

**Comment by ddennedy** [comment]
I no longer reproduce this on latest version 19.10. There have been many updates since this report.
