### ISSUE TITLE
Add Filter Menu only has Favourites

### ISSUE THREAD

**Issue by Jovascript** [mltframework/shotcut#577]
In the Filter selection menu, when I press the add filter button, I can only see the default favourites, and there are no tab buttons to show any other sets of filters like so:
![image](https://user-images.githubusercontent.com/9502637/40674136-d4c4a21a-636b-11e8-8f83-b29715b7597d.png)

I am running Shotcut 18.05.08, on Windows 10 Home 1803

**Comment by ddennedy** [comment]
Based on the size of your text and icons in your screenshot, I think this is due to your Windows DPI (text size) setting. However, I could not reproduce this using 125, 150, 175, 200, or 300%. To workaround this, you can set a windows environment variable `QT_AUTO_SCREEN_SCALE_FACTOR` to the value `0`. Maybe if you provide a full window screenshot, your screen resolution, and text size setting I can reproduce it. Otherwise, this UI view is due soon for a major change to improve it, and then the problem will likely go away.

**Comment by ddennedy** [comment]
I moved the filter chooser buttons and search field to the top of the panel for the next release.
