### ISSUE TITLE
Crash when loading a project with a newer version

### ISSUE THREAD

**Issue by Dieter65** [mltframework/shotcut#624]
I created a project with a 40 minutes movie.
- Windows 7 Professional 32 Bit with service pack 1
- Shotcut-win32-180602.exe

When the movie became longer and longer the crashes increased when I edited the movie.
I had an 12 years old computer with a dual core processor and 2GB RAM.

So I reinstalled a system with an Intel 8700T with 12 cores and 32 GB RAM:
- Windows 7 Professional 64 Bit with service pack 1
- Shotcut-win64-180702.exe

When I load the project that was made with the 32 Bit version then the program crashes again when the timeline will be actualized.

[20180826_shotcut-log.txt](https://github.com/mltframework/shotcut/files/2321674/20180826_shotcut-log.txt)

![20180826_debug](https://user-images.githubusercontent.com/42718605/44630460-5e5d6880-a95e-11e8-9c45-fbbe678e0148.PNG)

What is the problem? Unfortunately I'm don't have experience with developping.

**Comment by ddennedy** [comment]
Try using the latest version 18.08.14. There have been 3 versions since 18.07 with all mainly bug fixes. If that does not help, try changing Settings > Display Method to OpenGL. If that does not help, upload the project file here by renaming it with .txt or zip-ing it.

**Comment by Dieter65** [comment]
Neither the version 18.08.14 nor the change to OpenGL is running.
Always the following fault:
[Debug  ] <LeapNetworkListener::onDisconnected> Disconnected from Leap Motion 
[Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "Verbindung verweigert" 

Attached the project file (hope only the file is enough because the complete project has about 10 GB).

[Kurzfassung.txt](https://github.com/mltframework/shotcut/files/2321926/Kurzfassung.txt)

**Comment by ddennedy** [comment]
I made a change in code to better handle an incorrect image file name extension for the next version.

**Comment by Dieter65** [comment]
I checked the image 001374.JPG. It' an original and not edited file from my camera and really JPG.
The fixed MLT caused the same crash. 
By the way: the old 18.06.02 (32bit) could open the complete project (but had other problems due to low performance).
Any other idea?

**Comment by ddennedy** [comment]
I am sorry to report that after I re-linked your project file (Kurzfassung - fix1.mlt) with my own media, I have not experienced a crash. I played the entire project from start to finish. An export is in progress.

Maybe there is still a problem with that image since it had something suspicious at that point. Try to rename the image file or move it away temporarily. Open the project, and Shotcut will report a missing file. Click OK to ignore that warning and to load it without that file.

**Comment by ddennedy** [comment]
A last option (because I think you uploading all of your media somewhere is ridiculous), is to download the Shotcut SDK, which has a debug build of shotcut. Note that it is 1.4 GB:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-sdk-180801.zip

After extracting it somewhere locate Shotcut/shotcut.exe in Explorer and double-click to run it. Open your project. When it crashes it might create a text file named shotcut.RPT with a crash report in the same folder as the exe. You can see if it is there and attach it here to provide some clue (unfortunately, it is only a clue).

**Comment by Dieter65** [comment]
I changed the name of the file 001374.jpg. When I opened the original mlt or the fixed mlt then in both cases a missing file was reported and after pressing OK shotcut crashed.
Here is the crash report of the debug version that was created with renamed image and fixed mlt (renamed from rpt to txt).
[shotcut.txt](https://github.com/mltframework/shotcut/files/2329845/shotcut.txt)

Could one of the following messages correspond to the problem?
[Warning] <MLT> [ 0x42d14df0] The DeckLink drivers not installed.
[Warning] <qt_png_warning> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Warning] <> file:///C:/temp/Shotcut/share/shotcut/qml/timeline/Clip.qml:146: TypeError: Cannot read property 'isMute' of null
[Warning] <qt_png_warning> libpng warning: iCCP: known incorrect sRGB profile

**Comment by ddennedy** [comment]
Those warning messages are not a problem. The crash report tells me if failed when reading an image file, but it does not tell which one it is unfortunately.

You can to figure out which one it is by moving all image files out of their folder, opening the .mlt file in Shotcut and click OK on the missing files dialog, seeing if it crashes. Then, working in batches of say 10 images at-a-time, move the images back into their folder and reopen the project, again clicking OK on the missing files dialog until it does crash again. Then, you know it is one of the last 10 you restored. After that, work backwards to remove one at-at-time until the crash stops. Now, you know which one is causing it to fail.

**Comment by Dieter65** [comment]
I moved group for group out of the folder and also file type for file type out of the folder. The result is that none of the files are faulty.

The problem occurs when the number of files in combination is too high. Looking back to the log files. I remember to two messages:
1. The first item of the list referring to the access violation is the call libmltqt.dll!refresh_image
2. [Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "connection denied"

My project is stored on a NAS server and I think there are too many refresh calls at the same time after loading the project. The refresh frequency is higher than the possibility to finish all these calls because the access to the NAS server is not fast enough.

I made two tests:
1. Changing the project to a local SSD drive. The export was not faster but the crash didn't appear any more.
2. Switching off "Show Audio Waveforms" and "Show Video Thumbnails" in the timeline. The crash didn't appear any more.

So my problem is solved but there should be made a fix that prevent too many refresh calls e.g. wait for the next call until the last call is finished.

Thany you for the excellent support!

**Comment by ddennedy** [comment]
In order to make a definite fix, I need to be able to reproduce it, which I have not. I also tested on a NAS. There are some things that occur in parallel in the background that depends on the number of CPU threads. My machine has 8 cores/16 threads, and yours has 12/24. That might have something to do with it. Perhaps I should limit this not only to prevent this crash but also to reduce I/O contention.

**Comment by Dieter65** [comment]
Excuse me. I was wrong. I wrote that I have 12 cores. But the 8700T has 6 cores and 12 threads.

**Comment by ddennedy** [comment]
Well, you can see I added a change based on this issue to try to prevent this from occurring to you and others in the future. As well, I think this can make Shotcut more well behaved feeling especially when opening an old project whose thumbnails and waveforms may no longer exist in the cache.
