### ISSUE TITLE
Crash in v15.04 (Windows) when inserting a mlt file as the first element of the playlist

### ISSUE THREAD

**Issue by BenLubar** [mltframework/shotcut#63]
Happens both on GPU-accelerated mode and software-rendering mode (tested by reconstructing the mlt file in each mode).

Non-GPU mlt files are here: https://gist.github.com/BenLubar/1a725f9a4fba90742b9b

Inserting either one as the first clip by dragging from the video viewer to the playlist crashes ShotCut. It appears to generate the first of the two thumbnails before it crashes.

The `bgfx_*.mp4` files are 50fps with no audio and `Alien Swarm 2015.04.21 - 13.06.37.81.mp4` is 60fps with AAC audio. They are all 720p.

**Comment by BenLubar** [comment]
Additionally, it seems to happen only if the video wasn't paused before dragging it to the playlist.

**Comment by ddennedy** [comment]
Unable to reproduce with my own MLT XML files created by Shotcut (as I see yours have been tagged with the shotcut=1 property). I have not taken the time to try with yours and manually relinking media. In any case, it is not possible in the the design of Shotcut and latest 16.01 version to drag a project file to the playlist unless you choose File > Open MLT XML As Clip to open it. Otherwise, dropping a project file opens the file as a project. If I do that (Open MLT XML As Clip) and add it to the playlist, then it does not crash for me.

This needs testing on the latest version and steps to reproduce as the steps here cannot be followed.
