### ISSUE TITLE
AppImage cannot be launched, does not bundle all needed libraries

### ISSUE THREAD

**Issue by probonopd** [mltframework/shotcut#634]
Getting

![](https://github.com/AppImage/appimage.github.io/blob/36c030d9612b81cb12c3a02929a06db6daae5a54/database/Shotcut/screenshot.png?raw=true)

libsdl2 should be bundled. As should be every library that is not on the https://github.com/AppImage/AppImages/blob/master/excludelist.

References:
* https://github.com/AppImage/appimage.github.io/pull/576
* http://docs.appimage.org/

**Comment by ddennedy** [comment]
I started working on this by recursively enumerating library dependencies, filtering them, and copying them in. We also require JACK, and I see that is on the excludelist. We check for it at runtime and present a dialog like the above. I think the reason we did not include SDL was because SDL 1.2 had different libraries for various audio backends, and there was a problem in some testing. This goes way back before we upgraded to SDL2.
