### ISSUE TITLE
Issue with Multi-Monitor Setup in Linux-Env

### ISSUE THREAD

**Issue by sledge1977** [mltframework/shotcut#658]
Hello,

today I tested Shotcut on Manjaro and Ubuntu and found that there is an issue with Shotcut in Multi-Monitor Environments.
I have a Setup with three monitors. 
3
2-1

So my Main-Monitor is #1, followed by a second to the left and a third above the second.

I tested the Snap in Ubuntu and the Portable Version in Manjaro. In both Environments the Menu was not working when having the Main Window on my Main-Monitor. I had to move to the 3rd Monitor to see the menu.
Seems to be an issue with the coordinates or something. Opening the Menu on the 3rd monitor seems to be working fine. But opening the menu on #2 showed a Menubar bar filling the complete height of the screen.

Jens

**Comment by ddennedy** [comment]
I had to change the graphics card on my Linux box recently, and I need to get some new adapter or cables to be able to test this. I think this might a Qt issue. Both the portable and the snap use the same version of bundled Qt: 5.6.1. It would be great and appreciated if you can test the [Flatpak](https://flathub.org/apps/details/org.shotcut.Shotcut) because it uses Qt 5.11 the last time I checked.

**Comment by sledge1977** [comment]
I just tested the Flatpak. Seems you're right. The menu works using the Flatpak.

**Comment by ddennedy** [comment]
Qt in our portable archive, AppImage, and Snap have all been updated to Qt LTS 5.9.6 earlier this year. This is probably fixed in those as well.
