### ISSUE TITLE
shotcut 18 saves timestamps with commas on a german mac os. 

### ISSUE THREAD

**Issue by klausbreyer** [mltframework/shotcut#668]
hi, we experienced something weird. 

Shotcut on a german mac saves timestamps with a comma (like it is common in germany)
The same installed version with english region settings saves the file with a dot (like it should)

![image 1](https://user-images.githubusercontent.com/32771/48554827-bf526800-e8df-11e8-8778-749c73c609b0.png)

this results in a problem, when you try to render the melt file on an other system, like a linux server ;) 

in Version 17 everything was fine on a german system. 
![image 2](https://user-images.githubusercontent.com/32771/48555054-5fa88c80-e8e0-11e8-9f99-633de5cd4840.png)

**Comment by ddennedy** [comment]
This is by design. The LC_NUMERIC attribute declares how the numbers are stored in the XML document. MLT for Linux reads this attribute and converts the numeric string to a number type using the specified locale.

**Comment by klausbreyer** [comment]
are you sure this is intended? this makes me thinking, that it is by design not possible to work together with 2 macs, one with german and one with english region settings?

also it gets worse. we have troubles working together with a 3rd computer, a windows machine in spain (with spanish as well as with english settings)

**Comment by ddennedy** [comment]
Unfortunately, this is due to a technical issue with an early fundamental design decision of MLT called properties that are not strongly typed and can be set as string and interpreted as a number. User-facing interfaces that should allow users to use locale-specific numerics can set the property as a string, or a property read as a string can be passed-through the system. As a result, Shotcut must convert a document from a foreign locale to the current one, but that does not completely prevent collaboration. It may, however, fail to convert some property values (e.g. filters) and not work well for all workflows (e.g. git). I agree this is a shortcoming, but there is no easy fix, and it does not affect 99% of the users. I would like to change something in MLT to make it possible to store things in a locale-agnostic manner, but I still need to revisit that more deeply.
