### ISSUE TITLE
Overlaying Alpha Track Darkens Final Output

### ISSUE THREAD

**Issue by cart** [mltframework/shotcut#674]
OS: Arch Linux
Version: 18.11.18

First, I'm loving Shotcut so far. For the most part very stable, snappy, and performant.  Thanks for making awesome software!

I encountered a bug where overlaying an alpha track darkens the base track, even with 100% alpha. I've encountered it in the following scenarios:

1. 100% alpha (default color) over a gray base track
2. 100% alpha png over a video base track
3. 100% alpha png with some color 

Example of (1)
![image](https://user-images.githubusercontent.com/2694663/49204618-52b87e00-f361-11e8-8293-f7e3ce6ec84b.png)
![image](https://user-images.githubusercontent.com/2694663/49204497-efc6e700-f360-11e8-8840-c4db24bdaf2e.png)

Note the rendered color gets darker when we get to the transparent track. This happens both in the preview and the final render. I replicated it with both the Flatpak release and the AppImage.

**Comment by cart** [comment]
And heres an example project replicating the issue:

[AlphaBlend.zip](https://github.com/mltframework/shotcut/files/2627982/AlphaBlend.zip)

**Comment by ddennedy** [comment]
100% alpha to me means opaque whereas 0% is transparent, but I understand what you mean.

Actually, it seems to lighten it by 1 8-bit value in the blue channel. Ideally, the color eyedropper shows rgb(50, 50, 50) but it does not due to YUV-RGB conversion rounding errors.

![image](https://user-images.githubusercontent.com/1146683/49270101-f9158980-f41c-11e8-93c3-cfcd46dab2a3.png)

![image](https://user-images.githubusercontent.com/1146683/49270126-1ba7a280-f41d-11e8-9598-41c17be55ec0.png)

![image](https://user-images.githubusercontent.com/1146683/49270255-51e52200-f41d-11e8-9cd8-e6f45e3585ad.png)

Shotcut uses the [cairographics](https://www.cairographics.org/) library for compositing.

**Comment by ddennedy** [comment]
As far as I can determine, this is actually an inaccuracy in the color generator's RGB to YUV conversion coefficients for the BT.601 colorspace. If I force the color generator to use ARGB, which I had planned to do to let FFmpeg libswscale convert it to the target colorspace more accurately, then I get this result for the lower track, which is the same values for the composited positions:

![image](https://user-images.githubusercontent.com/1146683/49271443-814a5d80-f422-11e8-9048-2ac4422071c7.png)

**Comment by ddennedy** [comment]
Reopen if you can provide hard evidence of #2 from your list.

**Comment by ddennedy** [comment]
I tried many different combinations of [swscale flags](http://www.ffmpeg.org/doxygen/trunk/swscale_8h_source.html), but it did not make a difference.

**Comment by ddennedy** [comment]
Steps to determine if swscale, MLT, or Shotcut issue:

1. Create gray (50, 50, 50) in GIMP and export as BMP
1. ffmpeg -i 'rgb 50-50-50 640x360.bmp' 'rgb 50-50-50 - ffmpeg.mp4'
1. ffplay 'rgb 50-50-50 - ffmpeg.mp4'
1. a color eyedropper (I wrote a quick app using Qt Creator and Qt Quick's FontDialog API) verifies the color is still 50,50,50. This confirms ffmpeg with swscale RGB->YUV is OK.
1. I reproduced the same in v18.11.18 of Shotcut using the BMP with (mlt_image_format=rgb24) in Export > Other. This confirms swscale RGB->YUV is OK.
1. I reproduced the same in dev version of Shotcut using the color generator with (mlt_image_format=rgb24) in Export > Other.  This confirms Shotcut color generator with swscale RGB->YUV is OK.
1. ffmpeg -i 'rgb 50-50-50 - ffmpeg.mp4' 'rgb 50-50-50 - ffmpeg.bmp'
1. ffplay 'rgb 50-50-50 - ffmpeg.bmp'
1. eyedropper shows 50,50,50. This confirms ffmpeg with swscale YUV->RGB is OK.
1. melt 'rgb 50-50-50 - ffmpeg.mp4' -consumer 'avformat:rgb 50-50-50 - melt.bmp' vcodec=bmp
1. eyedropper shows 50,50,50. This confirms MLT with swscale YUV->RGB is OK.
1. open 'rgb 50-50-50 - ffmpeg.mp4'  in Shotcut (Video Mode 720p50) and use eyedropper on its preview
1. eyedropper shows 50,49,50. This shows Shotcut's viewer has an issue. It uses MLT to render to yuv420p and then uses OpenGL shader to convert to RGB. This code probably has a slightly incorrect coefficient for the conversion.
1. export this from Shotcut as default MP4, open the result with ffplay
1. eyedropper shows 49.49.49. Then, I notice 'rgb 50-50-50 - ffmpeg.mp4' has yuv444p while this file has yuv420p (most typical delivery pixel format).
1. ffmpeg -i 'rgb 50-50-50 640x360.bmp' -pix_fmt yuv420p 'rgb 50-50-50 - ffmpeg - yuv420p.mp4'
1. ffplay 'rgb 50-50-50 - ffmpeg - yuv420p.mp4'
1. eyedropper shows 47,50,47. This means some inaccuracy occurs due to subsampled chroma. MLT renders to yuv422 internally before converting to yuv420p for shotcut preview or encoding.
1. ffmpeg -i 'rgb 50-50-50 640x360.bmp' -pix_fmt yuv422p 'rgb 50-50-50 - ffmpeg - yuv422p.mp4' followed by ffplay and eyedropper gives 50,50,50.  This confirms ffmpeg with swscale RGB->YUV422 is OK.
1. melt -profile atsc_720p_50 'rgb 50-50-50 640x360.bmp' -consumer 'avformat:rgb 50-50-50 - melt - yuv422p.mp4' pix_fmt=yuv422p gives 49,49,49. This confirms a problem in MLT with swscale RGB->YUV conversion.

In hindsight, the eyedroper on Shotcut preview might be a subsampled chroma issue since the input was 4:4:4 downsampled to 4:2:2 and then 4:2:0 for delivery (4:2:0 is the least amount of data to transfer over PCIe bus to GPU and closest to most export targets).

Next, I notice in MLT debug log output:
```yuv422 @ 640x360 space 601->709
...
[swscaler @ 0x7f50bc90a780] YUV color matrix differs for YUV->YUV, using intermediate RGB to convert
```
When the input has no colorspace transfer characteristic signaling, MLT assumes SD resolution or less uses BT.601. Adding `force_colorspace=709` after the producer on the melt command line makes the messages go away but does not help. Changing swscale flags to add `SWS_FULL_CHR_H_INT` fixed the melt command line output of the last step! However, incorporating this change into all uses of swscale has not fixed the timeline test project. :(

If I edit the test project and change the transition to qtblend or frei0r.composition, the problem goes away. This implies a problem with frei0r.cairoblend. With more troubleshooting, I found a rounding bug in the premultiply alpha function it uses to prepare the images for cairo.

**Comment by cart** [comment]
That is some seriously impressive debugging. Thanks for looking in to this! (and for fixing it so quickly)

**Comment by ddennedy** [comment]
You can download the nightly build with these fixes in portable tarball format here:
http://build.mltframework.org/viewLog.html?buildId=59766&buildTypeId=bt36&tab=artifacts
