### ISSUE TITLE
Global menu on XFCE

### ISSUE THREAD

**Issue by rauldipeas** [mltframework/shotcut#684]
How can I use Shotcut with global menu in XFCE?

**Comment by ddennedy** [comment]
This is unsupported as it requires a Qt plugin that is not provided in our builds. This is one of the drawbacks of a self-contained build - we are not going to provide specialty Qt plugins with the Qt we provide. You can look for a distro-provided shotcut package, but they tend to poor quality and out-of-date. We are not going to complicate our already difficult build process to include this (besides other considerations, it would require bundling a bunch of XFCE-libs that most users do not need).

**Comment by rauldipeas** [comment]
Could You give me the way to do this by myself?

**Comment by ddennedy** [comment]
Sorry, but I do not know. I know about a Qt plugin for Unity global menu, and I assume there is something for XFCE. It is not easy because our Qt version is different than your system/distro Qt version. :(

**Comment by rauldipeas** [comment]
Thanks, I'll keep looking for this...

**Comment by Butterfly** [comment]
Pre-thought 1: If you use ShotCut a lot, there's a possibility that it might load automatically after each reboot. You could (try):

Applications > Settings > Session and Startup > Application Autostart (tab) > Click "Add" button > type full path to executable file in Command text field then exit out as appropriate to save that change.

That may or may not work, but it's worth a shot.

Pre-thought 2: ArchLinux Wiki to the rescue with a nice, *cognitively friendly* explanation of just these very files: [Desktop entries](https://wiki.archlinux.org/index.php/desktop_entries)

OK... Pre-finding [ArchLinux's "Desktop entries" wiki page](https://wiki.archlinux.org/index.php/desktop_entries), I created a hack... a work-around that worked **FOR ME, BUT** I don't have `shotcut` downloaded to test *it* specifically. I tested the following with a different but similar self-contained package already on my computer.

**DISCLAIMER**: Some of the following lines will surely need tweaked, but, again, this *DID* work just like this.

To start this, I knew that we, *as root*, can play around in:

/usr/share/applications

Next, I found a *third* similar video editor that had been installed via Debian Linux `apt-get`. As *root* user, I used the `mousepad` text editor to open that third video editor's corresponding file under /usr/share/applications.

**WARNING IF YOU TEST DRIVE THIS**: Save that newly opened file under a different name **NOW before you touch anything else**. You **will lose** that original entry in your Applications Menu if you do NOT. You're about to test drive overwriting that information. That's what will cause you to lose that original, previously fully functioning Applications Menu entry.

[Uploading shotcut-test-menu-entry.desktop.txt…](Example file, just drop the dotTXT ending that Github required)

So... These are the lines that are now in the file that just worked *for me*:

```
[Desktop Entry]
Name=ShotCut Video Editor
GenericName=Video Editor
X-GNOME-FullName=ShotCut Video Editor
Comment=Create and edit videos and movies
Exec=/entire/path/to/shotcut/executable/location %F
Terminal=false
Type=Application
#Icon=shotcut
Categories=GNOME;GTK;AudioVideo;Video;AudioVideoEditing;
#MimeType=application/vnd.videoeditorexecutablename-project;
#X-AppInstall-Package=videoeditorexecutablename
#X-Ubuntu-Gettext-Domain=VideoEditorNameWithCapsEGShotCut
```

That's been tweaked to need as little further updating as possible to **possibly** function on other users' systems. Before final edit to include here, some of that matched as needed for it to open that third video editor app here locally (for me).

Those hashtagged lines do appear to be successfully commented out because the icon on my system defaulted to a recognized default. If left uncommented, there is a blank space instead of an icon. That's what told me that the hashtags do work here.

I tried deleting some of those commented out lines rather than hashtagging them. The menu entry *zap* disappeared and would not come back for nothing even after those deleted lines were put back in place. The Applications Menu entry reappeared when I simply created a new, differently named file and filled it back in again. *Odd quirk*. :smile:

The `Icon` line will NOT work because that icon is within the self-contained file. The work-around there would be to play around with adding appropriate icons under /usr/icons.

Where I wrote `videoeditorexecutablename`, that would possibly be replaced with `shotcut` *IF* those lines are appropriate for ShotCut. The capitalization of that word will match however the *clickable* executable is named, presumably most likely in all lowercase letters, e.g. `shotcut`.

For the last line that includes `VideoEditorNameWithCapsEGShotCut`, that appears to most likely be the "proper name" for the executable program. *DISCLAIMER:* I'm just guessing about that based on what was there before I adapted the file for this. :smile:

If this looks like something that might actually work, Developers are invited to please edit my comment as necessary if you have that type of ownership here. If that's not possible, just let me know what needs changed to fit ShotCut's personality, and I'll make the change(s) as soon as possible. That's in case mine is the only comment websurfers wander in to read here.

**OF NOTE**: That `MimeType` line in particular seems like something important that should be updated, uncommented, and included if possibly applicable to ShotCut. On the flipside, there is the possibility that line will forever be irrelevant to self-contained packages/programs. :smile:
