### ISSUE TITLE
Crash when deleting last transition from the timeline

### ISSUE THREAD

**Issue by ygoe** [mltframework/shotcut#691]
I've just started using this program today and played a bit with it. At one point I noticed that the audio waveform of a video track was wrong. While it played all the sound correctly, the waveform display was zoomed to about 10% of the clip length. So I deleted things. First deleted the clip with the wrong waveform display, then deleted the clip after it, and finally deleted the transition I made between them. That was my last action, then the program crashed and disappeared. I wasn't offered any details when I started it again, so I guess you'll have to guess what happened. If there's a crash dump, please let me know how I can find it.

Windows 10.1709 x64, Shotcut 18.12.23 x64

PS: It would have been helpful to find a link to this project from your website. Google helped me out though. I only guessed that you're here because I could choose GitHub as a download server.

**Comment by ddennedy** [comment]
I have seen the waveform not display completely as you describe especially when zoomed in on the timeline, but I have not found the cause yet.

Are you able to repeat the steps for this crash? I am not reproducing it. Please explain exactly how you are deleting because there are multiple ways. Also, let me know if Ripple All Tracks is turned on in the Timeline menu and if you have more than one track.

Windows crash logs are in C:\Users\All Users\Microsoft\Windows\WER\ReportArchive, but they never contain enough information to help me. The debug build of shotcut.exe in the [SDK](https://shotcut.org/notes/windowsdev/) produces meaningful crash logs with code symbols that can help more, but I still need to be able to reproduce it almost at will in order to confirm a fix. If you can repeat the steps to crash, then it will be helpful to get shotcut.RPT located alongside shotcut.exe.

There are a few places on the web site that link to GitHub especially the new [Contribute ](https://shotcut.org/howtos/contribute/) page and the "GitHub repository" link near the bottom of the Download page. Most users do not understand the meaning of a bug versus a question or feature request, and I do not want to use GitHub Issues as a discussion forum. So, most users are directed through the Forum, which is prominent.
