### ISSUE TITLE
Eliminate arbitrary limits on scale & rotate filter

### ISSUE THREAD

**Issue by DaveJarvis** [mltframework/shotcut#707]
When using images that are 10,000 pixels wide, the scale filter does not permit zooming into the edges. This is because there is a hard-coded limit of 2,000 pixels on the `SliderSpinner`:

https://github.com/mltframework/shotcut/blob/master/src/qml/filters/rotate/ui.qml#L265

Changing this limit to 5,000 pixels would be helpful. A superior solution would be to detect the widest image dimension in the playlist and adjust the sliders accordingly.

**Comment by ddennedy** [comment]
> the widest image dimension in the playlist

That info is not available and very difficult to implement and going to introduce bugs. Besides why playlist only and not the entire project? Why not only the producer to which the filter is applied? That would be easier even though info is not available in the filter UI API at this time. Anyways, all this is much work when there is more important things to do at this time.

**Comment by DaveJarvis** [comment]
In case anyone wants to increase the limits to the sliders:

1. Open `/usr/share/shotcut/qml/filters/rotate/ui.qml`
1. Find `minimumValue: -2000` and `maximumValue: 2000` (around lines 265, 266, 294, and 295).
1. Change the values to `-5000` and `5000`.
1. Find `maximumValue: 500` (around line 226).
1. Change the value to `maximumValue: 1000`.

These changes allow larger images to be panned and zoomed.

> Besides why playlist only and not the entire project? Why not only the producer to which the filter is applied? 

It was merely an idea. The underlying problem persists: there's no way to fully pan and zoom around images that are 10,000 x 4,000 pixels in dimension due to the hard-coded UI limits. Changing these limits as documented above does not appear to incur any bugs (in my limited testing).

**Comment by ddennedy** [comment]
FYI, this was closed because I already increased the limit for the offset parameters. I will make another change for the Scale parameter. Yes, there is very low risk to these changes. The reason to make limits is simply to make a usable range for the slider control. If the range is extremely large and most people spend most of their time in like 20% of the overall range, then it is not so usable. However, in this case, I agree the limits need to be increased. I am also going to think about changing our SliderSpinner control to allow the spinner to have a separate max (or numeric max) from the slider such that one could type in a number to override.
