### ISSUE TITLE
decimal comma / locale breaks transfer between different machines

### ISSUE THREAD

**Issue by grinapo** [mltframework/shotcut#713]
Linux 19.03.01 (en_US) and windows 19.02.28 (hu_HU).
I see lots of issues about locales but this aspect haven't been mentioned:

**Steps to reproduce**
1. create anything with fractional numbers in it, like a filter with fractionals, opacity, your free choice
2. save it on a locale which uses comma as decimals
3. send the file to your best friend using a locale which uses dot as a decimal separator
4. best friend loads the file and realises all numbers are **zero** which did have any fractions (breaking everything from chroma key to ... anything, really)
5. if you both are unaware what  "locale" is, or what a "decimal separator" is, you both will scream and cry a lot without understanding what's happening. :-(

**Resolution**
Do not use locales for XML output: force en_US.UTF-8. Anything else breaks interoperability.

**Related**
*#292 
*#166 
*#186

**Comment by ddennedy** [comment]
I agree, and I am working on this. However, it is a bit of work to ensure old projects that are locale-sensitive load with a repair, to ensure the same for MLT XML loaded as a clip, to fix presets, and to test comprehensively. Thus, this will not be in the next release, but I hope for 19.05.

**Comment by ddennedy** [comment]
This is fixed for the next release.

**Comment by ddennedy** [comment]
This change specifically does not try to convert legacy documents. Most users were saving and loading a project in the same locale, and I do not want the support headache of everyone's projects changing in a fundamental way as they upgrade the app. Rather, it loads them as-is (using LC_NUMERIC in the XML) if the project locale's decimal point matches the system locale's decimal point, and it subsequently saves them using that project's locale. However, if the system locale's decimal point is a period and the project locale's decimal point is a comma, then as before it converts a subset (as you noticed) of numeric values to create a "Repaired" project but with LC_NUMERIC=C (since the conversion target is period). New projects are saved using LC_NUMERIC=C.

**Comment by kparal** [comment]
Will this change also fix #745 (using `level=4.2` in the `Other` tab under locales using a decimal comma)?

**Comment by ddennedy** [comment]
> Will this change also fix #745 (using level=4.2 in the Other tab under locales using a decimal comma)?

It does now; thanks for the reminder.
