### ISSUE TITLE
Press Enter Resets to Source Tab

### ISSUE THREAD

**Issue by andrewk8** [mltframework/shotcut#716]
Windows 10 x64 1810 Shotcut 19.02.28

When you edit a value in the Properties or Filters tabs and press <Enter> the view resets.

See attached video.  I have a project with a clip on the timeline.

Want to change the clip aspect ratio.  Select the clip.  Click the properties tab. Change the horizontal value.  Press enter.  Note that the focus changes from the clip's properties to the Source tab.  Annoying.

Select the clip. In the Properties, change the vertical value. Press Enter.  Focus switches away from the clip's properties, again.

Add a levels filter.  Change the gamma value. Press Enter.  Focus switches away from the levels property.

Pressing Enter to set a value should keep the focus on whatever it was you were doing.
[Press Enter View Resets.zip](https://github.com/mltframework/shotcut/files/3000914/Press.Enter.View.Resets.zip)

**Comment by ddennedy** [comment]
> Add a levels filter. Change the gamma value. Press Enter. Focus switches away from the levels property.

I do not reproduce this. Otherwise, it is a known problem that changing some things in Properties deselects the clip and thus the focus. That is because it must recreate the clip and re-select is currently not implemented (let alone the focus). This is not ideal, and I will leave the bug open and try to work on it.

For me, it does not switch to the Source tab, but I see that happening in your video. Hopefully, that problem goes away when reselection is implemented. Next, I see the bug with the filter parameter in your video, and that is strange because I also do not reproduce it (also not reproduced on Linux or macOS). Is that only when you press Enter or also when you tab out or click into another parameter?


What is your Settings > Display Method set to?

**Comment by andrewk8** [comment]
No (at least for a few filters) it does not flip to the source tab if you hit <Tab>after entering a value in a filter.

DirectX(ANGLE).  I used the 64-bit Windows portable zip to an empty folder. So that's what you get with all the defaults?

I changed it to Automatic.  After it re-started, pressing enter after changing a value highlights the value. See sample.

[Automatic Display.zip](https://github.com/mltframework/shotcut/files/3020553/Automatic.Display.zip)

**Comment by ddennedy** [comment]
Thanks for the answers. Automatic tries OpenGL first before falling back to DirectX depending on the machine; so, it probably is using OpenGL for you in that mode. You might expect Automatic to be the default, but I had a number of people report problems with Automatic=OpenGL and explicitly choosing DirectX fixed it. So, DirectX seems like a safer default. It is interesting that the behavior is different for you as it was just a guess and made no difference for me.

@bmatherly Do you reproduce this on filters when using DirectX?

**Comment by bmatherly** [comment]
I tested all three display methods (OpenGL, DirectX, Automatic). I do not reproduce the problem of switching to the source tab when hitting enter in the filters panel.

**Comment by andrewk8** [comment]
I can reproduce this on two computers and two different builds of Windows 10. Both computers Shotcut portable zip extracted to an empty folder.

- Windows 10 Home x64 1809 - homebrew with NVidia GTX 650 Ti.

- Windows 10 Enterprise x64 1703 - Dell - Intel HD 630 / Nvidia Quadro M2200. Mobile switchable graphics (Nvidia Optimus) enabled. I think this means the system uses the Intel graphics unless there's a trigger for the Nvidia chip to take over rendering of a window. Querying the Nvidia Control Panel says Shotcut is being rendered by the Quadro M2200.  Note: I extracted the 19.02. Launched Shotcut `a minute ago for the first time and inserted a clip.  Display Method comes up as DirectX (ANGLE)
![Dell Graphics Usage](https://user-images.githubusercontent.com/16465258/56777362-0dc53600-679f-11e9-8880-2835ef6766a2.png)


Enterprise computer never had Shotcut prior to this test.

Since I can reproduce this on two different computers, is it possible for you to make a debug build that I could run to try to trap the error??

**Comment by ddennedy** [comment]
> unless there's a trigger for the Nvidia chip to take over rendering of a window

Shotcut does include such a trigger.

**Comment by ddennedy** [comment]
A debug build is a part of the SDK:
https://shotcut.org/notes/windowsdev/

When Shotcut Windows debug crashes it will usually write to a file named shotcut.RPT that contains a backtrace. You cannot use the Microsoft debug tools for Shotcut as it is not using MSVC but rather mingw. So, you would need to use gdb if you want to set breakpoints. Using Qt Creator makes this easier.

**Comment by ddennedy** [comment]
Also, please be clear about what "this" is as you have raised two different issues. The first one is known and simply the current intended behavior. The second when using a filter is not intended and not reproduced.

**Comment by ddennedy** [comment]
> When you edit a value in the Properties or Filters tabs and press the view resets.

To my surprise, this is working now in version 19.04.30! I think I know the unintended related change that fixed this.  Please be aware that the default Display Method changed in this version from DirectX to Automatic. It will only change to default if you never changed it. It is helpful if you can confirm and also retest pressing Enter in a filter field when Display Method is DirectX.

**Comment by ddennedy** [comment]
I reproduce this on macOS (maybe others too, but that is what I am using right now). A key point is to have something in the playlist and selected.

The problem is that <kbd>Enter</kbd> is also delivered to the global shortcut handler which says to open the current playlist item (see [Keyboard Shortcuts](https://shotcut.org/howtos/keyboard-shortcuts/) reference). The **workaround** for now is to use <kbd>Tab</kbd> to apply the change.
I realize this is unfriendly. Moreover, it is not limited to Filters, it also affects Properties (every variant), Export, and Recent. I could work on a change to every UI panel and try to remember to do that. However, there are and will continue to be more pitfalls. So, I am changing this shortcut to <kbd>Ctrl</kbd>+<kbd>Enter</kbd> (<kbd>Cmd</kbd>+<kbd>Return</kbd> for macOS).
