### ISSUE TITLE
Failed to create OpenGL context for format QSurfaceFormat

### ISSUE THREAD

**Issue by BlohoJo** [mltframework/shotcut#722]
Installed latest version (190228) on non GPU computer. It's Win7 x64, used installer shotcut-win64-190228.exe.

Get error on running. I was under impression this supported software emulation / non GPU?

![opengl](https://user-images.githubusercontent.com/8242464/55466055-6d7b5780-55cc-11e9-8f4b-8ca000a575f7.png)

Installation from this repository has libEGL.dll, libGLESv2.dll, and d3dcompiler_47.dll.

I have many applications that require OpenGL that I am able to run by simply copying a [MESA software emulation opengl.dll ](https://github.com/pal1000/mesa-dist-win/releases)into the application directory. That does not work with Shotcut. (I copied the MESA opengl32.dll into the Shotcut directory but the error above persists.) I see there is a opengl32sw.dll file in the Shotcut directory, the "sw" implying "software" so I assumed it was similar to MESA.

Is there any way to get this to run?

**Comment by BlohoJo** [comment]
Just uninstalled and tried shotcut-win64-190127.exe. It works.

**Comment by ddennedy** [comment]
I do not know why the new version does not work for you except that Qt, which uses OpenGL, was upgraded, and it might be using it in a way that is incompatible. Software OpenGL can be made to work. Find `Qt::AA_UseSoftwareOpenGL` on [this page](https://doc.qt.io/qt-5/qt.html). I had a removed menu item for "Software" under Settings > Drawing Method because previously it did not work - probably due to a faulty build process. Now, in the new build, I just tested it, and it works (local 64-bit debug build)! I will re-enable it, and test the 32-bit and release builds. Yes, opengl32sw.dll is Mesa with llvmpipe.

**Comment by ddennedy** [comment]
Software OpenGL enabled in 0bddee46

**Comment by ddennedy** [comment]
Please test the beta, which adds Settings > Drawing Method > Software (Mesa).
https://github.com/mltframework/shotcut/releases/tag/v19.04.21

**Comment by ddennedy** [comment]
I have one system where the new **Settings > Display Method > Software (Mesa)** in version 19.04.30 works and another where it does not.

openglsw32.dll is a patched version of Mesa provided by Qt that does not appear to work reliably because I am now able to drop in the opengl32.dll from Mesa (mingw build), and it works on both systems. It does not work with the Shotcut Software setting, however, if you rename it opengl32sw.dll to overwrite the Qt-provided one.

If you, the reader got here because you switched to Display Method > Software to see what that is or if it is better, and now are stuck with the dreaded dialog
![opengl error](https://user-images.githubusercontent.com/1146683/57206036-ab76ed00-6f77-11e9-993d-58c7744d75ed.png)
Then, here is some information to revert your setting in the situation where one of the other Display Method options does partly work:
- If you are using the Store app, you need to reset the app:
  1. RIght click the app icon and choose **App Settings...**

**Comment by ddennedy** [comment]
Related Qt bug: https://bugreports.qt.io/browse/QTBUG-68407
I am trying to figure out a way for the user to get out of this hell in a more user-friendly way (not editing rergistry, resetting the app, or placing opengl32.dll).
