### ISSUE TITLE
cant add PNG's with no background 

### ISSUE THREAD

**Issue by richyxi** [mltframework/shotcut#735]
im running Shotcut version 19.04.30 on ubuntu 18.04 and im facing an issue with transparency on pngs images bc when i add one, the background turns black like: 
![Captura de pantalla de 2019-05-04 18-59-32](https://user-images.githubusercontent.com/47098907/57186208-4b614780-6ea0-11e9-9eaa-81f8dddec99b.png)

**Comment by ddennedy** [comment]
It works, but you are doing something wrong and not providing enough information. Also provide how you are getting Shotcut (downloaded as tar/appimage, snap, flatpak, package).

**Comment by richyxi** [comment]
i downloaded via ubuntu software center
what could it be the problem, i did the same process of putting an image in an other proyect i did 4 months ago and it worked good now i move the image into the timeline and this happens

**Comment by ddennedy** [comment]
You made a poor screenshot to understand and help you. You show me the properties for V3, which you are not using. If you use V3, it will not work because you have turned off blending. If you have the image on V2, then V2 blending should be something other than Ninguno. One common pitfall is that people hide V1. Each upper track blends with V1. If you hide V1, then there is nothing with which to blend. That is not a bug; it is just how Shotcut works. You can also upload a small project file and PNG that shows the problem. You can put a color clip (not black or transparent) on V1 to have a background so you do not need to supply a video.
