### ISSUE TITLE
19.04.30 requires unreleased mlt++

### ISSUE THREAD

**Issue by FFY00** [mltframework/shotcut#736]
`19.04.30` requires https://github.com/mltframework/mlt/commit/d93c975473838dcc302b06356eba9fc29548b587 which hasn't been released yet. I know often people are quite anxious about getting new releases but please be careful with things like this. I am packaging shotcut for Archlinux and unless mlt gets a new release I can't update shotcut to `19.04.30`.

**Comment by ddennedy** [comment]
I am going to make a new release of MLT with no changes over what was included in our builds of v19.04.30.

**Comment by ddennedy** [comment]
MLT [v6.16.0 is released](https://github.com/mltframework/mlt/releases/tag/v6.16.0) now. As you can see from the [git log](https://github.com/mltframework/mlt/commits/v6.16.0) no code changes were made except for version bumps. From now on, we will add version checks to the Shotcut code to prevent this from happening, but we will remove version checks aggressively as MLT is released because new Shotcut versions will always require the latest MLT release.

Also, please feel to submit pull requests that make your package better as the default Shotcut build is for a relocatable package. But please put any code that is specific to a system install behind a new build-time configuration macro - not to mention anything Linux specific inside a `#if defined(Q_OS_UNIX) && !defined(Q_OS_MAC)` block. Thanks
