### ISSUE TITLE
project file vanished

### ISSUE THREAD

**Issue by ZakiYT** [mltframework/shotcut#746]
I spent 10 hours editing a project in Shotcut when it then proceeded to crash on me. I couldn't even find the file beacuse it vanished. I even saved the project before it  crashed. I'm so angry and mad. I can't stand this. I don't know what to do now. I feel like I never want to edit videos again.
This is absurd!!!! I'm loosing hope.

**Comment by ddennedy** [comment]
I am very sorry to hear about that. I know your feeling as I too have been frustrated by computers, and reports like this almost make me want to give up working on Shotcut at times. You can try to locate your old project as an auto-saved file. In Shotcut menu, go to Settings > App Data Directory > Show.... That opens a file manager window. Go into the "autosaves" folder, and you may see a bunch of strangely named .mlt files in there. I suggest to sort this view by Date Modified and check some of the most recent files.

Regarding the crashing, it sounds like something bad and unexpected crept into the project. However, I, of course, do not know what that is. Rather, I want to focus more on the lost project file problem in this report. You are not the first person to report this, but I have not experienced it myself. At first, I believed it was due to user error by mis-locating a project or accidentally moving it somewhere in a file manager. However, I think I have mainly been hearing about it since the last release. In this version (19.04.30), we made a change to try to prevent saving a corrupt project file. We do this by writing to a temporary file and doing a basic verification of that (well-formed XML) before moving to the target location (including overwriting an existing file in the case where the user saves existing project). I think there is a bug in this that affects a small number of saves. Looking at the documentation for the [rename function](https://doc.qt.io/qt-5/qfile.html#rename) that we use for "moving to the target location" it says:

> If the rename operation fails, Qt will attempt to copy this file's contents to newName, and then remove this file, keeping only newName. If that copy operation fails or this file can't be removed, the destination file newName is removed to restore the old state.

Note the key words: "the destination file newName is removed." I think this can be happening to cause this problem. I will think about a solution or simply reverting this code change.

**Comment by ddennedy** [comment]
I believe I just reproduced a similar problem in auto-save. The auto-saved files go through this same process of save-verify-rename. However, in my case (macOS), the temp file was not removed and the target file became 0 bytes. With additional debug logging on, I could see the rename function reporting failure. This gives me a solid case on which to develop a fix.

**Comment by ddennedy** [comment]
I also found a place in my code where the target file is removed prior to saving. I fixed that as well as built a safety net around the side effects of the rename() function previously mentioned. Thank you for sacrificing your time and will to suffer these consequences and report them so we can improve the lives of other Shotcut users. There will be a new version released very soon with this fix.

**Comment by ZakiYT** [comment]
I can give you a more in-depth detail about what happened: well normally I save my file for every new edit I make. For example, let's say I add a new overlay with chroma key or a simple cut. yea I save after every single thing I do.

So back on point. I was adding an overlay with green screen. Then I mirrored the "overlay"  or the green screen as you can call it on the second time-line on top of the first one. So after I mirrored it. I added the 
"rotate and scale" visual. I proceeded to move the X axis then ShotCut immediately crashed. I figured this was normal since ShotCut does crash on me alot when I edit.

And beacuse it crashes so often, I hit save alot aswell as I mentioned before.

But this time even tough I hit save before I added the chroma key on top of the second time-line with mirror and rotate. I still couldn't find the file.

The file was there on the "recent projects" tab so I proceeded to click it. But It failed to launch that project.

After about something that seems to be 3 minutes, I couldn't even find it on that tab. Even my older projects got corrupted with it. 

I searched up the MLT file destination. And it's now just a shortcut with like a couple of bytes of memory that I can't open in shotcut. 

Verdict: Mirror + Rotate and Scale = DeathTrap


Mirror and Rotate & Scale seems to be working fine on small projects. But the bigger the project is. The more vulnerable it is.

Well that's just my assumption. It might not be both of the effects but something else that happened internally inside the engine when that happened. I have no idea.

**Comment by ddennedy** [comment]
Regarding crash with Mirror with Rotate and Scale (or Size and Position as they both use the same filter in the engine), I will be tracking it here:
https://forum.shotcut.org/t/using-mirror-filter-causes-shutdown/10908
The workaround is to add Mirror **after** either of those filters.

**Comment by ddennedy** [comment]
The crash with Mirror filter has been fixed for the new version 19.06 being released later today.
https://github.com/mltframework/mlt/commit/082f2584fb420b3ef2b87faa417cd16645d98362
