### ISSUE TITLE
Crash when i drag GIF images into the timeline

### ISSUE THREAD

**Issue by TokgoRonin** [mltframework/shotcut#748]
Every time I drag a GIF image into the timeline, the software crashes.I have tried it more than ten times, every time it crash.

**Comment by ddennedy** [comment]
It works for me. What is your OS and Shotcut version? Can you please share the GIF you are using?

**Comment by ddennedy** [comment]
See this thread:
https://forum.shotcut.org/t/can-i-use-gifs/11525

**Comment by ddennedy** [comment]
To fix your project, remove all GIFs from the Playlist. Add your GIF by double-clicking it in Recent, using File > Open.... At this point you may be prompted to convert it, which is going to fail in v19.06 due to bug #739. That bug is fixed in the new version 19.06.15 available tomorrow. Or, you can cancel and press + at the bottom of Playlist to add it. Clicking + will prompt you for a duration. It is not too important to set a correct duration because you can increase it when you add it to the Timeline by dragging the end of the clip.
