### ISSUE TITLE
Shotcut AppImage has wrong version set

### ISSUE THREAD

**Issue by probonopd** [mltframework/shotcut#758]
```
./Shotcut-*.AppImage --appimage-extract shotcut.desktop 
cat squashfs-root/shotcut.desktop 
(...)
X-AppImage-Version=.glibc2.14
```
AppImage desktop integration systems like AppImageLauncher are using this information to display it e.g., in the launcher menu.

![](https://user-images.githubusercontent.com/2480569/61578531-1603e780-aae8-11e9-8ed9-f86e04fde900.png)

`export VERSION=...` before running `appimagetool` should do the trick.

Let me know if you need further assistance in fixing this.

**Comment by ddennedy** [comment]
How do I see the version in the command line outside of AppImageLauncher?

**Comment by probonopd** [comment]
Hi @ddennedy, as I wrote above:

```
./Shotcut-*.AppImage --appimage-extract /shotcut.desktop 
cat squashfs-root/shotcut.desktop 
```

**Comment by ddennedy** [comment]
😳 sorry I just woke up

**Comment by ddennedy** [comment]
We use `pkg2appimage`, and it does not respect the `VERSION` environment variable even if exported. Per the pkg2appimage source, instead I will create a VERSION file.

**Comment by probonopd** [comment]
Uh, using `pkg2appimage` should only be the last resort. Why not do a native AppImage build using https://github.com/probonopd/linuxdeployqt or https://github.com/linuxdeploy/linuxdeploy-plugin-qt? cc @TheAssassin

**Comment by ddennedy** [comment]
Because this is how it was contributed, and now I am stuck to maintain it. I have better things to do with my time than spin my wheels rewriting packaging for a very minority of users. Every Linux package format wants their own native build process integrated, but I get along fine with just the portable archive. Both AppImage and Snap are based on this portable archive. This is working good enough for me.

**Comment by probonopd** [comment]
OK, I understand. Thanks for providing an AppImage. :+1:
