### ISSUE TITLE
Audio. Shotcut Version 19.08.16    Win64

### ISSUE THREAD

**Issue by sad4life** [mltframework/shotcut#764]
MP3 music has plugg in sounds at some parts.

**Comment by ddennedy** [comment]
Your description is meaningless. Reopen only if you can provide the file and some real evidence.

**Comment by sad4life** [comment]
so if u use music from soundcloud or youtube you might hear plugg in noises on some parts that isnt in the audio.

**Comment by ddennedy** [comment]
I do not understand "plugg in noises." If the sound is choppy (sounds like tiny gaps), then it might only be a preview problem when using high frame rate (60) or heavy video processing. You should make a test export and see if the problem is in the export result when played in a media player.

If the audio sounds like metal or a robot, then some people have needed to restart Shotcut or their computer to reset something that went wrong. Others have reported success after using Convert to Edit-friendly in Properties.

Another problem with this bug report is "music from Soundcloud or YouTube." YouTube does not provide downloads or deliver as mp3; so, you must be using something you did not specify to download and convert. I think Soundcloud downloads vary by the author and how they encoded them. I am not going to randomly try shit to reproduce this. I already have a lot of music and audio that works fine.

Another reason you can have a problem is because you are mixing it with other audio, and the levels are clipping, which causes a distortion. If so, you will know because it plays fine in the Source player but not while in the Timeline. Then, you can see levels going over 0dB in the meter or scope. In that case, you need to adjust levels; Shotcut will not do that for you.

For all of the above reasons, this is why the bug report must be specific and provide steps.
