### ISSUE TITLE
Video stabilization filter makes video more shaky.

### ISSUE THREAD

**Issue by Erstus** [mltframework/shotcut#765]
Hello.
When I wanted to use the video stabilization filter, the first odd thing I noticed, was that in the filter menu, it was named stabilise, with an s, not z. I guess that's just a typo, but here's a real problem: I pressed analyse and when it finished, the video was a lot more shakier than originally. It looked as if the filter had done the exact opposite to what it was suppose to, so every little movement got magnified instead.

System version: Manjaro 18.0.4.
Shotcut version: Shotcut 19.08.16.

**Comment by ddennedy** [comment]
> it was named stabilise, with an s, not z

This is because "English (Great Britain)" was selected by you or the system. If you change it to English (United States) it will be "Stabilize" but the Settings menu will still reflect Great Britain, which is a bug that has already been fixed for the next version.

Now, I have reproduced your problem, and it seems some footage simply does not work well.
For example, the second scene in the popular (example video from Windows 95) [wildlife video](https://archive.org/details/WildlifeSampleVideo) has a problem when the birds start flying across. Other scenes in this video work fine. We use the [vid.stab library](https://github.com/georgmartius/vid.stab) to power this. I am afraid that this is a situation where the algorithm it uses is not foolproof, and sometimes it does not work as expected. [Here is a related ticket in that project](https://github.com/georgmartius/vid.stab/issues/55), but reducing shakiness did not work for this test.

Also, there is a known issue that if you change the clip's in point (start frame) after running analyze, the analysis results become invalid, but Shotcut does not reset the filter. In that case, you need to re-run analyze. You can do that by changing the Shakiness or Accuracy parameter or remove and re-add the filter. Likewise, if you add a filter that does some kind of transform (size, position, rotation) **before** the Stabilize filter, then the analysis results are invalid, but again Shotcut does not detect that. Do you think any of those situations apply to you?
