### ISSUE TITLE
How to configure -vaapi_device passed to ffmpeg?

### ISSUE THREAD

**Issue by peti** [mltframework/shotcut#771]
I'm using shotcut 19.09.14 on Linux. My laptop has an Intel chipset that supports VAAPI, but Shotcut won't detect that because it calls ffmpeg with `-vaapi_device $DISPLAY` and that does not work:

~~~
[AVHWDeviceContext @ 0xf11040] No VA display found for device :0.
Device creation failed: -22.
Failed to set value ':0' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
~~~

If you call ffmpeg with `-vaapi_device /dev/dri/renderD128`, however, then it works just fine.

Now I wonder whether there's any way for me to configure those flags? It seems to me like they are hardcoded in the source code?

**Comment by ddennedy** [comment]
You are dealing with automatic configuration. You should try to manually configure using the configure button and then turn on hardware encoder and test Export. The auto configure command line is not configurable but export is if you need that using the other tab.

I will test if auto configure is still working for me or if I need to change it and report back.

**Comment by peti** [comment]
For what it's worth, running

    sed 's#"-vaapi_device" << ":0"#"-vaapi_device" << "/dev/dri/renderD128"#' -i src/docks/encodedock.cpp

before the build fixes the auto-detection. Shotcut now recognizes `h264_vaapi` and `hevc_vaapi` properly.

**Comment by ddennedy** [comment]
Can you please test if this works for you?

`args << "-init_hw_device" << "vaapi=vaapi0" << "-filter_hw_device" << "vaapi0" << "-vf" << "format=nv12,hwupload";`

This is more automatic trying multiple methods and devices without hard-coding.

**Comment by ddennedy** [comment]
Please be aware that I had to change this to `"vaapi=vaapi0:,connection_type=x11"` because only x11 and not drm works in the Ubuntu 16.04-based binary builds we provide and because I prioritize what is needed for our builds. Thus, you will need to patch this in newer VAAPI or kernel to remove the `:,connection_type=x11` to let it be more automatic (it tries drm first). You should also remove the following line, which passes the connection_type to MLT's usage of FFmpeg vaapi:
https://github.com/mltframework/shotcut/blob/master/src/docks/encodedock.cpp#L768

**Comment by peti** [comment]
OK. Thank you for the heads-up.

**Comment by nh2** [comment]
> You should also remove the following line, which passes the connection_type to MLT's usage of FFmpeg vaapi:
> https://github.com/mltframework/shotcut/blob/master/src/docks/encodedock.cpp#L768

Stable-linking for reference:

https://github.com/mltframework/shotcut/blob/e7f8aa69ff94b8ae178efaf1dcacdced646b6b5a/src/docks/encodedock.cpp#L768

**Comment by nh2** [comment]
@ddennedy Could you explain the meaning of the `connection_type` values `x11` vs `drm` a bit, for people new to the topic?

The only docs I found are:

* https://www.mltframework.org/blog/v6.18.0_released/ which only says `connection_type`: x11 or drm
  * This patch where that was added: https://github.com/mltframework/mlt/commit/eb7540f3c8ce64ec5ba410d6bc807469cda0113c
* https://patchwork.ffmpeg.org/project/ffmpeg/patch/618521bf-0807-13a8-2530-12ff7a980dcf@jkqxz.net/ which is an ffmpeg patch to add documentation about `connection_type` that hasn't been merged (so these things apparently remain undocumented in ffmpeg)
* The Wikipedia section https://en.wikipedia.org/wiki/Video_Acceleration_API#Software_architecture and linked image https://en.wikipedia.org/wiki/Video_Acceleration_API#/media/File:Vaapi_illustration.svg

But none of that explains whether `x11` or `drm` is "better", or in which situation which one should be chosen.

In https://github.com/mltframework/shotcut/issues/771#issuecomment-533842055 you comment:

> Please be aware that I had to change this to `"vaapi=vaapi0:,connection_type=x11"` because only x11 and not drm works in the Ubuntu 16.04-based binary builds we provide

but it is unclear to me whether that is legacy and may work with `drm` on newer Ubuntu versions, or what other considerations are relevant.

**Comment by ddennedy** [comment]
I do not really know the difference. I just read some code in FFmpeg to discover the options and tried them to figure out what works. Since that comment, Shotcut's builds are based on Ubuntu 18.04, but I have not revisited this because VA-API seems basically broken for portable binary builds as it is extremely version sensitive. I no longer have the patience to deal with it. The open source community needs to step up if they want this area to improve.
