### ISSUE TITLE
waveform not updated after making transition

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#781]
Shotcut 19.10.10
After creation transition waveform on video is not updated. In fact audio outstrips waveform on time of transition.
![2019-10-20 0000](https://user-images.githubusercontent.com/27248144/67153069-eed9d380-f2eb-11e9-8d05-8ba28bb582b7.png)
![2019-10-20 0001](https://user-images.githubusercontent.com/27248144/67153073-f00b0080-f2eb-11e9-8918-ffd3a402dda2.png)
![2019-10-20 0002+](https://user-images.githubusercontent.com/27248144/67153088-10d35600-f2ec-11e9-8886-68282743bf78.png)

**Comment by ddennedy** [comment]
Are you creating transition by trimming or drag-and-drop/move clip?

**Comment by LedAlex** [comment]
I'm moving clip to the left by drag-and-drop.

**Comment by LedAlex** [comment]
I've figured out that,
![2019-10-20 0003+](https://user-images.githubusercontent.com/27248144/67153425-88f04a80-f2f1-11e9-8b28-8ea2fae881bd.png)
 it's important that clip is longer then visible timeline.
If it's shorter then everything is ok.

**Comment by ddennedy** [comment]
I have not been able to reproduce this. I tried with OpenGL, DirectX, and Software display methods on Windows 10. If you choose Timeline > menu > Reload (F5) does it resolve?

**Comment by LedAlex** [comment]
I've faced that again yesterday. I've not tried F5 (I see your post only now, sorry).
I also tried to reproduce it in clean project, it's not there. I think it happens after some sequence of actions.

By the way I've tried to build Shotcut to debug it. I can't find prebuild mlt for QT Creator. Does it exist somewhere? Maybe nightly builds or something? Compilation of it is not friendly and time consuming, I left if for some other time therefore.

**Comment by ddennedy** [comment]
Look in the site map on the web site for SDKs that includes MLT as well as custom build of Qt.

**Comment by LedAlex** [comment]
Faced it twice more, one time reload helped, other not.
Now I'm experiencing that waves not drawing at all sometimes.
![2019-12-12 0001](https://user-images.githubusercontent.com/27248144/70688578-2e58e680-1cc3-11ea-819a-fde2eded781b.png)

**Comment by LedAlex** [comment]
19.12.31. Reload of timeline helps....

**Comment by jason-wisnieski** [comment]
I'm editing filler words out of several videos this weekend, and I've experienced this consistently. Shotcut 21.02.27, QT 5.15.2 on Windows 10. For me, the steps to reproduce are:

- Start a new project
- Drag a video file in
  - I've had this happen with an MP4 straight out of my screen capture utility and also the "safe" .mlk files
- Drag the video to the timeline
- Leave audio attached
- Scrub to just before the filler word with the mouse, dragging above the timeline
- Press 's' to split
- Scrub to just after the filler word
- Press 's' to split
- Select the segment with the filler word
- Press 'x' to remove
- Click and drag the right-hand clip to the left
  - Overlap to create a crossfade
- While dragging, the waveform shadows out and overlaps the left-hand waveform as expected
- After releasing the mouse button, the waveform snaps back to its original location before the drag instead of overlapping the transition

![Test](https://user-images.githubusercontent.com/7024262/110257737-28f15700-7f6d-11eb-9615-eb1c85cb4adb.gif)

Hope this helps. Good luck!
