### ISSUE TITLE
shotcut recaculate end time by another frame rate unexpectly

### ISSUE THREAD

**Issue by gcrisis** [mltframework/shotcut#792]
win10 家庭版
Shotcut 版本 19.10.20

My clips changed its in and out times unexpected for unknow reason.For clips which is full video or audio without split it's OK, the others which is a part of video or audio have this problem.

before I find the problem ,I do open MLT xml as clip operate and import a mlt file for different frame rate.

Maybe my frame rate changed from 25 to 30 led clips recaculate its start and end time,but I dont know how to recover it ,so I need your help.Thank you!

[gerbv使用.zip](https://github.com/mltframework/shotcut/files/3828714/gerbv.zip)

**Comment by ddennedy** [comment]
Yes, I reproduced a bug with File > Open MLT XML as Clip when the frame rate is different. In the meantime, you should use a consistent frame rate until this bug is fixed. I do not know if I can repair your project, but I made an attempt by changing it back to 25 fps and removing the included .mlt files. If that did not fix it, then I cannot do anything else to repair it.

If you want to try to make `kgz outro.mlt` have a consistent frame rate with this project, **before** adding it back into your project: open it in a text editor other than notepad.exe, locate `<profile>` near the top, change `frame_rate_num` to 25, change `frame_rate_den` to 1, and save it.

[gerbv - changed back to 25 fps.txt](https://github.com/mltframework/shotcut/files/3829117/gerbv.-.changed.back.to.25.fps.txt)

**Comment by gcrisis** [comment]
The problem still exists.
Thank you all the same.I will reedit it.
