### ISSUE TITLE
Improve clarity of Cut and Split at playhead buttons

### ISSUE THREAD

**Issue by miohtama** [mltframework/shotcut#860]
This is Shotcut 20.14.12 and OSX. 

This report is a defect in the sense that it is a UX issue that confuses, especially new users. Also the defect could not get more cosmetic than this one. 

When one presses the scissors button the expectation is that the currently selected element is split at the playhead.

The cut icon on the timeline:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/49922/80289197-6fffa080-873d-11ea-8d89-7bde3e8e9cd9.png">

is used by the other video editors for "Split At Playhead" action. Because this is what you do (or did) back in a day for a physical film with scissors. Especially the users coming from other video editors may expect this action to happen when pressing the button. Meanwhile the Split at played action itself is not obvious from the graphics:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/49922/80289252-c40a8500-873d-11ea-93dc-9bcfcff9e1bb.png">

Some suggestions on how to make the situation better

* Improve Split at playhead icon e.g. by making it look more like two film bits are tear apart (make it look more like film, make the space bigger)

* Use Knife icon for Split at playhead

* Group icons. so that it is obvious that "these are copy-paste actions" and "these are film actions" - in that case scissors icons could be used in boths

**Comment by ddennedy** [comment]
I do not entirely disagree, but there are already separators between groups of icons (it is subtle) and the scissors-for-cut is more familiar to people now than using something to literally cut film. I bet only a handful of the millions of Shotcut users have ever actually cut a piece of film. I have intentionally banned film analogies within Shotcut (e.g., logo, icons, UI labels) because it is a sorely dated practice. Also, it is difficult to avoid some conflicting concepts between Cut, Remove, Lift, and Split just as there there are many similar time-oriented concepts in the main toolbar: timeline, recent, history, keyframes. Immediate complete distinction is nearly impossible, and the tooltips on all these help to quickly clarify.

We rarely make our own icons and tend to use only those from [DefaultIcon](http://www.defaulticon.com/) and [Oxygen](http://www.oxygen-icons.org/), and I have not found anything suitable in them. Feel free to suggest something specific.

**Comment by ddennedy** [comment]
I thought to improve the split icon by making it somewhat resemble the Shotcut logo. After all, its design was inspired by the appearance of two neighboring clips on a track. The light and dark themes use symbolic icons, so it looks like this:

![image](https://user-images.githubusercontent.com/1146683/80321189-fcf33a00-87cf-11ea-93de-90692f27a3a0.png)

With System theme it looks like:

![image](https://user-images.githubusercontent.com/1146683/80321398-9d962980-87d1-11ea-9f7e-98716939f2fa.png)

**Comment by ddennedy** [comment]
I found most other video editors are tool-oriented on the timeline (unlike Shotcut), and have a blade tool using a razor blade icon. Kdenlive and OpenShot use a scissors icon, which is overloaded and neither support a clipboard style of editing. I think this is all I am willing to do to improve here.
