### ISSUE TITLE
Snap version of Shotcut causes issues for vainfo

### ISSUE THREAD

**Issue by mjaggard** [mltframework/shotcut#863]
I've installed the `snap` version of Shotcut and when I run vainfo, I now get an error related to a method not being present in the snap version of the video card driver.

Ubuntu 19.10
Snap core 16-2.44.3 Rev 9066
Shotcut 20.04.12 Rev 64

```
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /snap/shotcut/64/Shotcut.app/lib/va/radeonsi_drv_video.so
libva error: /snap/shotcut/64/Shotcut.app/lib/va/radeonsi_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

Correct driver (I hope!) is installed in `/usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so`

**Comment by ddennedy** [comment]
That is weird that vainfo is getting things out of a snap. I have the snap installed on Ubuntu 19.10, and I get vainfo OK:
```
 vainfo
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.5 (libva 2.5.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Coffee Lake - 2.3.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
```

If you set LIBVA_DRIVERS_PATH, then it can cause this:
```
$ LIBVA_DRIVERS_PATH=/snap/shotcut/current/Shotcut.app/lib/va/ vainfo
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /snap/shotcut/current/Shotcut.app/lib/va//i965_drv_video.so
libva error: /snap/shotcut/current/Shotcut.app/lib/va//i965_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```
Maybe you did this and forgot? The snap (and other build bundles) do contain launcher scripts that set this environment variable because Shotcut bundles these, but that environment variable should not leak into the general shell environment.

**Comment by mjaggard** [comment]
I didn't set `LIBVA_DRIVERS_PATH` previously but I have now and I'm getting the expected results from `vainfo`
I don't know if Shotcut is behaving correctly or not now, encoding takes around twice as long using GPU vs CPU on my MacBook Pro.

**Comment by ddennedy** [comment]
This is not about Shotcut VA-API performance for encoding; that is separate.

The only way vainfo can show it using the snap copy of the library is when that variable is set. Otherwise how will it know about its existence? You should reboot, open a terminal, echo $LIBVA_DRIVERS_PATH, and then run vainfo and show that here. Currently I do not believe this is valid and inclined to close this.
