### ISSUE TITLE
use-after-free bug in shotcut (fix included!)

### ISSUE THREAD

**Issue by marcespie** [mltframework/shotcut#872]
I've spent the last week porting shotcut under OpenBSD. It now works!

Two days tracking a segfault, turns out it was a use-after-free in
qmltypes/qmlfilter.cpp !

The bug exists on every platform, I guess it only shows up on OpenBSD because our allocator is fairly aggressive in filling up free'd memory with garbage.

_I expect the bug to show up everywhere sporadically, it's just much easier to trigger on OpenBSD._ 

Consider:

```
QString QmlFilter::get(QString name, int position)
{
    if (m_filter.is_valid()) {
        const char* propertyName = name.toUtf8().constData();
        if (position < 0)
            return QString::fromUtf8(m_filter.get(propertyName));
        else
            return QString::fromUtf8(m_filter.anim_get(propertyName, position, duration()));
    } else {
        return QString();
    }
}
```

This code is invalid: `name.toUtf8().constData()` is temporary storage, that vanishes as soon as you exit the current statement.  Thus, `propertyName` **cannot** be used.

Diving a bit more into qt, I discovered `qUtf8Printable(x)`, as a shortcut for `x.toUtf8().constData()`.

[qmltypes.diff](https://github.com/mltframework/shotcut/files/4683884/qmltypes-diff.txt)

This patch was prepared against shotcut-20.04.12 and consists of two things:

- using `qUtf8Printable()` everywhere;
- removing the invalid idiom using `propertyName`.

with this, shotcut no longer segfaults on OpenBSD.

**Comment by ddennedy** [comment]
I am aware of `qUtf8Printable()` but I am not interested in using it everywhere. When I am coding in my IDE, I take advantage of the code-completion, and the current approach falls out of that more freely for me. At first I was worried you replaced it across the entire code base, which would cause a lot of conflicts to resolve in our current development branches. Since it was only in qmlfilter.cpp, I will accept the patch as-is, and thank you.

In any case, you are correct about the temporary! I have been bit by that before. I did a code regex search to find a few more instances of this and fixed.

**Comment by marcespie** [comment]
Ah great. I should have grepped.
My IDE tends to be vim, so code-completion is not something I'm aware of most of the time ;)
