### ISSUE TITLE
Hotkeys Ctrl+Alt+R for "Ripple All Tracks" stops  working

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#878]
Shotcut version 20.06.14.

If you click with mouse on menu button and after that another click on panel with buttons in red area hotkeys Ctrl+Alt+R for "Ripple All Tracks" stops  working.

By the way is there hotkeys for another buttons (green rectangle), can you put them in pop up messages, please.
![202-06-16 0000+](https://user-images.githubusercontent.com/27248144/84769957-65e07c80-afdf-11ea-9e0e-95ca596829ae.png)

**Comment by ddennedy** [comment]
This problem is specific to Windows and not new with this version. I have not been able to figure out how to fix it with the high level GUI toolkit this part of the UI uses. This will probably have to wait until we upgrade the GUI library and hope that fixes it. To workaround it, you need to click elsewhere to give focus such as a clip or the player. 

See Help > Keyboard Shortcuts in the menu.

**Comment by ddennedy** [comment]
Since this time, we have upgraded our GUI library Qt several major versions and switched to a different API within the library for the timeline toolbar and menu. I do not believe this occurs but needs retest on a recent version 21.02 or 21.03.

In case other people land here for a related issue... unrelated to the core issue described here where the menu and toolbar become out of sync, see also this related forum post about how some Ctrl+Alt shortcuts do not work in many Windows languages: https://forum.shotcut.org/t/shortcut-remove-a-track/26313
