### ISSUE TITLE
multiple (two) size and position filters cause transition not to render properly

### ISSUE THREAD

**Issue by crysman** [mltframework/shotcut#891]
Two _Size and Position_ filters cause transition not to render properly :(

Steps to reproduce:

1. work with two images, one has non-19:9 ratio
1. apply _Size and Position_ filter to the one with non-19:9 ratio just to make it "zoomed" - without black margins
1. apply second _Size and Position_ filters with e.g. _Slow Zoom In_ preset on both images in timeline
1. make them transition
1. preview - seems to be working
1. save project and quit
1. load project
1. preview - **transition is not rendered properly** - smaller image is not resized ("zoomed") and there is a black border/s or second image shining through
1. try to export in order to see if it's just preview - unfortunately, no, exported video is rendered incorrectly

However, if only one filter is applied, transition is OK.

see below:
![image](https://user-images.githubusercontent.com/5269350/87877059-6b652400-c9dc-11ea-83d4-3239f05ca887.png)

Test projects and source files are available here:
https://drive.google.com/drive/folders/1WZh23mmGta4QTxuKNVZfjJfzyEs3f-bh?usp=sharing

Shotcut 20.07.11 on Ubuntu 20.04 LTS

**Comment by ddennedy** [comment]
This was already fixed for the next version in https://github.com/mltframework/mlt/commit/2c354d6e876811c73d6ae6b5899874e890c2c34d

With that said, it always better to use one of these filters to avoid resampling the image multiple times. If you want to make an image fill the frame you can also use **Crop: Souuce** and check ""Center"". This avoids resampling because it simply removes pixels from the edges before going into **Size and Position**.
