### ISSUE TITLE
Dragging Clip to start of time line causes crash.

### ISSUE THREAD

**Issue by notdodgy** [mltframework/shotcut#893]
Steps.
1. Add Video to time line.
2. Play / move forwards a few seconds
3. Click Cut
4. Select clip adjacent to start of time line.
5. Delete this clip
6. Drag rest of clip left to start of time line
Crash - program closes
This seems to be repeatable.
Using right click / remove on the empty space works fine, so not a critical error once you know about it.

Window Version 10 i5 cpu.
ShotCut version 20.07.11

**Comment by ddennedy** [comment]
Unable to reproduce. I tried over 10 times with 2 different clips with different resolutions, frame rates, and codecs. It helps to be precise and accurate in steps. For example, in step 3 you mean "Split" not "Cut." Cut removes the clip. Also, there are multiple ways to delete a clip with nothing in the UI labeled "delete." There is Lift, Remove, Ripple Delete, and Cut exercised by menu, toolbar, or keyboard shortcut.
Some additional workarounds that use less steps:
- instead of Split, position the play head and press <kbd>Shift</kbd>+<kbd>I</kbd> (set in point with ripple)
- after Split, use Cut or Ripple Delete on toolbar (or keyboard shortcut)
- after Split, right-click clip on the left and choose Cut or Remove from context menu
- turn on Ripple in toolbar (or its keyboard shortcut) and drag left edge of clip to trim in and ripple

**Comment by notdodgy** [comment]
I had used the ][ split icon 

I tried again today and could not reproduce it.

Some other factor may have been involved.  Definitely happened several times on the same file and straight after re-opening shotcut.
I appreciate reproducing an issue is key to fixing it.  
If this happens to me again, I will try and capture as much information as I can.

I also experienced VLP doing strange things yesterday, cured by a reboot, so possibly something like a system / memory issue was going on.

Thanks for looking.

**Comment by gwestwood** [comment]
I had this today, with Shotcut version 20.11.28.
I split and then deleted an initial block of video from the start to about 20 seconds in.
I could drag the clip back to 2 seconds after the start, but it would pull it to the very start any closer than that.  Dragging it to the start (0:00:00) would cause Shotcut to crash.
Ditto when dragging it several seconds forward after dragging it to 2 seconds from the start.
Typically I then resolved it while testing, so cannot now replicate the issue after it happening several times (I only took a backup just before it all worked again and that backup works fine too).

OS: Windows 10
RAM: 48GB, 36 GB free
