### ISSUE TITLE
Transparency in image ignores all layers beneath it except the first layer

### ISSUE THREAD

**Issue by gringrant** [mltframework/shotcut#904]
I have four layers, and one PNG image and one MP4 video. The project is 1080p 16:9 30fps. The image is 4:3 and the video is 9:16 (vertical). The image has a completely transparent section in the middle. I use the size and position filter on the image to scale it up (so it fills the 16:9 frame) and position it. I put it on the 4th layer. I use three copies of the same video on layers 1 to 3, all with their own size and position filters. Only the video on the first layer can be seen in the transparent section of the image on the 4th layer. The videos on the 2nd and 3rd layers are ignored. I exported a frame to see if it was just the editor preview, but it wasn't. If I turn off the 1st layer, and keep the other three on, the transparent section shows black.

Windows 10; Shotcut 20.07.11

**Comment by ddennedy** [comment]
Unable to reproduce:
![image](https://user-images.githubusercontent.com/1146683/91620439-cdeb0180-e944-11ea-84e4-9246b0218f2c.png)

I do not have any audio tracks. Make sure V1 is turned on and all Size and Position filters have alpha=0 for their Background color and post a screenshot. Or even better, reproduce it in a separate most minimal project and upload the project file (rename it as .txt so GitHub accepts it).

>  If I turn off the 1st layer, and keep the other three on, the transparent section shows black.

All upper video tracks are composited onto V1. Do not turn off V1 if you are compositing. Otherwise, you are turning off the composited destination.
