### ISSUE TITLE
Black screen for Video and Video Tab is disabled in Properties for a compatible video

### ISSUE THREAD

**Issue by durgaswaroop** [mltframework/shotcut#910]
Hi, I think I'm hitting a weird bug here. I am on Windows 10 with the latest shotcut version 20.09.13.
I have a video file that was working fine before. I have resized it outside and used the same name. From then, I am seeing a black screen when I play the clip. Other videos in the project play fine.  It is just with this particular video. 

I tried restarting the project, removing the proxies among other things but nothing worked. I just see a black screen while playing that clip from the timeline. 

I am **able to** play the clip from the source tab. So, it is not a code issue. 
What could be causing this issue?

Any suggestions?

**Comment by ddennedy** [comment]
It is common to break seeking on a file when you use something like:
- lossless cut or trim
- Avidemux copy mode
- Shotcut Properties > Extract Sub-clip
- so-called pass-through editing

This is not something Shotcut will support. What happens when you simply try to play the file separate from the project within Shotcut? How about another media player?
You can try using Shotcut > Convert on the file, and that will transcode it to a high quality intermediate or truly lossless, but even that may not help.

**Comment by durgaswaroop** [comment]
Maybe I don't understand what those mean but I don't think I have done any of those four.
Shotcut can play the same file if I open in a new project. Vlc media player can play it too. 

But I want to understand, isn't what I've done a common use case? I've changed the quality of the file but it still has the same length and name. Can't shotcut work directly on that? Isn't it sort of like proxy editing?

**Comment by durgaswaroop** [comment]
If this cannot be fixed, is there another way I can salvage the work done in the project so far?
Can I recreate a new project somehow that can get it working?
I have spent almost 2 hours on my current edit. Don't want to lose all of that.

**Comment by ddennedy** [comment]
Another important point is that edits in the project are relative to the beginning of the original file. Replacing it with a modified version that has a different starting point messes up all the timing. It is quite possible the black video is because shotcut is looking for frames at offsets beyond the end of the video. The tool cannot understand what you did. Like you changed the ground underneath it. You can replace the file with the original file or replace affected clips by using the original file. This is not a bug; it is your failure to manage the files correctly and maintain the integrity of your project.

**Comment by durgaswaroop** [comment]
I am not sure what you mean "failure", as I said all I did was replace the file with a lower resolution of the file. It has the same length. Isn't that how proxy editing works? Before proxy editing was added isn't that how people did editing on high quality clips?
You edit on a lower quality clip and then replace that with the original clip. What is so wrong here?

**Comment by ddennedy** [comment]
Also I think you have not explained “resize it”. If you simply transcoded or changed resolution, then possibly you changed the order of the contained audio and video streams from the original. In that case, visit the Properties of each s affected clip and reselect the audio and video tracks inside Properties

**Comment by durgaswaroop** [comment]
How do I change the streams? The "video" and "Audio" tabs are disabled for the edited sections of the video on the timeline. 
And when I click properties from the playlist, I see Track1 selected for both Audio and Video. What do I need to change here?

I tried replacing the file with the original file (Removed the lower resolution file and renamed the original file to the same name) but even then I only black.

**Comment by ddennedy** [comment]
In the right click menu on a timeline clip, there is a Replace operation. For each affected clip, you can load the clip you want to use in Source, set the in point, and choose Replace.

**Comment by durgaswaroop** [comment]
When I do it, it is replacing each section of the edited clips from the start of the original clip. Setting in points manually for all of the individual pieces in the timeline (I have over 50 small sections) would be really time consuming. Is it possible for me to figure out the start and stop points of a clip on the timeline w.r.t to the original clip? so, that I can just use them for the new one as well.

**Comment by ddennedy** [comment]
Edit the xml project file in a text editor and remove all of the lines with “audio_index” or “video_index”

**Comment by durgaswaroop** [comment]
Did that. Unfortunately the video still shows black. I guess there is nothing left but to restart the whole thing again.
Thanks for the help anyway.
