### ISSUE TITLE
Add libdav1d to FFMpeg build to support AV1 files

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#919]
As reported here:https://forum.shotcut.org/t/video-clip-loads-in-with-no-visuals-blank-white/21552
AV1 decoding does not work.

Example clip:
`youtube-dl https://www.youtube.com/watch?v=370zqr5Z_4E`

**Comment by eszlari** [comment]
I have enabled dav1d on `flathub-beta`, but the performance is bad and I get this warning:
```
[libdav1d @ 0x56019e371000] The deprecated avcodec_decode_* API cannot return all the frames for this decoder. Some frames will be dropped. Update your code to the new decoding API to fix this.
```

**Comment by ddennedy** [comment]
I fixed decoding all frames in my working copy of MLT today by adopting the new decoding APIs `avcodec_send_packet()` and `avcodec_receive_frame()`. This plays well sequentially now, but seeking is not at all reliable. Briefly testing the code changes against other formats like VP9/Opus WebM, H.264/AAC MP4, and AVCHD TS shows the decoding changes working fine and with no seeking problems. Already this code change has me a little concerned about frame threading. And it looks like we may have some major change needed to fix seeking on AV1, which greatly concerns me. Touching any of the seeking code is extremely risky in general as this code has many years and users of testing and feedback and seeking is something absolutely, fundamentally critical to a video editor.

For the first version to include this (20.12), I might only do something where we enable dav1d in FFmpeg but reject it in Shotcut so that users must use **Properties > Convert** to use it in Shotcut.

**Comment by bmatherly** [comment]
In order to reduce the risk of regressions, I wonder if we should create a new producer named avformat2 where we leap to the latest API and leave all legacy support behind. We could easily modify Shotcut to switch between avformat and avformat2. The first release would only be for developers and testers, the second release could be "opt in", the 3rd release could be "opt out" and the final release could only use avformat2 after the code has some heritage. At that time, it could be renamed to avformat and replace the current implementation. Maybe more work than it is worth - just trying to think outside the box because I agree with the risk of regression and I think that as long as we are taking a risk, we might as well clean up any other code in the module that we want.

**Comment by ddennedy** [comment]
I have this working good now in a branch in MLT: https://github.com/mltframework/mlt/compare/ffmpeg_deprecations
It did not require heavy changes to seeking thankfully. Requires more testing but looks very promising.

**Comment by ddennedy** [comment]
This was added to the builds in 16844465. We will show a Convert to Edit-friendly dialog when AV1 is detected. Eventually, there will be proper support for playback and even editing, but it is generally not desirable for editing, and this dialog may be presented indefinitely. Improved playback and seeking activity is tracked in MLT PRs and branches.
