### ISSUE TITLE
Massive performance issue in medium sized project on Windows 64bit - related to video thumbnails?

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#925]
Affects 20.09.27 64bit Windows (also affects 20.10 Beta).

**Update**: the playback-related part of the problem **vanishes**, if I disable "show video thumbnails". Sorry, if this caused any confusion, but there are simply too many options that I might try them all before creating a new issue.

I have a 1080p [project](https://drive.google.com/file/d/1ZtItOkDv2HQ3YlKqJUrZyilc1ByY0IsJ/view?usp=sharing) of slightly over 20 minutes with 5 video and 2 audio tracks and a few hundred scenes.
Shotcut is running on a Ryzen 7 3700X with 32 GB of RAM, installation and data is on a SSD that easily does several 100MB/s IO.

When trying to playback from beginning, performance is OK - even though there are multiple layers with crhoma keying text overlays, blur etc. However, there seems to be a MASSIVE performance impact after I reach about 50 seconds into the project, despite nothing special going on there in terms of complexity i.e. only 1 video and audio track active, no fancy stuff at all. It slows down to a crawl (several seconds per frame!) and memory consumption goes up until out of memory (i.e. much larger than 20 GB). UI becomes unresponsive. 

If I manage to stop playback before it runs out of memory, shotcut seems to recover, CPU usage returns to almost zero and the UI becomes responsive again - however, most of the RAM seems to remain allocated anyway.

Interestingly enough, playback once again works fine when I am near the end of the project (again less than 1 minute from the end), although there is plenty of effects going on. This even works when I start playback somewhere in the "bad" zone but near enough to the end - it just magically "heals" and playback continues with the expected performance.

The only difference that I can spot in the project itself is the frequent use of transitions in the main part of the project.

Preview scaling, display method, disabling audio waveform display, visibility of layers etc. - nothing I tried seems to make any difference AT ALL.

It should be noted that playback isn't the only thing that's affected, e.g. adding a clip to the project can get ridiculously slow too (operation may take several seconds with high CPU load). Opening the project alone is creating a very high CPU load for a few minutes (and this remains true even if video thumbnails are not displayed)

**Comment by ddennedy** [comment]
You can try with this nightly build where I have done some tuning to reduce memory usage in general:
https://s3.amazonaws.com/builds.us.meltytech/shotcut/shotcut-win64-201102.zip

**Comment by ddennedy** [comment]
With  it has over 140 MP4s in it, this is a large project for Shotcut. After replacing the media, I played the timeline from beginning-to-end in v20.10.31, and it used up to 6.2 GB, and I did not suffer the problem you described. Of course, it may make a difference with different media. Next, I removed the database where thumbnails are stored and tried again with v20.09.27. It used up to 8.1 GB. It helps that I substituted every MP4 with the same 720p clip, every MP3 with the same one, and every JPEG and PNG with the same of each. Every clip is object is a still a uniquely opened file with its own cached data , but many waveforms still image thumbnails are going to be redundant requests that are consolidated. Thumbnailing and waveform background threads is already limited to 4 (less if you have fewer CPU threads).
After that test, within the same session, I zoomed in on the timeline to about 60% and increased track height a few increments to create larger and more UI objects that can consume memory. Memory usage went up to 8.6 GB. Next, I opened every playlist item, and memory usage only went up to 8.7 GB. I realized I only had thumbnails showing for in points; so turned on thumbnails for in and out points in the playlist: memory usage fell.

**Comment by Gizemquea** [comment]
Sorry that I didn't reply any sooner. I've been on a long distance hike - that's what my videos are about. :)
Just to make sure I got my point across, I was **not** talking about memory consumption upon loading the project. Your numbers are not that much different from mine (using the original files) in this respect.
My original report says that memory usage kind of explodes if you try to **play** the video from a location somewhat "in the middle". It does so **only** if you play AND **only** if video thumbnails are active and **only** if the timeline actually seems to move during playback (that's probably why it seems to work if the playhead is positioned right at the beginning and close to the end of the project).
I _suspect_ that shotcut does something with the video thumbnails when it refreshes the timeline during plaback and it will make a huge difference whether you're using >100 different video clips or just one identical clipl
I will try the nightly build and give feedback ASAP, but I am rather busy ATM just having returned from vacation. Meanwhile thanks a lot that you're looking into this.

**Comment by ddennedy** [comment]
I think you missed reading the parts where I mentioned playing. Every test involved playing the entire project with scrolling.

**Comment by Gizemquea** [comment]
Sorry about that. Do you think it would help if I just replaced all the different files in my project with one clip only and try out if this reduces memory consumption as expected? This would rule out any influence from my setup (be it installation or machine).

**Comment by ddennedy** [comment]
I did some more tests on this today on a different system and a different single MP4. This system has a mobile Intel processor with 8 CPU threads, 16 GB RAM, and Intel Iris Plus graphics with Windows display scale 200%, and Shotcut using DirectX Display Method. Testing with v20.11.05 nightly, the timeline playback test made it use up to 12.8 GB peak. The application never crashed, the memory was never completely exhausted, but Shotcut was mostly unresponsive during this time and basically unusable. However, it did finally stop at the end of the timeline, reduce memory, and became responsive again.

Next, I restarted, turned off thumbnails and waveforms, loaded the project, and played the entire timeline. Now, it peaked at about 5.4 GB RAM usage, was mostly responsive and updating the preview, and completely usable.
Next, I restarted, turn on thumbnails only, loaded the project, and played the entire timeline. This was going fine for a while staying under 5 GB RAM to my surprise. But I decided at about the 5 minute point to pause and change from playing at 4X to resume at playing 1X. That is when things fell apart and back to using 13 GB RAM and becoming unresponsive yet still not crashing until eventually finishing, dropping memory usage drastically, and becoming responsive again.

With these options (thumbnail on, waveform off), initial load of the project only consumes about 1.1 GB RAM. Zooming timeline out to show all and then back in to about 33% and scroll by paging (click empty part of scroll bar) through the entire timeline is fine and only increases RAM to about 3 GB. Switching Display Method to OpenGL does not make a difference.

Repeating the same timeline playback test with thumbnail on, waveform off on version 20.07.11, and it is fine! I even paused and resumed. It only peaks up to about 3.5 GB RAM. Turning waveforms back on, and it is still fine even though RAM usage goes up and scrolling is slower. After this version, I made a change to hide thumbnails and chunks of waveforms that are not within the scrollview's current viewport in order to improve the speed of zoom in and zoom out, which it did. However, these many expressions are causing a slowness due to many expressions being evaluated on every horizontal movement of the timeline. 

Simply removing these new expressions on the thumbnails cleared up the problem. There were additional expressions added to waveform chunks and timeline ruler items, and removing the expressions from those does degrade the zoom in performance on this project.

**Comment by Gizemquea** [comment]
Great to hear that you were able to reproduce the issue and found something that explains the behavior and fixes the problem in your test.

I just tried 20.11.05 and the initial CPU and I/O strain when opening the project is indeed gone. With my original project, 20.09.27 read >30 GB from my drive before it was "ready" - 20.11.05 doesn't seem to do that anymore.

I know that your most recent changes to restore playback performance to normal will only be present in the next nightly build 20.11.06, so I'm going to wait for that although I don't doubt that this acutally works with the original project file too.

Thanks a lot for your help!

**Comment by ddennedy** [comment]
Nightly with this fix https://s3.amazonaws.com/builds.us.meltytech/shotcut/shotcut-win64-201106.zip

**Comment by Gizemquea** [comment]
> Nightly with this fix https://s3.amazonaws.com/builds.us.meltytech/shotcut/shotcut-win64-201106.zip

20.11.06 works as expected with my original project. The performance issue is gone and memory consumption seems reasonable now (not much more than 5 GB in this project).

This is a real life-saver for me, thank you!
