### ISSUE TITLE
Rich Text Scrambled Letters in all Linux distros. 

### ISSUE THREAD

**Issue by faithflux** [mltframework/shotcut#930]
I had test this on Debian, Ubuntu, Fedora, KDE Neon and Kubuntu with the same results. The rich text editor is unusable. It will scramble the letters no matter the font I use, the font size or display manager. 
![test](https://user-images.githubusercontent.com/73503905/97237793-3ed05d80-17be-11eb-8ca6-1990742579ea.png)

**Comment by ddennedy** [comment]
It depends on the font size, operating system, and maybe even the typeface. Did you try reducing the size? I don’t know to fix it. Maybe it is a bug in Qt or a library it uses such as freetype. A patch or further research is welcome. What happens when you deselect the filter? (That uses a slightly different renderer.)

**Comment by faithflux** [comment]
I tried multiple font types and sizes. I tried reducing the size as well increasing it. I know that a lot of us in Linux use Shotcut. But this is really bad if you can use rich text. By the way It works great on Windows 10 and it doesn't have this problem.

**Comment by faithflux** [comment]
I discover the issue. It is the display method. If I select Mesa, it works great. But if I select OpenGL then I get the issue.

**Comment by ddennedy** [comment]
I was going to suggest trying that if you are not using nvidia. That is why I asked how it looks without the filter selected. When the filter is selected, it is using OpenGL to draw the UI over the video, which is also displayed using OpenGL. What is your GPU? The filter works for me on my integrated Intel CPU on Ubuntu 20.04 up until a very large size, which is why I put a maximum of 1000 on it. Basically, this is an OpenGL interoperability bug between Qt (we use a very high level API of it) and the driver+hardware. I do not suggest using Mesa as your display method, and it is slower (affects video preview as well). I think the only thing I can do is to offer an external editor (not overlayed) that opens in a new window as an alternative. 

It is possible the Qt version will make a difference, and you can try the [beta](https://github.com/mltframework/shotcut/releases/tag/v20.10.24) which upgrades the portable, AppImage, and snap to Qt 5.15.1 (the flatpak was already on this version).

**Comment by faithflux** [comment]
I have a HP Z1 workstation with an NVIDA Quadro K4000m graphics card. I am
using the open source driver. Maybe I should use the proprietary one.

**Comment by ddennedy** [comment]
We are not able to workaround OpenGL interoperability problems between Qt and the poor nouveau driver.
