### ISSUE TITLE
Rich text does not export in some cases (Sample MLT provided)

### ISSUE THREAD

**Issue by mengelagi** [mltframework/shotcut#960]
[Info   ] <Application::Application> Starting Shotcut version 20.10.31 
[Info   ] <Application::Application> Windows version 192 
[Info   ] <Application::Application> number of logical cores = 4 
[Info   ] <Application::Application> locale = QLocale(French, Latin, France) 
[Info   ] <Application::Application> install dir = "C:/Program Files/Shotcut" 
...
[Debug  ] <EncodeDock::on_encodeButton_clicked> 113629511680 bytes available on "C:/" 
[Debug  ] <MeltJob::start> "C:/Program Files/Shotcut/melt" ("-verbose", "-progress2", "-abort", "C%3A%2FUsers%2FBAZ%2FAppData%2FLocal%2FTemp%2Fshotcut-Dlhceq.mlt") 
[Info   ] <AbstractJob::onFinished> job succeeeded 

When exporting rich text, it does appear in the exported video.

Attached in the archive is very simple MLT file that reproduce the problem with only one transparent zone using a rich text filter.
The text is moving from bottom to top using keyframes.

[testExport.zip](https://github.com/mltframework/shotcut/files/5580467/testExport.zip)

**Comment by ddennedy** [comment]
The problem is that your text does not have any color. And the text engine defaults to black for text because it is word-processor-oriented where black on white is the default. It just so happens to look near white to you because you are running the dark UI theme, and the GUI control is following that in the absence of color. The workaround is to select all of the text and change the color. Shotcut defaults to opaque white. I do not know how you got it into this state, but a defined color is not something I can enforce. In a version before 20.10.31 it could get into this state by deleting all of the text.

**Comment by mengelagi** [comment]
Thank you for the answer @ddennedy . It helped me to correct the issue. 

Now I understand how the problem occurred: when you delete all the text in a rich text filter, you loose the color attribute while when adding the first text the color was correctly set to white.
I think this can be an issue for other users since the WYSIWYG is not the same in edit mode and at export.

**Comment by isync** [comment]
Had this problem. Noticing that text had actually no color and then adding a color fixed it. Unfortunate that the default UI color masks this state.
