### ISSUE TITLE
Question: how do you make money?

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [mltframework/shotcut#981]
Hi Dan (@ddennedy), I started using Shotcut just a few days ago on my Linux Ubuntu 20.04 laptop. I'm a software developer now too, and am an avid open source user and lover of open source. When I was deciding which video editor to use the other day, after an evening of research, I tried OpenShot briefly, quickly saw it wouldn't meet my needs, then watched this video, and [at this point right here](https://www.youtube.com/watch?v=FVgu4E2CzFY&t=245s), decided I better give Shotcut a try. I've been tinkering with it all this evening, and so far am thoroughly impressed. 

I am always intrigued by open source software this powerful and developed (because I want to be as knowledgeable and influential as you) and I assumed this program would have been made by a small company of 5 to 10 people. The contributor graph (https://github.com/mltframework/shotcut/graphs/contributors), however, shows it's pretty much just you. 

So:

1. How do you make money doing this? 
2. How do you find the energy to do it? 
3. Do you make money doing it? (hopefully yes). 
4. Are incredible projects like this really just fueled by utter passion and drive of one individual? 
5. Or, is it providing you an income and means of supporting yourself somehow too? 

I'm so tired all the time from my main job I can't understand how to progress my side projects anymore unless they were my main projects and provided my income. 

If COVID wasn't going on, I'd love to go get donuts and chat your ear off sometime. I may live as close as 20 minutes from you. Feel free to extract my email from a commit and email me if you'd like to meet up sometime. I'm looking to learn from people like you.

Thanks for the time. I'm genuinely intrigued to know the answers to the questions above.

**Comment by ddennedy** [comment]
Thank you for the complement, and I will close this as we only use this space for bug tracking.

1. advertisement on the website and forum and app for sale in the Microsoft Store
2. It might due to a mental or personality condition, but also it comes from doing a little bit almost every day for many years.
3. yes
4. I started contributing to open source in 2001 and started on the engine for Shotcut ([MLT](https://mltframework.org/)) in 2004. During the 2000s, companies contracted me for small, short-term work related to the projects that I did. However, I did not start making money with Shotcut until I started the advertising, and that started out very small only hoping to cover my build and Internet hosting expenses. Yes, it is driven by passion and hobby, but it definitely helps that almost always there is one other individual that is helping a lot or whose work I have used to build upon.
5. yes, but I have only worked on it for about 10 months as a full time job. I went back to part-time employment because I was offered an interesting project, and I wanted to get out of the home office and work closely with colleagues. 

I am tired a lot too. When I was younger I sacrificed a lot of sleep working well into morning hours or sometimes skipping a night of sleep altogether. Also, I am sure personal relationships, social life, and possibly physical and mental health were affected as well. So, I think people should be careful about devotion to their passions and hobbies.
