### ISSUE TITLE
bug: Export presets not in sync with Advanced config unless you mouse click or press Enter

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [mltframework/shotcut#986]
Ubuntu 20.04  
Shotcut 20.11.28

In the image below, if you use the arrow keys to move the selection on the left up and down among the various presets, the Advanced config menu (circled) gets out-of-sync and doesn't update unless you mouse click on a preset or press Enter on a preset with the preset selected. This seems like buggy behavior, as I'd expect the Advanced config section to auto-update to match the selected preset on the left as I change the selection up and down with the arrow keys as well. 

![image](https://user-images.githubusercontent.com/6842199/102702203-fad56400-4214-11eb-889f-bfcefd87ec8c.png)

**Comment by ddennedy** [comment]
This is by design.

**Comment by ddennedy** [comment]
Let put this another way. I guarantee that if I change this then someone else will file a bug that says, "Selection does not imply activation. I accidentally pressed the down key and got something I did not want." You cannot please all the people all the time.
BTW, in your screenshots, nothing in the video tab that you circled implies anything to do with the YouTube preset. Most presets do not affect the video tab, again, by design. Only the ones that have a video mode in paranthesis or possibly your custom ones do.

**Comment by ElectricRCAircraftGuy** [comment]
> BTW, in your screenshots, nothing in the video tab that you circled implies anything to do with the YouTube preset. Most presets do not affect the video tab, again, by design.

Thanks. That's good to know. What do the presets control then? Just the Codec, Audio, and Other tabs? What controls the Video tab? Settings --> Video Mode?

**Comment by ddennedy** [comment]
The video tab is generally based on the Video Mode. Changing it from the video mode still uses the video mode. If changed, it renders to the video mode and then reformatted to the export video settings by scaling, padding, and adjusting frame rate. For example, putting a 16:9 project into 4:3 export results in letterbox (Remember seeing movies on old SD TVs?).
What exactly changes depends on the preset, but generally, yes, those other tabs.
I will think about this more. I can definitely see that some people might cursor down to a preset and then not get what they expected. It's a real toss-up, and as we do not know which way the 80/20 rule applies. Consider that Shotcut has been around for 8 years with this functionality and is downloaded over 500k times a month for the past year, and this is the first time it has been brought up.

**Comment by ElectricRCAircraftGuy** [comment]
> You cannot please all the people all the time.

This is absolutely true, and ultimately it is your call. 

> I guarantee that if I change this then someone else will file a bug that says, "Selection does not imply activation. 

This may happen, but I suspect it will not. I can't see why someone would intentionally change the selection with the arrow keys while not intending to activate the selection. If they don't want to activate another selection, they wouldn't move the selector with the arrow keys. 

> and is downloaded over 500k times a month for the past year

That's really really impressive. Nice work!

> this is the first time it has been brought up.

That's because I've never used it before. :) 

In all seriousness though, I have a strong attention to detail, and am willing to go the extra mile. I tend to take the time to bring up even the small details, although I think most people don't consider it worth their time.

**Comment by ddennedy** [comment]
I am definitely re-evaluating the significance of this because changes are hidden behind not only tabs but advanced mode combined with the fact that exports take a long time. Moreover, I found that, at least on macOS where I am typing now, the Enter key does not activate either, only a mouse click does. At the very least that needs fix. @bmatherly what do you think?

**Comment by bmatherly** [comment]
My opinions:
1) If a line is highlighted, it should be activated (and the right pane should update to match)
2) It would be OK with me if we disable arrow up/down for that list and just require clicking to select

I also observe some inconsistencies in the UI for list highlighting:
* The filter list does not accept arrow up/down to highlight/select different filters
* The playlist allows arrow up/down to highlight different clips. But nothing changes. What does it even mean to be highlighted in the playlist?

In general, for a list, I think there can be a difference between an item being "selected" and being "current"
See here:
https://doc.qt.io/qt-5/qabstractitemview.html#details
The standard behavior seems to be:

Keys | Functionality
-- | --
Arrow keys | Changes the current item and selects it.
Ctrl+Arrow keys | Changes the current item but does not select it.

Is there a way to have a different visual indication for what is "current" and what is "selected"? Like maybe current would be highlighted and selected would be outlined or a different color? If not, then we should decide that selected=current=activated.

**Comment by ddennedy** [comment]
Today on Linux, I found that <kbd>Enter</kbd> does activate the new selection.
Regarding @bmatherly input above, it still seems activation is separate from selection. You select some things and choose an action, and a click or enter key activates (chooses default action). See https://doc.qt.io/qt-5/qabstractitemview.html#activated
But also notice it says "current." The distinction between current and selected is not entirely clear, and I suppose that is left for the developer to decide. See [setCurrentIndex](https://doc.qt.io/qt-5/qabstractitemview.html#setCurrentIndex) expresses some aspect of being synonymous especially in single selection mode. In Playlist, there is a distinction: an item is current if it has been opened in the Source player by activating it. Otherwise, selection is for actions. These are the same until you select an item without activating it, which at that point, nothing indicates the current item.
Another reason I find selection and activation are separate is because there was no way to accomplish this change via the Qt UI design tool and signals. To make it work, I had to subclass the treeview to rewire something, which is inconvenient for a very mature toolkit like this (but also not too bad).
